### ISSUE TITLE
Kapt and dexBuilder significantly slower on feature module ABI change after migrating to Hilt

### ISSUE THREAD

**Issue by aconda-mercari** [google/dagger#2031] opened 2020-08-08 12:17 UTC
I used gradle-profiler to benchmark and scan with abi (add public method api) and non-abi (update method body) change scenarios on a feature module.

A clean build takes around 6s for kapt for our current 21-module project. I'm concerned Hilt is triggering a partial rebuild as it's already taking 2s even though I am only adding a new method (or simply changing a method body) on a single feature. Also `dexBuilder` is also weirdly taking some time.

Is this working as expected in this scenario? I feel Hilt or Dagger shouldn't be reprocessing classes too much especially since I didn't add any new dagger-related code. This also implies that the dagger tasks will be running every-time for every build on any kind of change.

**I worry Hilt will not scale very well on when the project gets larger.**

Snippet of the BuildAnalyzer results:
```
...
:app:kaptDebugKotlin 2.4s 34.2%
:app:dexBuilderDebug 2.1s 30.1%
:feature_sample:kaptDebugKotlin 0.7s 9.2%
:feature_sample:compileDebugKotlin 0.6s 8.1%
:feature_sample:kaptGenerateStubsDebugKotlin 0.5s 6.5%
...
```
Note that the app module only have a single class `CustomApplication` annotated with `@HiltAndroidApp`.

Kapt-related logs with `kotlin.verbose` enabled
```
> Task :app:kaptDebugKotlin
[INFO] All Javac options: 
[INFO] Kapt3 is enabled (stand-alone mode).
Annotation processing mode: apt
Memory leak detection mode: none
Show processor time: false
Verbose mode: true
Info as warnings: false
Use light analysis: false
Correct error types: false
Dump default parameter values: false
Map diagnostic locations: false
Strict mode: false
Detect annotation processors in compile classpath: false
Incremental annotation processing (apt mode): true
Project base dir: /Users/allan/AndroidStudioProjects/app-hilt-migration/app
Compile classpath: <manually ommited>
Sources output directory: /Users/allan/AndroidStudioProjects/app-hilt-migration/app/build/generated/source/kapt/debug
Class files output directory: /Users/allan/AndroidStudioProjects/app-hilt-migration/app/build/tmp/kapt3/classes/debug
Stubs output directory: /Users/allan/AndroidStudioProjects/app-hilt-migration/app/build/tmp/kapt3/stubs/debug
Incremental data output directory: /Users/allan/AndroidStudioProjects/app-hilt-migration/app/build/tmp/kapt3/stubs/debug
Annotation processing classpath: ...
Annotation processors: 
AP options: {room.schemaLocation=/Users/allan/AndroidStudioProjects/app-hilt-migration/app/schemas, dagger.fastInit=enabled, dagger.hilt.android.internal.disableAndroidSuperclassValidation=true, room.incremental=true, kapt.kotlin.generated=/Users/allan/AndroidStudioProjects/app-hilt-migration/app/build/generated/source/kaptKotlin/debug}
Javac options: {-source=1.8}
[incremental apt] Changed files: []
[incremental apt] Compiled sources directories: /Users/allan/AndroidStudioProjects/app-hilt-migration/app/build/tmp/kotlin-classes/debug, /Users/allan/AndroidStudioProjects/app-hilt-migration/app/build/intermediates/javac/debug/classes
[incremental apt] Cache directory for incremental compilation: /Users/allan/AndroidStudioProjects/app-hilt-migration/app/build/tmp/kapt3/incApCache/debug
[incremental apt] Changed classpath names: com/sample/fragment/SampleFragmentKt[INFO] Need to discovery annotation processors in the AP classpath
[INFO] Annotation processors: dagger.hilt.processor.internal.root.RootProcessor, dagger.hilt.android.processor.internal.testroot.TestRootProcessor, dagger.hilt.android.processor.internal.uninstallmodules.UninstallModulesProcessor, dagger.hilt.processor.internal.definecomponent.DefineComponentProcessor, dagger.hilt.android.processor.internal.bindvalue.BindValueProcessor, dagger.hilt.android.processor.internal.customtestapplication.CustomTestApplicationProcessor, dagger.hilt.android.processor.internal.androidentrypoint.AndroidEntryPointProcessor, dagger.hilt.processor.internal.aggregateddeps.AggregatedDepsProcessor, dagger.hilt.processor.internal.originatingelement.OriginatingElementProcessor, dagger.hilt.processor.internal.aliasof.AliasOfProcessor, dagger.hilt.processor.internal.generatesrootinput.GeneratesRootInputProcessor, dagger.internal.codegen.ComponentProcessor, androidx.hilt.AndroidXHiltProcessor, androidx.room.RoomProcessor
[INFO] Processing java sources with annotation processors: /Users/allan/AndroidStudioProjects/app-hilt-migration/app/build/tmp/kapt3/stubs/debug/error/NonExistentClass.java, /Users/allan/AndroidStudioProjects/app-hilt-migration/app/build/tmp/kapt3/stubs/debug/com/sample/base/DebugsampleApp.java, /Users/allan/AndroidStudioProjects/app-hilt-migration/app/build/tmp/kapt3/stubs/debug/com/sample/base/sampleApp.java
warning: The following options were not recognized by any processor: '[room.schemaLocation, kapt.kotlin.generated, room.incremental]'[INFO] Analyzing sources structure took 0[ms].
[INFO] Annotation processing complete, errors: 0, warnings: 0
[INFO] Annotation processor stats:
[INFO] dagger.hilt.processor.internal.root.RootProcessor: total: 204 ms, init: 12 ms, 6 round(s): 61 ms, 0 ms, 130 ms, 1 ms, 0 ms, 0 ms
[INFO] dagger.hilt.android.processor.internal.testroot.TestRootProcessor: total: 0 ms, init: 0 ms, 0 round(s): 
[INFO] dagger.hilt.android.processor.internal.uninstallmodules.UninstallModulesProcessor: total: 0 ms, init: 0 ms, 0 round(s): 
[INFO] dagger.hilt.processor.internal.definecomponent.DefineComponentProcessor: total: 0 ms, init: 0 ms, 0 round(s): 
[INFO] dagger.hilt.android.processor.internal.bindvalue.BindValueProcessor: total: 1 ms, init: 1 ms, 0 round(s): 
[INFO] dagger.hilt.android.processor.internal.customtestapplication.CustomTestApplicationProcessor: total: 0 ms, init: 0 ms, 0 round(s): 
[INFO] dagger.hilt.android.processor.internal.androidentrypoint.AndroidEntryPointProcessor: total: 313 ms, init: 3 ms, 6 round(s): 310 ms, 0 ms, 0 ms, 0 ms, 0 ms, 0 ms
[INFO] dagger.hilt.processor.internal.aggregateddeps.AggregatedDepsProcessor: total: 30 ms, init: 1 ms, 5 round(s): 22 ms, 0 ms, 7 ms, 0 ms, 0 ms
[INFO] dagger.hilt.processor.internal.originatingelement.OriginatingElementProcessor: total: 0 ms, init: 0 ms, 5 round(s): 0 ms, 0 ms, 0 ms, 0 ms, 0 ms
[INFO] dagger.hilt.processor.internal.aliasof.AliasOfProcessor: total: 0 ms, init: 0 ms, 0 round(s): 
[INFO] dagger.hilt.processor.internal.generatesrootinput.GeneratesRootInputProcessor: total: 0 ms, init: 0 ms, 0 round(s): 
[INFO] dagger.internal.codegen.ComponentProcessor: total: 1391 ms, init: 238 ms, 6 round(s): 203 ms, 2 ms, 2 ms, 942 ms, 2 ms, 2 ms
[INFO] androidx.hilt.AndroidXHiltProcessor: total: 5 ms, init: 5 ms, 0 round(s): 
[INFO] androidx.room.RoomProcessor: total: 20 ms, init: 20 ms, 0 round(s): 
File Object History : []
Open Type Names     : []
Gen. Src Names      : []
Gen. Cls Names      : []
Agg. Gen. Src Names : []
Agg. Gen. Cls Names : []
[INFO] Annotation processing took 2166 ms
```
I may have complete misunderstanding on how Hilt kapt works. 
I'm hoping to get some clarity since I'm stuck in figuring out why the kapt is taking so much time and how I can increase the build performance. It's currently impeding our decision to migrate to Hilt or just use other non-kapt DI solutions such as Koin.

Please let me know if you need more information.

**Comment by danysantiago** [comment] 2021-05-04 14:56
The fix for this was confirmed internally due to https://github.com/google/dagger/commit/d69b00f152a6e7e3252d65b51ae635b8656e534f. When using the Android Gradle Plugin version 4.2+ Hilt will use the a newer more efficient transform pipeline that improves build performance and reduces the increased dexing times.

**Closed by danysantiago** 2021-05-04 14:56 UTC
Labels: area: build, area: hilt, needs investigation

**Comment by danysantiago** [comment] 2021-05-04 15:00
Note that further work is being done to optimize the processors and other areas that might affect the build. For tests, we added a [feature to share test component, enabled via a flag](https://dagger.dev/hilt/compiler-options#sharing-test-components) that reduces the amount of generated code in tests. Additionally, work is being done to remove one of Hilt's processor from being `AGGREGATING` and turning it into `ISOLATING` which will further improve incremental compilations.
