### ISSUE TITLE
"@BindValue fields cannot be private" error in androidTest

### ISSUE THREAD

**Issue by ziglee** [google/dagger#2045] opened 2020-08-13 16:33 UTC
When using **@BindValue** inside an androidTest: 

```
@HiltAndroidTest
@UninstallModules(KittensModule::class)
@RunWith(AndroidJUnit4::class)
class FavoritesFragmentTest {

    @get:Rule
    var hiltRule = HiltAndroidRule(this)

    @BindValue
    val repository: KittensRepository = mockk()
}
```

It generated this java class:

```
...
public final class FavoritesFragmentTest {
...
    @org.jetbrains.annotations.NotNull()
    @dagger.hilt.android.testing.BindValue()
    private final net.cassiolandim.kittychallenge.repository.KittensRepository repository = null;
...
}
```

and the following error **@BindValue fields cannot be private. Found: repository**

I'm using the following dependencies:
```
    implementation "com.google.dagger:hilt-android:2.28-alpha"
    kapt "com.google.dagger:hilt-android-compiler:2.28-alpha"
    implementation 'androidx.hilt:hilt-lifecycle-viewmodel:1.0.0-alpha02'
    kapt 'androidx.hilt:hilt-compiler:1.0.0-alpha02'
    androidTestImplementation  "com.google.dagger:hilt-android-testing:2.28-alpha"
    kaptAndroidTest "com.google.dagger:hilt-android-compiler:2.28-alpha"
    testImplementation "com.google.dagger:hilt-android-testing:2.28-alpha"
    kaptTest "com.google.dagger:hilt-android-compiler:2.28-alpha"
```

**Comment by bcorso** [comment] 2020-08-13 16:38
Closing as duplicate of #2038

**Closed by bcorso** 2020-08-13 16:38 UTC

**Comment by ziglee** [comment] 2020-08-13 16:45
Sorry 'bout that. Didn't check the closed issues first. My bad.
