### ISSUE TITLE
Can we remove @Inject for model classes with only one constructor without arguments?

### ISSUE THREAD

**Issue by macarthor** [google/dagger#1409] opened 2019-01-31 08:19 UTC
provided one model class has only one constructor, and the constructor has no argument.

could dagger support removing @Inject annotation for its constructor? because it’s clear how this class provides its instance.

@Inject annotation would produce the “Xxx_Factory” class, and the class is not used when the model class has only one constructor without arguments. Instead, the component class would directly use “new Xxx()”. So there’s no need to add the @Inject annotation, and would not produce the “Xxx_Factory” class.

**Comment by tbroyer** [comment] 2019-01-31 09:48
Duplicate of #1105?

**Comment by ronshapiro** [comment] 2019-01-31 14:04
Yup. See that issue.

**Closed by ronshapiro** 2019-01-31 14:04 UTC

**Comment by macarthor** [comment] 2019-02-01 05:42
thanks i got the answer. i’d have searched the issues.
