### ISSUE TITLE
[Feature Request] optional provide activity when using ContributesAndroidInjector

### ISSUE THREAD

**Issue by andretietz** [google/dagger#961] opened 2017-11-22 15:16 UTC
When using the ContributesAndroidInjector Annotation there's no way to provide the activity itself. In the rare cases I need this it's a pain to always use the "old" approach.

``` java
    @Binds
    @IntoMap
    @ActivityKey(MainActivity::class)
    internal abstract fun bindAndroidInjectorFactory(builder: MainActivitySubcomponent.Builder)
            : AndroidInjector.Factory<out Activity>

    @ActivityScope
    @Subcomponent(modules = arrayOf(ActivityModule::class))
    interface MainActivitySubcomponent : AndroidInjector<MainActivity> {
        @Subcomponent.Builder
        abstract class Builder : AndroidInjector.Builder<MainActivity>() {
            abstract fun module(module: ActivityModule): Builder

            override fun seedInstance(instance: MainActivity) {
                module(ActivityModule(instance))
            }
        }
    }
```

with the module:

``` java
@Module
class ActivityModule(private val activity: AppCompatActivity) {
    @Provides
    @ActivityScope
    fun provideActivity(): AppCompatActivity = activity
}
```

This is a lot of boilerplater why I love the annotation you introduced in 2.11

I would love to see an additional boolean(?) flag in this annotation(may be no IN this annotation but a different one?) which is default false, so that the activity is provided (the code for the subcomponent is generated automatically)

This could be figured out by reading the type of key (@ActivityKey) in the subcomponent

**Comment by tbroyer** [comment] 2017-11-22 15:41
Given that [`AndroidInjector.Builder#seedInstance`](https://google.github.io/dagger/api/2.13/dagger/android/AndroidInjector.Builder.html#seedInstance-T-) is annotated with `@BindsInstance`, shouldn't it already work? (it should already be equivalent to what you wrote, except for the `@ActivityScope` but is that really needed?)

**Comment by JakeWharton** [comment] 2017-11-22 15:47
It already works, yes, with the concrete type. And you can alias to the
general supertype with a @Binds.

**Comment by andretietz** [comment] 2017-11-23 09:11
Thanks

``` java
@Module
abstract class ApplicationModule {

    @ContributesAndroidInjector
    abstract fun provideActivity(): MainActivity

    @Binds
    abstract fun provideActivity(mainActivity: MainActivity): AppCompatActivity
}
```

**Comment by andretietz** [comment] 2017-12-07 12:22
One additional question:

What if I have 2 activities (lets say MainActivity and WhateverActivity) which both need to provide an AppCompatActivity?

I tried this and I am (of course) running into the issue that AppCompatActivity is mutliple times bound.

Any ideas on how to solve this?

**Comment by ronshapiro** [comment] 2017-12-19 02:18
The bindings for `MainActivity` and `WhateverActivity` should be in different components so it shouldn't be an issue, right?

**Comment by kingsleyadio** [comment] 2018-03-10 15:28
@ronshapiro Indeed, that could work if the subcomponents were being written manually

However, it is rather impossible with the `@ContributesAndroidInjector` annotation, which makes this quite tricky

**Comment by liminal** [comment] 2018-03-12 10:05
@kingsleyadio not very hard with @ContributesAndroidInjector. Simplest way is to add a component-local module like so:

```kotlin
@Module
abstract class ApplicationModule {

    @ContributesAndroidInjector(modules = [MainActivityModule::class])
    abstract fun provideActivity(): MainActivity
}

@Module
abstract class MainActivityModule {
    @Binds
    abstract fun provideActivity(mainActivity: MainActivity): AppCompatActivity
}

Then you have AppCompatActivity bound in the scope of the MainActivity subcomponent IIRC

```

**Comment by kingsleyadio** [comment] 2018-03-12 10:34
@liminal I agree this will work, and I wouldn't mind if I have to do this once so that it applies to all the activities provided by the module (the ApplicationModule using your example).

However, the issue is having to implement this extra module (which basically does the same thing) for every new activity/fragment that is subscribed to the graph via `@ContributesAndroidInjector`

**Comment by Bodo1981** [comment] 2018-03-26 19:18
How about an annotation param in @ContributesAndroidInjector.

```kotlin
@Module
abstract class ApplicationModule {

    @ContributesAndroidInjector(additionalsBinds = [Activity::class, Interface::class, ...])
    abstract fun provideActivity(): MainActivity
}
```

```kotlin
class MainActivity : AppCompatActivity, Interface {
}
```

With this "additionalBinds" parameter in @ContributesAndroidInjector we can specify the addtional binds functions getting created.

The benefit of this "additionalBinds" parameter is, that we are not limited to the supertypes of specified classes.

**Comment by kingsleyadio** [comment] 2018-03-27 09:58
Hey @Bodo1981. That's a good suggestion.
Perhaps, it could even be used as a meta-annotation, so that we can do something like:
```kotlin
@ContributesAndroidInjector(additionalBinds = [Activity::class, AppCompatActivity::class, ...])
annotation class ContributesActivity
```

So, we can simply use the `@ContributesActivity` whenever those additional bindings are required

**Comment by GeorgePetri** [comment] 2018-04-03 08:17
@Bodo1981 How would that work with Qualifiers?

**Comment by GeorgePetri** [comment] 2018-04-03 16:38
```kotlin
@Module
abstract class ApplicationModule {

    @ContributesAndroidInjector(modules = [MainActivityModule::class])
    abstract fun provideActivity(): MainActivity

    @Binds
    @FromApplication
    abstract fun provideApplication Context(app: App): Context
}

@Module
abstract class MainActivityModule {
    @Binds
    abstract fun provideActivity(mainActivity: MainActivity): AppCompatActivity

    @Binds
    @FromActivity
    abstract fun provideContext(mainActivity: MainActivity): Context
}
```

```@FromActivity``` and ```@FromApplication``` are qualifiers

**Comment by ronshapiro** [comment] 2018-04-04 13:57
Maybe we could have a way to define an abstract generic module and use a type parameter for the concrete activity type. Then you can specify the module and Dagger will implement it for you:

Something like this:
```java
@Module
@ContributesAndroidInjector.GenericModule // with a better name
interface ActivityModule<T extends Activity> {
  @Binds AppCompatActivity bind(T activity);
  @Binds @MySpecialQualifier Context context(T t);
}
```

You implement it once, include it in all of your @ContributesAndroidInjector declarations, and Dagger handles the rest. cc: @netdpb

**Comment by NikolayKul** [comment] 2018-05-19 09:50
Will it ever be implemented? This feature'd save us from writing a boilerplate and would make the code much cleaner

**Comment by Dizarray** [comment] 2018-06-21 07:12
@andretietz, actually builder of component or subcomponent created with `@ContributesAndroidInjector` provides an Activity (or whatever class you wrote). I suggest you make your `@Provides` methods in `ActivityModule` static, or in case of Kotlin, make your `@Module` class an object and annotate `@Provides` functions with `@JvmStatic` like this:
```Kotlin
@Module
object ActivityModule {
    @Provides
    @ActivityScope
    @JvmStatic
    fun provideObjectDependentFromActivity(someActivity: SomeActivity) = SomeObject(someActivity)
}
```
I had the same issue and making `@Provides` functions static solved it. Maybe it will solve your issue too.

**Comment by Elvis10ten** [comment] 2018-11-08 13:02
Any news about this

**Comment by Chang-Eric** [comment] 2020-07-14 23:28
Closing this as with Dagger Hilt's release there's unlikely to be significant new features added to Dagger Android.

**Closed by Chang-Eric** 2020-07-14 23:28 UTC
