### ISSUE TITLE
Hilt injection ViewModel cannot pass parameters

### ISSUE THREAD

**Issue by hi-dhl** [google/dagger#1965] opened 2020-07-02 10:40 UTC
My project has 1 Activity、 1 Fragment 、1 ViewModel

**HiltViewModel**

```
class HiltViewModel @ViewModelInject constructor(
) : ViewModel() {
       val mName:  MutableLiveData<String> =  MutableLiveData()
}
```

**HitAppCompatActivity**

```
@AndroidEntryPoint
class HitAppCompatActivity : AppCompatActivity() {
    private val mHitViewModule: HiltViewModel by viewModels()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_hilt)
        mHitViewModule.mName.postValue("google")

    }

}
```

**HiltFragment**

```
@AndroidEntryPoint
class HiltFragment : Fragment() {
    private val mHitViewModule: HiltViewModel by viewModels()

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        Log.e("HiltFragment", "HiltFragment 1111 ")
        mHitViewModule.mName.observe(activity, Observer {
            Log.e("HiltFragment", "HiltFragment 222  name = " + it)
        })
    }
}
```

I cannot get parameters (name) int the HiltFragment?

**Comment by raviteja786143** [comment] 2020-07-02 11:29
if you want to use Activity viewmodel instance inside fragment u should use by activityViewModels(). In fragment by viewModels() will be create vm per fragment instance. Also postValue is not required if you are setting value on UI thread, it will add unnecessary synchronised lock to it.

**Comment by hi-dhl** [comment] 2020-07-02 12:15
@raviteja786143 Thank u ,  I use activityViewModels()  can  pass parameters

**Comment by goldy1992** [comment] 2020-07-04 15:22
I still think this is an issue, 
- what happens if the logic is fragment specific, why should it use the activity view model?
- The **[code lab](https://codelabs.developers.google.com/codelabs/android-dagger-to-hilt/#6)** for migrating to hilt **does not include** this use case, it only passes arguments in activity view models

**Comment by ravik1swiggy** [comment] 2020-07-05 06:22
@goldy1992 I think @hi-dhl wants to observe(or Share) Activity viewModel changes in Fragment for that purpose activityViewModels can be used nothing to do with hilt.  Fragment can also have its own viewModel using by viewModel() along with above shared activityModel. If you want to pass arguments to this fragment scoped viewModel let's say repository/Manager, can be created via module with @FragmentScope (hilt annotation). Similarly Fragment arguments can be consumed via SavedStateHandle using  @Assisted(hilt annotation). 

https://developer.android.com/training/dependency-injection/hilt-android#component-scopes
https://developer.android.com/training/dependency-injection/hilt-jetpack

**Comment by goldy1992** [comment] 2020-07-05 11:36
`If you want to pass arguments to this fragment scoped viewModel let's say repository/Manager, can be created via module with FragmentComponent (hilt annotation). Similarly Fragment arguments can be consumed via SavedStateHandle using @Assisted(hilt annotation).`

@raviteja786143 regarding the quoted comment. I tried this approach without much luck. However I did not delve to far into the cause of the error as I found a workaround by avoiding passing parameters to the Fragment's ViewModel.

I do however believe that there still exists an issue passing parameters to a Fragment ViewModel but I am unable to provide any more details since I was happy with my workaround.

**Comment by danysantiago** [comment] 2020-07-08 00:03
I'll close this since there is nothing actionable from our side, if you ever go back to the issue you encountered when passing parameters to a Fragment ViewModel and can provide us with more details then maybe we can take a look. Thanks

**Closed by danysantiago** 2020-07-08 00:03 UTC
