### ISSUE TITLE
Kapt errors are not visible when build failed with Gradle Cache turned on

### ISSUE THREAD

**Issue by remcomokveld** [google/dagger#2201] opened 2020-11-30 18:11 UTC
This issue is semi-related to #1991 

Not sure if this is a Dagger specific issue, or more of a kapt issue, but posting here to determine if it is Dagger or Kapt.

I managed to reproduce this issue by having a library project that has a `compileOnly` dependency and an app project that does not depend on the same dependency. This results in the Dagger compiler to fail to generate the component graph.

When this is the case, the first compilation attempt will report the error correctly
```
$ ./gradlew clean assembleDebug

> Task :app:kaptDebugKotlin
error: cannot access CastContext
  class file for com.google.android.gms.cast.framework.CastContext not found
  Consult the following stack trace for details.
  com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.google.android.gms.cast.framework.CastContext not found
> Task :app:compileDebugJavaWithJavac FAILED
/Users/rmokveld/Workspace/DaggerSample/app/build/generated/source/kapt/debug/nl/remcomokveld/daggersample/Hilt_SampleApplication.java:20: error: cannot find symbol
      return DaggerSampleApplication_HiltComponents_SingletonC.builder()
             ^
  symbol: variable DaggerSampleApplication_HiltComponents_SingletonC
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
55 actionable tasks: 10 executed, 44 from cache, 1 up-to-date
```

Now because the kapt task succeeded, it will be stored in cache, and a second clean compilation attempt will pull the result from cache instead of executing. This results in the the original error not being reported, which makes it very hard to determine what went wrong
```
$ ./gradlew clean assembleDebug

> Task :app:compileDebugJavaWithJavac FAILED
/Users/rmokveld/Workspace/DaggerSample/app/build/generated/source/kapt/debug/nl/remcomokveld/daggersample/Hilt_SampleApplication.java:20: error: cannot find symbol
      return DaggerSampleApplication_HiltComponents_SingletonC.builder()
             ^
  symbol: variable DaggerSampleApplication_HiltComponents_SingletonC
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 908ms
52 actionable tasks: 6 executed, 43 from cache, 3 up-to-date
```

If you run the the build again with `--no-build-cache` flag you will see the proper error again.
[DaggerErrorCachingSample.zip](https://github.com/google/dagger/files/5617846/DaggerErrorCachingSample.zip)

**Comment by bcorso** [comment] 2020-11-30 18:55
Hi @remcomokveld,

Thanks for reporting the issue and giving a workaround!

As for whether this is a Dagger or kapt issue, it sounds more of a kapt issue. In particular, if the `:app:kaptDebugKotlin` task reports an error, I would have thought that would mean that the task did not succeed and thus would not be cached, right?

**Comment by remcomokveld** [comment] 2020-11-30 20:56
The weird thing is that if I add an additional module with a super simple annotation processor, it does cause the kapt task to fail and not just print the message. I'm thinking that this may have to do with the moment at Hilt the 
[DaggerErrorCachingSampleWithCustomProcessor.zip](https://github.com/google/dagger/files/5618337/DaggerErrorCachingSampleWithCustomProcessor.zip)

Also if I remove all hilt related code, and just define a simple component that injects the activity's dependencies, it does result in the kapt task failing. This does make me think that the issue is somewhere in Hilt's compiler.

**Comment by bcorso** [comment] 2020-12-04 18:55
Yeah, that is weird. I'm not sure why it isn't reproducing locally in `MyProcessor`. The one difference is that the original error is throwing a `Symbol$CompletionFailure` exception whereas `MyProcessor` is printing an error to the `Messager`. However, even once I modified `MyProcessor` to replicate the `Symbol$CompletionFailure` it still doesn't have the caching issue.

Unfortunately, I'm still not sure what we can do here. This really looks like like a kapt/gradle bug since if `:app:kaptDebugKotlin` is reporting an error, then it really shouldn't be marking that the task succeeded and caching it.

**Comment by bcorso** [comment] 2020-12-23 19:54
I'm going to close this issue out for now since I think the fix should be on the kapt/gradle side. Please feel free to file a bug against kapt/gradle and link it here.

**Closed by bcorso** 2020-12-23 19:54 UTC
