### ISSUE TITLE
Generated component error. Rawtype provider vs generic MembersInjector

### ISSUE THREAD

**Issue by kotucz** [google/dagger#939] opened 2017-11-07 11:39 UTC
Generated Dagger component `DaggerComp.java` cannot be compiled, because of this error:
```
...\di\DaggerComp.java
Error:(41, 26) error: method injectP in class AFrag_MembersInjector<P#2> cannot be applied to given types;
required: Object,P#1
found: Frag,Object
reason: inferred type does not conform to upper bound(s)
inferred: Object
upper bound(s): APres
where P#1,P#2 are type-variables:
P#1 extends APres declared in method <P#1>injectP(Object,P#1)
P#2 extends APres declared in class AFrag_MembersInjector
```

Happens using dagger `2.12`. Did not occur in previous versions of dagger (`2.11` and earlier)
Using AndroidStudio 3.0, Android plugin 3.0.0, Java 8

This issue can be reproduced with following example code:

**di/Comp.java**
```java
package di;

@Singleton
@Component
interface Comp {
    void inject(Frag f);
}
```

**Frag.java**
```java
public class Frag extends AFrag<Pres> {
    @Inject
    Frag() {
    }
}

abstract class AFrag<P extends APres> {
    @Inject
    P p;
}

@Singleton
class Pres extends APres {
    @Inject
    Pres() {
    }
}

abstract class APres {
}
```

`Comp` and `Pres` must be in different package and `Pres` is not public

Here is the generated `DaggerComp.java`:
```java
public final class DaggerComp implements Comp {
  @SuppressWarnings("rawtypes")
  private Provider presProvider;

  private DaggerComp(Builder builder) {
    initialize(builder);
  }

  public static Builder builder() {
    return new Builder();
  }

  public static Comp create() {
    return new Builder().build();
  }

  @SuppressWarnings("unchecked")
  private void initialize(final Builder builder) {
    this.presProvider = DoubleCheck.provider(Pres_Factory.create());
  }

  @Override
  public void inject(Frag f) {
    injectFrag(f);
  }

  private Frag injectFrag(Frag instance) {
    AFrag_MembersInjector.injectP(instance, presProvider.get()); // <<< ERROR
    return instance;
  }

  public static final class Builder {
    private Builder() {}

    public Comp build() {
      return new DaggerComp(this);
    }
  }
}
```

**Comment by kotucz** [comment] 2017-11-10 13:14
Issue persists in Dagger 2.13

**Comment by ultraon** [comment] 2017-11-17 14:18
I have the same issue but with Dagger2 version 2.13, with 2.12 - everything alright

**Comment by ronshapiro** [comment] 2017-12-19 02:47
Is this the same as #949?

**Comment by kotucz** [comment] 2017-12-29 18:07
I do not think that this is caused by compiler. The generated code has mismatch between the required parameter of `injectP` method and provided argument.

**Comment by MartinMMS** [comment] 2018-02-22 16:36
The problem is that since Dagger 2.12 you cannot do a member injection of a package private type which resides in another package than the main package of the application.
The reason is that the injection code is generated in the DaggerComp which is placed in the main package of the application and therefor has no access to the package private type in another package one want's to inject. This causes the Provider within DaggerComp to be generated as rawtype and the provider.get() method will only return the type Object. The static AFrag_MembersInjector.injectP()-Method cannot handle type Object, because it expects the specific type of P.

So... the simplest solution would be, when Dagger2 would generate a different (or a second) MemberInjector static inject method. So that it does not expect the specific type of P but instead a Provider<P>.

The Function call in DaggerComponent needs to change from
AFrag_MembersInjector.injectP(instance, presProvider.get());
to
AFrag_MembersInjector.injectP(instance, presProvider);
and the MemberInjector should call provider.get() internally.

This would trick the compiler because the raw provider would become a typed provider when given to the static inject method before provider.get() is called. The trick is the same as it already was in Dagger 2.11.

It would be nice if you could change this in an upcoming Dagger2 release but in the meanwhile the only workaround is to not try to inject package private types into other classes via member injection or setter-method injection.

**Comment by ronshapiro** [comment] 2019-06-05 20:46
Are you able to create a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) that exhibits this behavior?

Is this still an issue in 2.23.1?

**Comment by bcorso** [comment] 2020-07-28 21:21
Closing this, since there hasn't been a response in over a year. 

Please open back up if you can provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/minimal-reproducible-example) of the issue.

**Closed by bcorso** 2020-07-28 21:21 UTC
