### ISSUE TITLE
Stackoverflow on circular dependency

### ISSUE THREAD

**Issue by PaulWoitaschek** [google/dagger#366] opened 2016-04-30 12:32 UTC
Versions tested: `2.2`, `2.4`

I just figured out a weird issue where Dagger lead to an StackOverflowException.

I was using a global `AppComponent` which had a method for a sub component.

```java
@Singleton @Component(modules = {BaseModule.class, AndroidModule.class, NetworkModule.class, BusModule.class})
public interface AppComponent {

   ActivityComponent newActivityComponent(ShoppingModule shoppingModule);
}
```

This subcomponent was itself extending from the AppComponent:

```java
@ActivityScope @Subcomponent(modules = {ShoppingModule.class})
public interface ActivityComponent extends AppComponent {}
```

This was leading to a circular dependency and therefore hundrets of `dagger.internal.codegen.ComponentDescriptor$Factory.create(ComponentDescriptor.java:451)`.
To fix it don't let `ActivityComponent` extend `AppComponent`.

It would be great if Dagger could catch this kind of setup and warn about this circular dependency rather than just running in a circle.

**Comment by ronshapiro** [comment] 2016-08-16 15:16
Dupe of #326.

**Closed by ronshapiro** 2016-08-16 15:16 UTC
