### ISSUE TITLE
AS 3.0 gradle:3.0.0 build error

### ISSUE THREAD

**Issue by liyongyan** [google/dagger#924] opened 2017-10-30 04:34 UTC
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.NoClassDefFoundError: dagger/Provides

**Comment by JakeWharton** [comment] 2017-10-30 04:36
Dupe of #923 and not enough information to diagnose a problem anyway.

**Closed** 2017-10-30 11:42 UTC

**Comment by bayshier** [comment] 2017-10-31 07:39
Error:Execution failed for task ':order:compileDebugJavaWithJavac'.
> java.lang.NoClassDefFoundError: dagger/Subcomponent

**Comment by bayshier** [comment] 2017-10-31 07:43
Error:Execution failed for task ':login:compileDebugJavaWithJavac'.
> java.lang.NoClassDefFoundError: dagger/Provides
