### ISSUE TITLE
java.lang.IllegalStateException: Given component holder class com.avast.android.privacy.MainActivity does not implement interface dagger.hilt.internal.GeneratedComponent or interface dagger.hilt.internal.GeneratedComponentManager

### ISSUE THREAD

**Issue by MartinRajniak** [google/dagger#2764] opened 2021-07-20 12:29 UTC
When I upgrade to version 2.38 (2.37 previously) I get this error:

> java.lang.IllegalStateException: Given component holder class <MainActivity with AndroidEntryPoint> does not implement interface dagger.hilt.internal.GeneratedComponent or interface dagger.hilt.internal.GeneratedComponentManager
>       at dagger.hilt.EntryPoints.get(EntryPoints.java:62)
>       at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.createInternal(HiltViewModelFactory.java:129)
>       at androidx.hilt.navigation.HiltViewModelFactory.create(HiltNavBackStackEntry.kt:56)
>       at androidx.hilt.navigation.compose.HiltViewModelKt.createHiltViewModelFactory(HiltViewModel.kt:107)

AGP version: 7.1.0-alpha03

**Comment by Chang-Eric** [comment] 2021-07-20 23:11
Just to confirm, that activity you are passing in is annotated with `@AndroidEntryPoint`? And I assume you are using the Gradle plugin or extending the generated Hilt activity class?

**Comment by wiryadev** [comment] 2021-07-22 02:16
i got this error too and i did annotate my activity with that. Rolled back to 2.37 solve this. Btw, i use Compose so i assume it is because `hilt-navigation-compose` is not updated to be compatible with 2.38.

**Comment by MartinRajniak** [comment] 2021-07-22 12:49
Hi,
yes, activity is annotated like this
`@AndroidEntryPoint 
 class MainActivity : AppCompatActivity() {`
 
 Also I am using Android Hilt Gradle Plugin.
 
 But I think @wiryadev is right - we are also using hilt navigation compose.

**Comment by simonlebras** [comment] 2021-07-22 13:48
I'm also having this issue. Although I'm also using compose, I don't think this is related (might be wrong). I've a crash at startup  (when using a custom entrypoint with jetpack startup and an application context to get some dependencies manually) caused by an IllegalStateException saying that my Application class does not implement GeneratedComponent .
Rolling back to dagger 2.37 solved the issue for me as well

**Comment by Chang-Eric** [comment] 2021-07-26 21:42
Thanks for the report, I believe this is happening due to #2784. Closing this as a duplicate assuming that is the case.

**Closed by Chang-Eric** 2021-07-26 21:42 UTC

**Comment by Badman47** [comment] 2023-09-12 02:11
did anyone has an answer for this problem, Please

**Comment by NguyenKhue** [comment] 2024-03-27 16:14
I  got this error because i'm forgot implement: ksp(libs.hilt.compiler).
