### ISSUE TITLE
Injection not working from within super class.

### ISSUE THREAD

**Issue by Dorvaryn** [google/dagger#102] opened 2015-01-13 14:13 UTC
In the android-simple example a parent class (https://github.com/google/dagger/blob/master/examples/android-simple/src/main/java/com/example/dagger/simple/DemoActivity.java) is doing the injection and the children class (https://github.com/google/dagger/blob/master/examples/android-simple/src/main/java/com/example/dagger/simple/ui/HomeActivity.java) is expected to de injected after the call to super.

It does not seem to work as the inject method from the component called is the one from the parent class skipping any member injection for the child class.

**Comment by mgrzechocinski** [comment] 2015-01-13 15:39
Yep, always faced it, but somehow blindly accepted it. 

Worth mentioning, that in `Child->Parent` direction it works. In your component you only need `inject(ChildActivity)`. Then, you can call `inject` from child activity only and parent activity's fields would also be injected. 

Samples: [ChildActivity](https://github.com/mgrzechocinski/dagger2-example/blob/master/app/src/main/java/net/grzechocinski/android/dagger2example/home/HomeActivity.java) and [ParentActivity](https://github.com/mgrzechocinski/dagger2-example/blob/master/app/src/main/java/net/grzechocinski/android/dagger2example/home/BaseActivity.java) and [Component](https://github.com/mgrzechocinski/dagger2-example/blob/master/app/src/main/java/net/grzechocinski/android/dagger2example/internal/di/D2EComponent.java)

**Comment by Dorvaryn** [comment] 2015-01-13 16:09
@mgrzechocinski Yeah it works fine on the Child -> Parent direction.
Unfortunately I find the Parent -> Child situation a lot more common (ie Parent Activity define Injection and Children can use the @Inject if needed.)

I'm now using the Parent Activity as a hub and provide accessors to the injected fields. It seems to be the less boilerplate I can find for that situation.

In the short term if this cannot be resolved the example should be changed as it is not working.

**Comment by artem-zinnatullin** [comment] 2015-01-13 17:06
This is an old thing from Dagger 1...

My dirty solution: use some static `DIContainer` inner class in super class which holds injected things required for children.

But it will be great if issue will be resolved

**Comment by tbroyer** [comment] 2015-01-13 17:12
This is a dupe of #73

**Comment by chrisjenx** [comment] 2015-01-27 11:11
@Dorvaryn I expose an `protected abstract Inject()` method on the parent which the child has to implement, this is to encourage the correct implementation in your children. 

I guess there could be a warning here?

**Comment by konmik** [comment] 2015-02-01 16:19
Here is my solution for injection through a base class:

https://github.com/konmik/Dagger2Example/blob/master/app/src/main/java/info/android15/dagger2example/Dagger2Helper.java

**Comment by cgruber** [comment] 2015-03-26 18:37
We'll take a look at the examples - it's entirely possible that it's not a valid example anymore, as it was raw-ported without a lot of thought.

**Comment by konmik** [comment] 2015-03-26 18:48
You're right, this solution is quick and dirty just to show how this could be done. It does not this informative exceptions and does not have tests. Naming and architecture could be better.

**Comment by gk5885** [comment] 2015-03-31 23:18
IIUC, @tbroyer was correct and that this is a dup.  So, I think we can just call this closed.

**Closed by gk5885** 2015-03-31 23:18 UTC
Labels: area: examples, status: researching, type: bug

**Comment by svenjacobs** [comment] 2015-04-01 05:50
@gk5885 Now both #73 and #102 are closed. Where do we further discuss this issue?
