### ISSUE TITLE
Dagger and Compose

### ISSUE THREAD

**Issue by ber4444** [google/dagger#3188] opened 2022-01-26 00:38 UTC
I'm using the sample code seen here: https://github.com/Morfly/compose-arch-sample/blob/master/app/src/main/java/com/morfly/sample/archcompose/MainActivity.kt#L29 with composition locals (https://developer.android.com/jetpack/compose/compositionlocal)

Now with the latest compose, 1.2.0-alpha01, it stopped working here: https://github.com/Morfly/compose-arch-sample/blob/7509a204119eeb6fff3fa692d6a172dd5549c7f5/images/impl/src/main/kotlin/com/morfly/sample/images/impl/ImagesEntryImpl.kt#L28

It gives the error, `@Composable invocations can only happen from the context of a @Composable function`
because the generated code is not composable
```
    public Builder dataProvider(DataProvider dataProvider) {
      this.dataProvider = Preconditions.checkNotNull(dataProvider);
      return this;
    }
```

**Comment by danysantiago** [comment] 2022-01-26 15:15
That error is meant to show **when a composable function is invoked from a non-composable function**, but Dagger does not ever generate composable functions so they should all be callable from within a composable function.

However, the issue is the lambda parameter of [`injectedViewModel`](https://github.com/Morfly/compose-arch-sample/blob/f0c41ce50e6ce84b3d4f0492c7c4408c0ee9105f/common/src/main/kotlin/com/morfly/sample/common/di/InjectedViewModel.kt#L28) is not marked as a composable function which is why you can't retrieve your local from it in the provided lambda of your `ImagesEntryImpl`. You should update its signature like this:

```
@Composable
inline fun <reified VM : ViewModel> injectedViewModel(
    key: String? = null,
    crossinline viewModelInstanceCreator: @Composable () -> VM // Added annotation here
): VM = ...
```

**Closed by danysantiago** 2022-01-26 15:15 UTC
