### ISSUE TITLE
transformClassesWithAndroidEntryPointTransformForDebug when using an extension method on Uri

### ISSUE THREAD

**Issue by npike** [google/dagger#2153] opened 2020-10-19 20:31 UTC
- hilt-android 2.29.1-alpha
- hilt-android-compiler 2.29.1-alpha
- hilt-android-gradle-plugin 2.29.1-alpha

When annotating a BroadcastReceiver that uses in specific extension method in its onReceive implementation I am getting the following compilation error:

> Execution failed for task ':app:transformClassesWithAndroidEntryPointTransformForDebug'.
> javassist.bytecode.BadBytecode: onReceive (Landroid/content/Context;Landroid/content/Intent;)V in net.npike.hilt.transformClassesWithAndroidEntryPointTransformForDebug.ExampleBroadcastReceiver: failed to resolve types

Additionally, Android Studio 4.1 shows:
> Cause: android.net.Uri

In this situation I am using an extension function on `Uri` that returns a nullable string.  The implementation of this extension function doesn't seem to matter. This only seems to happen if I use the extension function inline with a `let`.  

```
/**
 * Compilation error
 */
@AndroidEntryPoint
class NotWorkingExampleBroadcastReceiver : BroadcastReceiver() {
    override fun onReceive(context: Context, intent: Intent) {
        intent.data?.parsePackage()?.let { packageName ->
            Log.d("test", packageName)
        }
    }
}
```

If I pull the value of the extension function out as a variable and apply the let directly to it everything seems fine...

```
/**
 * Compiles fine
 */
@AndroidEntryPoint
class WorkingExampleBroadcastReceiver : BroadcastReceiver() {
    override fun onReceive(context: Context, intent: Intent) {
        val packageName = intent.data?.parsePackage()

        packageName?.let {
            Log.d("test", packageName)
        }
    }
}
```

If I remove the `@AndroidEntryPoint` it also compiles fine:

```
/**
 * Compiles fine.
 */
class AlsoWorkingExampleBroadcastReceiver : BroadcastReceiver() {
    override fun onReceive(context: Context, intent: Intent) {
        intent.data?.parsePackage()?.let { packageName ->
            Log.d("test", packageName)
        }
    }
}
```

I am created an example project that demonstrates this issue: https://github.com/npike/android-hilt-transformClassesWithAndroidEntryPointTransformForDebug

**Comment by danysantiago** [comment] 2020-10-19 21:16
Thanks for the sample app. This issue is a duplicate of https://github.com/google/dagger/issues/2153, for now you'll have to keep `onReceive` simple (it delegates to another method) or use the 'long-form' of `@AndroidEntryPoint` (see https://dagger.dev/hilt/gradle-setup#why-use-the-plugin).

I'll close this issue for now as a dupe but we are working on a solution in the transform.

**Closed by danysantiago** 2020-10-19 21:16 UTC
