### ISSUE TITLE
Instant App and Dagger using AndroidInjection.inject(this)

### ISSUE THREAD

**Issue by quentin41500** [google/dagger#981] opened 2017-12-11 22:54 UTC
Hello,

I'm writing here as a last resort looking for advice on how to setup dagger with Instant App.

It seems like based on the answer, I have to make a component per feature with a dependency on app component.

Now my question is: 
**- Is it possible to use the Android feature (e.g `AndroidInjection.inject(this)`) considering the modular hierarchy required for Instant App?** 

When looking at the documentation [here](https://google.github.io/dagger/android.html#injecting-activity-objects), step 3 mention this:
```
@Module(subcomponents = YourActivitySubcomponent.class)
abstract class YourActivityModule {
  @Binds
  @IntoMap
  @ActivityKey(YourActivity.class)
  abstract AndroidInjector.Factory<? extends Activity>
      bindYourActivityInjectorFactory(YourActivitySubcomponent.Builder builder);
}

@Component(modules = {..., YourActivityModule.class})
interface YourApplicationComponent {}
```

In the case of instant apps, that would require `YourApplicationComponent` and `YourActivityModule` to be in the same module, which is not how instant apps needs to be set up.

Any recommendation?

I also made a sample app that showcase my current progress. The app is currently crashing with a `No injector found` for MainActivity which makes sense because the BindingModule is not present in the AppComponent... -> https://github.com/quentin41500/TryOut 

I posted a [stackoverflow question](https://stackoverflow.com/q/45380163/6524425) which answered partially my request.

I will be updating if I make progress  on my end as well.

Thanks,

**Comment by ronshapiro** [comment] 2018-01-05 16:54
`AndroidInjection.inject()` should work, but you may need to provide a custom implementation of `ActivityInjector` to make this work correctly. The problem is that the default implementation relies on the `Map<Class<? extends Activity>, AndroidInjector.Factory<? extends Activity>>` to be known statically when the application is created. That isn't the case for InstantApps because not all activities are downloaded yet.

I haven't had a chance to consider this yet, but I'd guess something like this would work:

```java
public class MyApplication implements HasActivityInjector {
  private InstantAppsActivityInjector activityInjector = new InstantAppsActivityInjector();

  @Override 
  public void AndroidInjector<Activity> activityInjector() {
    return activityInjector;
  }
}

final class InstantAppsActivityInjector {
  // somewhere in here, store information about the ActivityInjector.Factory instances that are in any parts of the instant-app that have been downloaded already.
}
```

**Comment by bcorso** [comment] 2020-07-10 21:48
Looks like the solution given in https://github.com/google/dagger/issues/981#issuecomment-355605774 has been verified in https://github.com/google/dagger/issues/981#issuecomment-374460454 so I'll close this.

**Closed by bcorso** 2020-07-10 21:48 UTC
