### ISSUE TITLE
DaggerFragment onAttach will not be called on devices running 5.1 and lower

### ISSUE THREAD

**Issue by davethomas11** [google/dagger#838] opened 2017-08-08 22:02 UTC
Because the function ```onAttach(Context context)``` was added in 6.0 API level 23. Using this class https://github.com/google/dagger/blob/master/java/dagger/android/DaggerFragment.java will result in on ```onAttach``` not being called on phones running 5.1 and lower.

Consider also overriding ```onAttach(Activity activity)``` as well or another solution until 5.1 is no longer in circulation.

Not critical as most users should be encouraged to use support library version.

**Comment by JakeWharton** [comment] 2017-08-08 22:04
Dupe of #777

**Closed** 2019-03-25 19:52 UTC
