### ISSUE TITLE
2.11 javadoc link is broken

### ISSUE THREAD

**Issue by yogurtearl** [google/dagger#815] opened 2017-07-18 16:09 UTC
2.11 Javadoc link on https://google.github.io/dagger/ is broken.
Should probably be something like https://google.github.io/dagger/api/2.11/

![image](https://user-images.githubusercontent.com/1195562/28327567-acd50554-6b98-11e7-9a33-997b44a07012.png)

**Comment by JakeWharton** [comment] 2017-07-18 16:14
Dupe of #806.

**Closed** 2017-09-12 19:39 UTC
