### ISSUE TITLE
NoSuchElementException thrown in KeyFactory after upgrading from 2.19

### ISSUE THREAD

**Issue by headsvk** [google/dagger#1609] opened 2019-09-12 10:48 UTC
In my project, any newer Dagger version than 2.19 makes kapt fail with NoSuchElementException thrown in an internal Dagger codegen class.
It's not simple to create a sample project for you to try so is there any way to figure out what causes this from the logs?

Gradle: 5.4.1
AGP: 3.5.0
Dagger: 2.24

> e: [kapt] An exception occurred: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at dagger.internal.codegen.KeyFactory.bindingMethodKeyType(KeyFactory.java:210)
	at dagger.internal.codegen.KeyFactory.forBindingMethod(KeyFactory.java:170)
	at dagger.internal.codegen.KeyFactory.forBindsMethod(KeyFactory.java:136)
	at dagger.internal.codegen.DelegateDeclaration$Factory.create(DelegateDeclaration.java:84)
	at dagger.internal.codegen.ModuleDescriptor$Factory.createUncached(ModuleDescriptor.java:147)
	at dagger.internal.codegen.Util.reentrantComputeIfAbsent(Util.java:93)
	at dagger.internal.codegen.ModuleDescriptor$Factory.create(ModuleDescriptor.java:128)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:783)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.graph.Traverser$GraphTraverser$DepthFirstIterator.computeNext(Traverser.java:456)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:455)
	at com.google.common.collect.ImmutableSet$Builder.addAll(ImmutableSet.java:512)
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:246)
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:228)
	at dagger.internal.codegen.ModuleDescriptor$Factory.transitiveModules(ModuleDescriptor.java:172)
	at dagger.internal.codegen.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:140)
	at dagger.internal.codegen.ComponentDescriptorFactory.subcomponentDescriptor(ComponentDescriptorFactory.java:84)
	at dagger.internal.codegen.ComponentDescriptorFactory.create(ComponentDescriptorFactory.java:146)
	at dagger.internal.codegen.ComponentDescriptorFactory.rootComponentDescriptor(ComponentDescriptorFactory.java:74)
	at dagger.internal.codegen.ComponentProcessingStep.processRootComponent(ComponentProcessingStep.java:135)
	at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:123)
	at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:51)
	at dagger.internal.codegen.TypeCheckingProcessingStep.lambda$process$0(TypeCheckingProcessingStep.java:51)
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:185)
	at dagger.internal.codegen.TypeCheckingProcessingStep.process(TypeCheckingProcessingStep.java:48)
	at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:116)
	at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:51)
	at dagger.internal.codegen.DaggerStatisticsCollectingProcessingStep.process(DaggerStatisticsCollectingProcessingStep.java:52)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:330)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:181)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:147)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:79)
	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:35)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.runAnnotationProcessing(Kapt3Extension.kt:230)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:188)
	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:99)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:96)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:106)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:81)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:555)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:82)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:107)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:546)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:177)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:164)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:54)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1558)
	at sun.reflect.GeneratedMethodAccessor133.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by MrBean355** [comment] 2019-10-02 05:57
We're getting the same issue.
Works fine with Dagger 2.16, but after updating to 2.24 we get the same stack trace.
We're using AGP 3.4.2, but the issue persists after updating to 3.5.0.
@headsvk have you managed to fix this issue?

**Comment by Drain7** [comment] 2019-10-02 06:01
Also experiencing the same issue. Tried:

Gradle: 5.4.1
AGP: 3.4.2
Dagger: 2.24

and

Gradle: 5.4.1
AGP: 3.5.0
Dagger: 2.24

@headsvk any luck fixing this issue?

**Comment by headsvk** [comment] 2019-10-02 10:09
No I haven't found a fix but we're slowly moving to Koin so it was not a priority to fix Dagger.

**Comment by MrBean355** [comment] 2019-10-10 10:53
We found the source of the problem (at least for us). We work in a multi-module environment, and were trying to compile the app module with Dagger 2.24, but the other modules were compiled with Dagger 2.16. After rebuilding everything with 2.24, this issue no longer happens.

**Comment by headsvk** [comment] 2019-10-21 09:09
@MrBean355 we had the same issue, one internal library had a dependency on Dagger 2.16 but it was not declared in its pom file. Once I discovered it and removed Dagger from there it worked fine.
What about you @Drain7 ?

**Comment by Drain7** [comment] 2019-10-21 09:21
Following @MrBean355 's advice. The issue has been resolved. :)

**Comment by bcorso** [comment] 2020-04-12 19:52
Thanks! I'll close this since it seems the issue is resolved by

https://github.com/google/dagger/issues/1609#issuecomment-540514877

**Closed by bcorso** 2020-04-12 19:52 UTC

**Comment by alessandrom** [comment] 2020-05-14 10:01
Hi, I'm experiencing this issue as well when upgrading from 2.16 to 2.27 on my project which supports androidx.
I've already verified that all the modules include the same Dagger version (screen shot attached):

<img width="446" alt="Screen Shot 2020-05-14 at 10 58 24" src="https://user-images.githubusercontent.com/1135297/81921041-ecb1cc00-95d1-11ea-9e18-2fe2cfed6e39.png">

The main project is on latests AGP (3.5.3)

Is there any other reason I could get this other than different version of dagger across the modules included?
