### ISSUE TITLE
Feature Request: Option to bind super-types of Fragment and Activity in ContributesAndroidInjector 

### ISSUE THREAD

**Issue by cckroets** [google/dagger#1088] opened 2018-03-07 05:45 UTC
When using `@ContributesAndroidInjector` there's no way to provide the base Activity or Fragment class. Only the concrete Activity or Fragment class can be injected. Currently to get around this, each concrete Android object needs its own module, which is a pain to write when you have dozens of these. My example setup looks like:

```java
@Module
public abstract class FragmentBindingModule {

    @Module
    abstract class FirstFragmentModule {
        @Binds abstract Fragment fragment(@NonNull FirstFragment firstFragment);
    }

    @PerFragment
    @ContributesAndroidInjector(modules = FirstFragmentModule.class)
    abstract FirstFragment firstFragment();

    @Module
    abstract class SecondFragmentModule {
        @Binds abstract Fragment fragment(@NonNull SecondFragment firstFragment);
    }

    @PerFragment
    @ContributesAndroidInjector(modules = SecondFragmentModule.class)
    abstract SecondFragment secondFragment();
}
```
```java
@Module
public abstract class ActivityBindingModule {

    @Module
    abstract class MainActivityModule {
        @Binds
        abstract Activity activity(@NonNull MainActivity activity);
    }

    @PerActivity
    @ContributesAndroidInjector(modules = { MainActivityModule.class, FragmentBindingModule.class })
    abstract MainActivity mainActivity();

    @Module
    abstract class OtherActivityModule {
        @Binds
        abstract Activity activity(@NonNull OtherActivity activity);
    }

    @PerActivity
    @ContributesAndroidInjector(modules = { OtherActivityModule.class, FragmentBindingModule.class })
    abstract OtherActivity otherActivity();
}
```
It would be nice to have an option e.g. ```ContributesAndroidInjector(bindSupertypes = true)``` which could automatically provide these bindings on the subcomponent builder.

**Comment by JakeWharton** [comment] 2018-03-07 05:47
Dupe of #961

**Closed** 2018-03-07 14:40 UTC
