### ISSUE TITLE
Cannot import 2.1-SNAPSHOT

### ISSUE THREAD

**Issue by vekexasia** [google/dagger#340] opened 2016-03-16 20:55 UTC
Hello there,

is there something going on with the snapshosts repo? gradle complains about it :(

https://oss.sonatype.org/content/repositories/snapshots/com/google/dagger/

Does not contain any further "dagger" folder

**Comment by JakeWharton** [comment] 2016-03-16 20:59
Dupe of #338.

**Comment by JakeWharton** [comment] 2016-03-16 21:00
TL;DR: Use 2.1 release version.

**Closed** 2016-03-16 21:02 UTC
