### ISSUE TITLE
2.10-rc1 incompatibile with retrolambda?

### ISSUE THREAD

**Issue by LuigiPapino** [google/dagger#594] opened 2017-02-23 14:20 UTC
Just playing around with the 2.10rc1 and I can't build my project:

```
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
Error:2 errors; aborting
Error:Execution failed for task ':thor:transformClassesWithDexForDebug'.
com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
```

the 2.9 works fine.

Not sure if it's related to retrolambda: https://github.com/evant/gradle-retrolambda
I'll create same brand new projects to investigate and update this issue.

In the meanwhile if someone has helpful information, please, could you share them? :)
Thank you

**Comment by JakeWharton** [comment] 2017-02-23 14:21
Dupe of #593

**Comment by LuigiPapino** [comment] 2017-02-23 14:22
Ok, I'm stupid, I just checked for dupe, and for some reason didn't see that one.
Thank you!

**Closed** 2017-02-23 14:28 UTC
