### ISSUE TITLE
IllegalArgumentException: No injector factory bound

### ISSUE THREAD

**Issue by usmanrana07** [google/dagger#1727] opened 2020-01-30 07:24 UTC
Since I've updated Dagger version  to '2.26' as AndroidInjector is introduced and 'HasSupportFragmentInjector' is removed. So, calling the line `'AndroidSupportInjection.inject(this);'` in fragment is giving error:

 ```
java.lang.IllegalArgumentException: No injector factory bound for Class<TestFragment>
        at dagger.android.DispatchingAndroidInjector.inject(DispatchingAndroidInjector.java:136)
        at dagger.android.support.AndroidSupportInjection.inject(AndroidSupportInjection.java:93)
        at dagger.android.support.AndroidSupportInjection.inject(AndroidSupportInjection.java:67)
        at dagger.android.support.DaggerFragment.onAttach(DaggerFragment.java:39)
```

**Comment by bcorso** [comment] 2020-01-30 18:06
Which version of Dagger are you upgrading from?

It looks like the subcomponent factory for your `TestFragment` was not bound to the multimap (see https://dagger.dev/android#injecting-fragment-objects), e.g.

```java
@Module(subcomponents = TestFragmentSubcomponent.class)
abstract class TestFragmentSubcomponentModule {
  @Binds
  @IntoMap
  @ClassKey(TestFragment.class)
  abstract AndroidInjector.Factory<?> bind(TestFragmentSubcomponent.Factory factory);
}
```

Can you check that you have this `@Binds` (with the correct return type) and that the module is included in the correct parent component.

**Comment by usmanrana07** [comment] 2020-01-31 05:25
I upgraded from '2.22.1'.

**Comment by bcorso** [comment] 2020-01-31 17:09
`HasAndroidInjector` was added in `2.23` and `HasSupportFragmentInjector` was removed in `2.24`, so upgrading to `2.26` will require a migration.

Can you double check the [docs](https://dagger.dev/android#injecting-fragment-objects) and make sure there isn't anything you've missed? 

One thing to look for is that `@Binds` method return types used to be `Factory<? extends Fragment>` etc... and now they're just `Factory<?>`. If you don't get the return type exact it won't go into the correct multimap.

If you're still having issues, a repro case would help determine what the issue is.

**Comment by usmanrana07** [comment] 2020-02-03 05:25
It is like this:

```
@Beta
@Module
public abstract class AndroidInjectionModule {
  @Multibinds
  abstract Map<Class<?>, AndroidInjector.Factory<?>> classKeyedInjectorFactories();

  @Multibinds
  abstract Map<String, AndroidInjector.Factory<?>> stringKeyedInjectorFactories();

  private AndroidInjectionModule() {}
}

```

and component is:

@Singleton
```
@Component(modules = {AndroidInjectionModule.class
        , AppModule.class
        , ActivityBuilder.class
        , ServiceBuilderModule.class
        , WorkerBuilderModule.class
        , AndroidSupportInjectionModule.class
        , AndroidWorkerInjectionModule.class
})
public interface AppComponent {

    void inject(DemoApp app);


    @Component.Builder
    interface Builder {

        @BindsInstance
        Builder application(Application application);

        AppComponent build();
    }
}
```

**Comment by bcorso** [comment] 2020-02-04 16:52
`@Multibinds` just declares that a multibindng map exists, but it doesn't actually add anything into the map. If you look at the [documentation](https://dagger.dev/android#injecting-fragment-objects), you should have a module that `@Binds` your factory into the map (see [my previous comment](https://github.com/google/dagger/issues/1727#issuecomment-580380994)). 

Can you verify that you have that module and that you are installing it in the correct component?

**Comment by bcorso** [comment] 2020-02-18 18:07
Closing this for now. However, please reopen if you're still having issues.

**Closed by bcorso** 2020-02-18 18:07 UTC
Labels: area: android, needs more information
