### ISSUE TITLE
Dagger 2 cannot provide generated Android DataBinding (compilation error)

### ISSUE THREAD

**Issue by ZakTaccardi** [google/dagger#339] opened 2016-03-15 04:06 UTC
Dagger2 generates code. The DataBinding library generates code. Bad things (build failure) happen when dagger2 needs to @Provides the generated binding classes

See the MainActivityModule.java file.

```

    @Provides
    @Singleton
    @SuppressWarnings("deprecation")
    /**
     * Providing this scene here causes a compilation error because of the {@link MoreTextBinding} parameter
     */
    public Scene layoutScene(LinearLayout container, MoreTextBinding binding) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            return new Scene(container, binding.getRoot());
        } else {
            return new Scene(container, (ViewGroup) binding.getRoot());
        }
    }

```
Full code demonstrating this compilation error can be found here: https://code.google.com/p/android/issues/detail?id=203853

Could be a duplicate of https://github.com/google/dagger/issues/252 (but if so this issue needs to be re-opened)

**Comment by gk5885** [comment] 2016-04-07 14:23
What is the error?

**Comment by ronshapiro** [comment] 2016-04-07 14:34
I don't think it's a dupe of #252 since that discusses types that are generated as part of `javac` annotation processing, but my sense is that the Android Data Binding API generates code in a different step. I think @lisawray and/or @ekchang have also had this issue with databinding

**Comment by ekchang** [comment] 2016-04-07 14:58
There is no default constructor for the generated binding classes so you need to provide it for the graph to figure out how to get it.

```
@Provides @PerActivity MoreTextBinding provideMoreItemBinding() {
    return DataBindingUtil.setContentView(activity, R.layout.more_text); // or DataBindingUtil.inflate() etc
}
```

**Comment by BuhTigRunner** [comment] 2016-05-27 15:45
I also have a similar problem
`public class MainActivity extends BaseActivity<ScreenTestBinding>` - error
`C:\Android Projects\TestArchitecture\app\src\main\java\com\example\dmn687\testarchitecture\MainActivity.java
Error:(12, 55) error: package com.example.dmn687.testarchitecture.databinding does not exist
Error:(16, 48) error: cannot find symbol class ScreenTestBinding
C:\Android Projects\TestArchitecture\app\src\main\java\com\example\dmn687\testarchitecture\BaseActivity.java
Error:(9, 55) error: package com.example.dmn687.testarchitecture.databinding does not exist
Error:(23, 15) error: cannot find symbol class ScreenTestBinding
where T is a type-variable:
T extends Object declared in class BaseActivity`
Where ScreenTestBinding - generated class extends android.databinding.ViewDataBinding
If use `public class MainActivity extends BaseActivity<ViewDataBinding>` - all ok

**Closed** 2016-08-09 20:48 UTC
Labels: status: needs more information
