### ISSUE TITLE
NPE On Lazy Dagger

### ISSUE THREAD

**Issue by wahyupermadie** [google/dagger#4392] opened 2024-08-15 09:29 UTC
Hi Dagger Team, I'm getting error due to NPE on Lazy Dagger

## Env:
```
dagger 2.43.2
```

## Error
```
NullPointerException: Attempt to invoke interface method 'java.lang.Object dagger.Lazy.get()' on a null object reference
```

This error I got in my Application class when retrieving the lazy injection, my application extend DaggerApplication
```
@Inject Lazy<Set<ClassA>> classA;

@Override
public void onCreate() {
    classA.get()
}
```
Dagger Module Example
```
@Module
class AppModule {
  @Provides
  @IntoSet
  fun provideClassXyz(): ClassA = ClassXyz()
}
```

This issue I observe in firebase crashlytics, but still not able to reproduce locally

**Comment by bcorso** [comment] 2024-12-03 00:16
If your property is `null` it means that the injection didn't happen. 

Unfortunately, if you can't reproduce locally there's not much we can do.

I'm going to close this, but feel free to reopen if you get more information or can share a repro example.

**Closed by bcorso** 2024-12-03 00:16 UTC
