### ISSUE TITLE
2.38: cannot instantiate ViewModel because of missing default constructor

### ISSUE THREAD

**Issue by fobo66** [google/dagger#2770] opened 2021-07-22 11:20 UTC
After update to Hilt 2.38, my app started to crash after start on instantiating ViewModel. Looks like default constructor is not generated. It can be kapt issue, but it worked fine on 2.37.

I was using `lifecycle-viewmodel-ktx` library on 2.3.1 version, updating it 2.4.0-alpha02 didn't help

Stacktrace:

```
2021-07-22 14:08:49.465 8158-8158/fobo66.exchangecourcesbelarus.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fobo66.exchangecourcesbelarus.debug, PID: 8158
    java.lang.RuntimeException: Cannot create an instance of class fobo66.exchangecourcesbelarus.ui.MainViewModel
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:221)
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278)
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at fobo66.exchangecourcesbelarus.ui.MainFragment.getViewModel(MainFragment.kt:41)
        at fobo66.exchangecourcesbelarus.ui.MainFragment.setupSwipeRefreshLayout(MainFragment.kt:100)
        at fobo66.exchangecourcesbelarus.ui.MainFragment.onViewCreated(MainFragment.kt:72)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2985)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:532)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:259)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1327)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2757)
        at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2693)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2986)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:532)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:259)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1327)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2757)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2700)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:477)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
        at android.app.Activity.performStart(Activity.java:8076)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3658)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2202)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7829)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:982)
     Caused by: java.lang.InstantiationException: java.lang.Class<fobo66.exchangecourcesbelarus.ui.MainViewModel> has no zero argument constructor
        at java.lang.Class.newInstance(Native Method)
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:219)
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278) 
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150) 
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54) 
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41) 
        at fobo66.exchangecourcesbelarus.ui.MainFragment.getViewModel(MainFragment.kt:41) 
        at fobo66.exchangecourcesbelarus.ui.MainFragment.setupSwipeRefreshLayout(MainFragment.kt:100) 
        at fobo66.exchangecourcesbelarus.ui.MainFragment.onViewCreated(MainFragment.kt:72) 
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2985) 
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:532) 
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:259) 
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1327) 
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2757) 
        at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2693) 
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2986) 
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:532) 
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:259) 
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1327) 
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2757) 
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2700) 
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262) 
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:477) 
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455) 
        at android.app.Activity.performStart(Activity.java:8076) 
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3658) 
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221) 
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2202) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7829) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:982) 
```

MainFragment.kt where it happens:

```kotlin
@AndroidEntryPoint
class MainFragment : Fragment() {

  private val viewModel: MainViewModel by viewModels()
  // ...
```

MainViewModel.kt:

```kotlin
@HiltViewModel
class MainViewModel @Inject constructor(
  private val refreshExchangeRates: RefreshExchangeRates,
  private val loadExchangeRates: LoadExchangeRates,
  private val copyCurrencyRateToClipboard: CopyCurrencyRateToClipboard,
  private val findBankOnMap: FindBankOnMap
) : ViewModel() {

  val bestCurrencyRates: Flow<List<BestCurrencyRate>>
    get() = loadExchangeRates.execute()

  val errors: SharedFlow<Unit>
    get() = _errors

  val progress: SharedFlow<Boolean>
    get() = _progress

  private val _errors = MutableSharedFlow<Unit>()
  private val _progress = MutableSharedFlow<Boolean>()

  fun findBankOnMap(bankName: CharSequence): Intent? {
    return findBankOnMap.execute(bankName)
  }

  fun refreshExchangeRates() =
    viewModelScope.launch {
      try {
        showProgress()
        refreshExchangeRates.execute(LocalDateTime.now())
        hideProgress()
      } catch (e: CurrencyRatesLoadFailedException) {
        Timber.e(e, "Error happened when refreshing currency rates")
        _errors.emit(Unit)
      } finally {
        hideProgress()
      }
    }

  fun copyCurrencyRateToClipboard(currencyName: CharSequence, currencyValue: CharSequence) {
    copyCurrencyRateToClipboard.execute(currencyName, currencyValue)
  }

  private suspend fun showProgress() {
    _progress.emit(true)
  }

  fun hideProgress() {
    viewModelScope.launch {
      _progress.emit(false)
    }
  }
}
```

Dependencies of MainViewModel are provided here:

```kotlin
@Module
@InstallIn(ViewModelComponent::class)
abstract class CurrencyRatesModule {

  @Binds
  abstract fun provideRefreshExchangeRates(
    refreshExchangeRatesImpl: RefreshExchangeRatesImpl
  ): RefreshExchangeRates

  @Binds
  abstract fun provideLoadExchangeRates(
    loadExchangeRatesImpl: LoadExchangeRatesImpl
  ): LoadExchangeRates

  @Binds
  abstract fun provideCopyCurrencyRateToClipboard(
    copyCurrencyRateToClipboardImpl: CopyCurrencyRateToClipboardImpl
  ): CopyCurrencyRateToClipboard

  @Binds
  abstract fun provideFindBankOnMap(
    findBankOnMapImpl: FindBankOnMapImpl
  ): FindBankOnMap
}
```

**Comment by Chang-Eric** [comment] 2021-07-26 21:40
Thanks for the report, I believe this is happening due to #2784. Closing this as a duplicate assuming that is the case.

**Closed by Chang-Eric** 2021-07-26 21:40 UTC

**Comment by fobo66** [comment] 2021-08-05 20:50
This issue happened to me again in another project on 2.38.1 after updating Kotlin to 1.5.21 due to Jetpack Compose 1.0.1

**Comment by Chang-Eric** [comment] 2021-08-05 22:32
@fobo66 The issue that caused this is that the Fragment/Activity hosting the ViewModel didn't have the override of `getDefaultViewModelProviderFactory()` because of the issue above with the plugin not working.

If this is happening for you, can you check that your ViewModel owner is a Hilt type? `@HiltViewModel` isn't supposed to have a default constructor, so it can't be instantiated using the default ViewModel factory. The issue is usually the factory is not being used somehow. (There's some docs on Hilt ViewModel and compose here too: https://developer.android.com/jetpack/compose/libraries#hilt)

**Comment by fobo66** [comment] 2021-08-06 13:06
My ViewModel has `@HiltViewModel` annotation and SavedStateHandle, but for some reason, ViewModelProvider cannot see that and tries to use NewInstanceFactory (base class). Activity, where composable is placed, is annotated with `@AndroidEntryPoint` and has override for `getDefaultViewModelProviderFactory()` because it inherits from `ComponentActivity`.

Here's the stack trace from my Compose class:

```
2021-08-06 15:48:38.125 6269-6269/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.fobo66.factcheckerassistant, PID: 6269
    java.lang.RuntimeException: Cannot create an instance of class io.github.fobo66.factcheckerassistant.ui.main.MainViewModel
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:221)
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278)
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at androidx.lifecycle.viewmodel.compose.ViewModelKt.get(ViewModel.kt:87)
        at androidx.lifecycle.viewmodel.compose.ViewModelKt.viewModel(ViewModel.kt:72)
        at io.github.fobo66.factcheckerassistant.ui.list.ClaimsSearchKt.ClaimsSearch(ClaimsSearch.kt:130)
        at io.github.fobo66.factcheckerassistant.ui.main.MainActivity$onCreate$1$1$1$2$1$1.invoke(MainActivity.kt:96)
        at io.github.fobo66.factcheckerassistant.ui.main.MainActivity$onCreate$1$1$1$2$1$1.invoke(MainActivity.kt:95)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
...
Caused by: java.lang.InstantiationException: java.lang.Class<io.github.fobo66.factcheckerassistant.ui.main.MainViewModel> has no zero argument constructor
        at java.lang.Class.newInstance(Native Method)
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:219)
```

MainViewModel is injected inside Compose function like usual:

```kotlin
@ExperimentalFoundationApi
 @ExperimentalAnimationApi
 @ExperimentalMaterialApi
 @ExperimentalCoroutinesApi
 @Composable
fun ClaimsSearch(mainViewModel: MainViewModel = viewModel(), onItemClick: (Claim?) -> Unit) {
// ...
}
```

Here's my [PR](https://github.com/fobo66/FactCheckerAssistant/pull/140) with the code

**Comment by danysantiago** [comment] 2021-08-06 15:25
@fobo66, I took a look at your project and your PR and the issue is that you compose functions where you are trying to get the `ViewModel` from are inside a Navigation graph. Therefore the compose function `viewModel()` will *not* use the Activity's `ViewModelFactory` and instead will use the closest `LocalViewModelStoreOwner` which will be a `NavGraphEntry`.

If you want to use Hilt injected ViewModels use the `androidx.hilt:hilt-navigation-compose` artifact and the `hiltViewModel()` method as described here: https://developer.android.com/jetpack/compose/libraries#hilt-navigation

**Comment by fobo66** [comment] 2021-08-06 17:17
@danysantiago Oh, somehow I missed this, probably thinking that it's the same thing as `androidx.lifecycle.viewmodel.compose.viewModel`. Thanks, it works fine now. Sorry for bothering
