### ISSUE TITLE
Allow modules to be provided by libraries without doing codegen so downstream users don't need to maintain the same Dagger compiler version

### ISSUE THREAD

**Issue by anuraaga** [google/dagger#1470] opened 2019-04-08 06:44 UTC
I found that with 2.22.1, previously working stopped compiling correctly in a case where a module declares `static` methods with package-private visibility.

```java
@Module
public abstract class Module1 {
  @Provides
  static Clock clock() {
    return Clock.systemUTC();
  }
}
```

When a component in a different package includes that module

```
Main_Component.java:196: error: cannot find symbol
        ApplicationModule_ClockFactory.clock(),
                                      ^
  symbol:   method clock()
  location: class ApplicationModule_ClockFactory
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

I can't find anything in the release notes mentioning this - is it an intended change? I had preferred using package-private on the methods since it meant that users have to go through Dagger to get the dependencies without exposing the methods to themselves to other modules. On the flip side, expecting public modules to declare all public methods for providers makes some sense in correctly modeling that the dependencies are, in fact, public so I see both ways and will update my code if this was indeed intended :)

**Comment by cgdecker** [comment] 2019-04-09 20:39
Can you provide a small, complete example demonstrating the problem? I just tried what you seem to be describing in 2.22.1 and it worked fine.

**Comment by ronshapiro** [comment] 2019-04-09 20:54
I think the issue is that your module was compiled with an old version of dagger, where the generated method is called `ApplicationModule_ClockFactory.`**`proxyClock()`** and the new version of Dagger expects it to be called `ApplicationModule_ClockFactory.`**`clock()`**.

Check the versions to make sure they're consistent

**Comment by anuraaga** [comment] 2019-04-10 14:14
Ah thanks for the insight and sorry for not having a proper example. That makes sense.

Is compile compatibility across versions of dagger not guaranteed (for reference I think protobuf always ensures forward, if not backward compatibility). I like to expose dagger modules in public APIs since it can make the library much easier to use for dagger users, while non-dagger users can still use the constructors directly. I didn't expect to run into this sort of compatibility issue though

**Comment by ronshapiro** [comment] 2019-04-10 15:28
It is not guaranteed. I think it ideally would be nice, but practically would be very difficult to make improvements if we had to stick to the generated APIs of once past.

Perhaps we can consider a way to defer the generation to library users so that library authors can export just the guaranteed APIs. Are you ok with me renaming this issue for that?

**Comment by anuraaga** [comment] 2019-04-10 15:46
Yeah feel free to rename the issue :)

Just some ideas, with no deep dive on how practical they are

- The older codegen upstream was with 2.21 and newer downstream was with 2.22. It would be cool if at least for X versions, even just one like here, dagger could recognize the mismatch and output a warning and the old code, or at least a clearer error message and bail. The error being a normal javac error made it hard to grok. I think this only needs a static field with codegen version in modules, and the codegen checks it, to achieve. Having just one version of compatibility, or at least easy to understand error message, would be enough for me.

- When generated method names are changed, or similar compatibility changes, seeing it in the release notes would be great. If I just missed it in the descriptions, sorry it's all on me. That being said, it is difficult if there isn't at least forward compatibility in the generated code since a library user could update before I get a chance to. But I don't mind watching the repo to catch such releases and update ASAP when a generated API change happened

**Comment by Chang-Eric** [comment] 2020-06-23 23:47
I'm going to close this for now since I don't know that there is specific work to be done here. I do agree though that in the future we should be thinking about compatibility as we make changes and try to keep things compatible for some versions to give libraries a chance to update and also try to call these things out in the release notes. Thanks!

**Closed by Chang-Eric** 2020-06-23 23:47 UTC
