### ISSUE TITLE
@JvmStatic still required for companion object modules

### ISSUE THREAD

**Issue by mos8502** [google/dagger#1675] opened 2019-11-18 04:23 UTC
dagger `2.25.2` removes the requirement to annotation provides methods with `@JmvStatic`:

> Module object classes no longer need @JvmStatic on the
provides methods. (0da2180)

However it seems that `@JvmStatic` seems to be required for provides methods in a module's `companion object`

E.g.:

```
@Module
abstract class FooModule {
  @Module 
  companion object {
    @Provides
    fun providesBar(...): Bar = ...
  }
}
```

Will result in an error like this:

`error: [Dagger/MissingBinding] Bar cannot be provided without an @Inject constructor or an @Provides-annotated method`

Annotating `providesBar` with `@JvmStatic` solves the compilation error. 
Maybe it's just the release notes that is not explicit about the improvement only applying to non `companion object` modules ?

**Comment by danysantiago** [comment] 2019-11-18 17:10
Yup the improvement is only for non companion objects, supporting companion objects are still a work-in-progress.

Closing this as a duplicate of #1646.

**Closed by danysantiago** 2019-11-18 17:10 UTC
