### ISSUE TITLE
ClassNotFoundException for application class

### ISSUE THREAD

**Issue by tiago7s** [google/dagger#3106] opened 2021-12-12 19:54 UTC
Any version from 2.40 to 2.40.5 has this issue. I have `7.1.0-beta04` AGP and  `enableExperimentalClasspathAggregation = true` if that matters.

```
java.lang.RuntimeException: Unable to instantiate application com.lingq.LingQApplication: java.lang.ClassNotFoundException: Didn't find class "com.lingq.LingQApplication" on path: DexPathList[[zip file "/data/app/~~AWCPKpRSuMdU3_aTj3QwBQ==/com.linguist-Y3P74mNdaL-WpdGThqSknA==/base.apk"],nativeLibraryDirectories=[/data/app/~~AWCPKpRSuMdU3_aTj3QwBQ==/com.linguist-Y3P74mNdaL-WpdGThqSknA==/lib/arm64, /system/lib64]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1332)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7532)
        at android.app.ActivityThread.access$1500(ActivityThread.java:301)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2166)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.lingq.LingQApplication" on path: DexPathList[[zip file "/data/app/~~AWCPKpRSuMdU3_aTj3QwBQ==/com.linguist-Y3P74mNdaL-WpdGThqSknA==/base.apk"],nativeLibraryDirectories=[/data/app/~~AWCPKpRSuMdU3_aTj3QwBQ==/com.linguist-Y3P74mNdaL-WpdGThqSknA==/lib/arm64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
        at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1158)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1324)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7532) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:301) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2166) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8633) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/lingq/Hilt_LingQApplication;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        		... 14 more
```

**Comment by bcorso** [comment] 2021-12-21 01:38
Hmm, sometimes we've seen this happen if you aren't using a [multidex application](https://developer.android.com/studio/build/multidex#mdex-gradle)?

If that doesn't help, is there any way you could provide a example project that reproduces the issue so that I can take a look?

**Comment by remcomokveld** [comment] 2021-12-21 06:17
Multiple members on our team reported the same, starting with 2.40.0 but still happening on 2.40.5. It seems to only affect incremental builds, clean builds on the same code then compiles fine.

**Comment by tiago7s** [comment] 2021-12-21 12:19
> Hmm, sometimes we've seen this happen if you aren't using a [multidex application](https://developer.android.com/studio/build/multidex#mdex-gradle)?
> 
> If that doesn't help, is there any way you could provide a example project that reproduces the issue so that I can take a look?

I have min sdk 23 so multidex is enabled by default. Dont have a project to provide for testing.

> Multiple members on our team reported the same, starting with 2.40.0 but still happening on 2.40.5. It seems to only affect incremental builds, clean builds on the same code then compiles fine.

I have tried clean builds and same thing happens. Its not a compile issue, its a runtime issue.

**Comment by remcomokveld** [comment] 2021-12-21 12:44
> Its not a compile issue, its a runtime issue.

I think it is a compile-time issue that only manifests itself at runtime, probably due to a bug in byte-code manipulation somewhere. Did you check if the class file for `com.lingq.LingQApplication` actually exists in one of the dex files using Studio's APK analyzer?

> I have tried clean builds and same thing happens.

When you say clean build does did you also disable Gradle's build cache?

**Comment by bcorso** [comment] 2021-12-21 16:15
@tiago7s do you have the same issue if you replace `enableExperimentalClasspathAggregation` with [`enableAggregatingTask`](https://dagger.dev/hilt/gradle-setup#aggregating-task) gives you the same issue?

**Comment by qavan** [comment] 2021-12-27 05:10
Faced with same issue. Clearing `build-cache-1`, `transforms-3` and all `build` directories in project "fixed" problem.

@tiago7s same with `enableExperimentalClasspathAggregation = false` and `enableAggregatingTask = true`

**Comment by tiago7s** [comment] 2022-01-26 02:06
Unfortunately I have tried doing everything suggested here and nothing works. I have deleted all the gradle cache and even all the build folders on the project. I even tried using MultidexApplication even if the min SDK is 23. `enableAggregatingTask` does nothing as well.

What I have also tried was to build using `gradlew installDebug` from the terminal, and check the apk. The app class is there, both `LingQApplication` and `Hilt_LingQApplication` but it keeps saying it doesn't find it. Can I somehow send the built apk so you can check the classes?

**Comment by tiago7s** [comment] 2022-01-26 03:33
As a last effort to make this work, I have created a new Application class in the application module that extends the base library Application class and this finally fixed it. It seems there might be some issue if the `@HiltAndroidApp` annotated class is on a library and not at the top app module. For me this fixed it, not sure if its something investigating for you. If not you can just close this issue. Thanks for the help.

**Comment by bcorso** [comment] 2022-02-15 04:03
@tiago7s thanks for posting back your findings -- that's very useful information.

`@HiltAndroidApp` was really only designed to be used a the root application level, but I don't think we have that in our docs. 

At the very least we should update our docs, but talking with the team I think it may be possible to also give a better error message when someone does set it up in a library. We'll leave this issue open to track those changes.

**Comment by PatrickVvB** [comment] 2022-08-24 16:11
I had the same error while running apps. In gredle I used ksp for androidx.hilt:hilt-compiler and com.google.dagger:hilt-android-compiler dependencies. When I changed to kapt the error went away

**Comment by mmd44** [comment] 2022-09-20 12:11
Any fix for this?
This is a breaking change and no one has fixed it yet!

**Comment by bcorso** [comment] 2022-09-20 18:39
According to the @tiago7s the issue was that `@HiltAndroidApp` was being used in a library rather than an application module. This is working as intended, as we can't generally support using `@HiltAndroidApp` in libraries.

Thus, the fix is on the users side -- you need to move the `@HiltAndroidApp` into the application module. @mmd44 , if that doesn't fix your issue, then you may be running into something else and you should file a separate issue.

Also, I'm going to close out this issue now. In https://github.com/google/dagger/issues/3106#issuecomment-1039830675, I decided to leave this issue open until we were able to add better error messages for this, and that was finished in https://github.com/google/dagger/commit/c23fcd3ee08abbc7056a0b36f4cd647d0ee0bee7.

**Closed by bcorso** 2022-09-20 18:39 UTC

**Comment by mmd44** [comment] 2022-09-21 06:12
@bcorso This is issue is only happening on 2.40.x -> 2.43.x and in order to use Kotlin 1.7 and above this version of Hilt is required.
My app is a multi-module app with a base code that has the application file with the `@HiltAndroidApp` annotation...Modules (or white-labels) do not have an Application class and have their Gradle dependencies included from the base code...
Everything was working as expected until the update was triggered.
Let me know if you need more info.

**Comment by bcorso** [comment] 2022-09-21 16:19
> I use different modules for different resources only

Without knowing more about your app, it sounds like the recommended approach for this would be to use different build variants/flavors to control the different resources for each build variant. This way you could move your `@HiltAndroidApp`-annotated class into the Gradle application module.

Another option which may work (but not really ideal), you could try to make the application in your library a base application (not annotated with `@HiltAndroidApp`) and then each Gradle application module would include an application class that extends the base and is annotated with `@HiltAndroidApp`, e.g.

```kotlin
@HiltAndroidApp
class DevApplication : BaseApplication() {}
```

> Everything was working as expected until the update was triggered.

I think you just kind of got lucky about this -- it was never intended to work at the library level and is error-prone there because it may miss Hilt contributions (e.g. from `@InstallIn` modules or entry points) from transitive dependencies. There's not a good way to support using `@HiltAndroidApp` at the library level, so I'd avoid using it even in the older versions of Hilt even if it seems to work correctly today.

**Comment by mmd44** [comment] 2022-09-21 16:38
I have 10+ modules...Implementing your approach (I think this is my only option) would require me to add Hilt dependencies in each module's gradle file...

**Comment by bcorso** [comment] 2022-09-21 17:29
> would require me to add Hilt dependencies in each module's gradle file...

Can you expand on why that would be an issue for you? IIUC, it should just be two lines of dependencies in each `build.gradle` file, or am I missing something?

**Comment by bcorso** [comment] 2022-09-21 17:30
Also, can you expand on why using build variants isn't an option for you?

**Comment by tiago7s** [comment] 2022-09-22 16:29
@mmd44 I'm a bit confused with the issue you are having. I have a multi module apps and just created an Application class on the app module that extends from the application class on the base module. The requirement is simply to only use the `@HiltAndroidApp` on the top application module.
