### ISSUE TITLE
[Hilt] Feature Request: Better error message when internal used in @EntryPoint declaration

### ISSUE THREAD

**Issue by snepalnetflix** [google/dagger#2139] opened 2020-10-09 02:54 UTC
Our team is experiencing a large learning curve when using Hilt. The two biggest contributors to this learning curve are:
* flaky compilation (having to do clean builds a lot)
* confusing error messages

This ticket is a feature request for better error messages when a entry point is declared with the internal keyword. For example:
```
class Foo {
  ...
  @EntryPoint
  @InstallIn(SingletonComponent::class)
  internal interface SingletonAccessor {
    fun getBar(): Bar
  }
}
```

In the above example, the reported error is:
```
ava.lang.ClassCastException: Cannot cast com.example.DaggerDebugMyApplication_HiltComponents_SingletonC to com.example.feature.Foo$SingletonAccessor
```

This feature might require a better Kotlin annotation processor which I hear is in the pipeline.

**Comment by bcorso** [comment] 2020-10-10 04:20
@snepalnetflix thanks for sharing this.

However, I can't seem to reproduce this. Do you have a repro app you can share?

**Comment by bcorso** [comment] 2020-10-14 17:24
After discussing this more with @Chang-Eric, I think this may be an issue with using "implementation" dependency vs "api". The reason is that it looks like our `@HiltAndroidApp` processor isn't detecting your entry point at compile-time, which could happen in a situation where you have Gradle modules dependencies with "implementation" like `A -> B -> C` where the `@HiltAndroidApp` is in `A` and the `@EntryPoint` is in `C`. There's currently no way for `A` to know about the entry point in `C` since it depends on it transitively through "implementation" dependencies so it doesn't have access to those sources (or generated sources).

We're looking into fixing the general issues with using "implementation" in Dagger and Hilt with the Gradle team, which might take a while. However, in the meantime, we can look into at least making this issue result in an obvious compile-time error.

**Comment by Chang-Eric** [comment] 2020-11-18 18:25
For reference, #1991 is the issue mentioned above.

**Comment by DroidPulkit** [comment] 2021-02-04 06:34
My team is still facing the same problem, as of now. Getting cast error, when running androidTest cases
java.lang.ClassCastException: Cannot cast com.example.client.DaggerPFAApplication_HiltComponents_SingletonC to com.example.client.osiris.di.components.TestPFAApplicationComponentEntryPoint
It's pretty annoying, if the component class I use is from same module com.example.client.PFAApplicationComponentEntryPoint then atleast the test cases compile and let it run, but I cannot inject Presentor or VM to test cases, as in order to inject, I have to use com.example.client.osiris.di.components.TestPFAApplicationComponentEntryPoint as all test cases are here.

Tried the fix suggested over here: https://dagger.dev/hilt/gradle-setup#classpath-aggregation
But it doesn't help

**Comment by bcorso** [comment] 2021-03-01 20:08
@DroidPulkit sorry, your comment must have slipped through the cracks. I'm going to close this issue because I believe the original feature request was more of a red herring, and it "should" be solved by https://dagger.dev/hilt/gradle-setup#classpath-aggregation.

It sounds like you're still having issues, but if you don't mind, can you file a new issue (preferably with a sample project with repro steps, as this may be difficult for us to debug without).

**Closed by bcorso** 2021-03-01 20:08 UTC
Labels: P2, area: hilt, type: bug
