### ISSUE TITLE
Allow @IntoSet to target class/constructor

### ISSUE THREAD

**Issue by FunkyMuse** [google/dagger#3042] opened 2021-11-17 12:49 UTC
The use case for this one is the following, for example I have an interceptors module where i'm forced to have a module 

```kotlin
@Module
@InstallIn(SingletonComponent::class)
object NetworkInterceptorModule {
    
    @Provides
    @IntoSet 
    @Singleton
    fun connectivityInterceptor(@ApplicationContext context: Context): Interceptor =
        ConnectivityInterceptor(context)
    
    @Provides
    @IntoSet 
    @Singleton
    fun authorizationInterceptor(encryptedPreferencesManager: EncryptedPreferencesManager): Interceptor =
        BasicAuthInterceptor(encryptedPreferencesManager)
}
```

What would be more useful is for Dagger2 to be able to recognize and allow the following
```kotlin
@IntoSet
@Singleton
class ConnectivityInterceptor @Inject constructor(@ApplicationContext private val context: Context)
```
or
```kotlin
@Singleton
class ConnectivityInterceptor @Inject @IntoSet constructor(@ApplicationContext private val context: Context)
```

Instead of having a module every time and manually needing to provide every dependency this will save time and boilerplate to be written.

**Comment by JakeWharton** [comment] 2021-11-17 13:24
Dupe of #2184, #2026, #633, #510.

**Comment by danysantiago** [comment] 2021-11-17 14:37
See https://github.com/google/dagger/issues/510#issuecomment-287189465 for an explanation of why this is not currently feasible.

**Closed by danysantiago** 2021-11-17 14:37 UTC

**Comment by FunkyMuse** [comment] 2021-11-17 14:44
> See [#510 (comment)](https://github.com/google/dagger/issues/510#issuecomment-287189465) for an explanation of why this is not currently feasible.

Thanks for the explanation, as I can see now that the current hurdle is in the "type" problem, which you'd need to scan for, but maybe it's possible for the subtype, as you can see in the sample above every interceptor is of a subtype of Interceptor, basically the implementation, I know this sounds cheesy and rushed comment but i'm just thinking out loud for the moment without too much knowledge about this problem.

**Comment by bcorso** [comment] 2021-11-17 21:58
Note that the comment in #510 mostly applies to Dagger. 

If you're talking about Hilt, you could probably write your own Hilt extension, similar to https://github.com/sczerwinski/android-hilt to generate an `@InstallIn` Module that binds your implementation class to some interface in some component. 

However, we're unlikely to make this a feature of Hilt. In particular, the API works okay for simple cases, like the one you mentioned above, but can quickly get out of hand for more complex use cases. Thus, IMO it's not a great candidate for an official Hilt feature.
