### ISSUE TITLE
Multibindings can't work in dependent components

### ISSUE THREAD

**Issue by blackberry2016** [google/dagger#1624] opened 2019-10-02 07:08 UTC
Multibindings works well in Inherited subcomponent multibindings.

But it can't work in dependent components. For example, BComponent dependencies AComponent, BComponent can't use @IntoMap to contribute elements to AComponent.
It can olny work when BComponent  is a sub component of AComponent

**Comment by Chang-Eric** [comment] 2020-04-07 22:57
I think this is kind of by design. Component dependencies have a pretty strict interface boundary whereas subcomponents are for things where you want to share information across the boundaries. With component dependencies, you wouldn't be able to tell that a map comes from a map binding especially since we support pulling deps from interfaces that aren't necessarily component interfaces.

Also, maps right now have a guarantee that the keys are validated statically (i.e. duplicated keys are a compile error and so you won't get an issue like that when injecting the map). If we merged the map from a component dependency that validation would have to move to runtime.

**Closed** 2020-04-21 22:14 UTC
