### ISSUE TITLE
Main documentation website down

### ISSUE THREAD

**Issue by MarkOSullivan94** [google/dagger#301] opened 2016-02-01 19:35 UTC
Getting 404 file not found error on this page: http://google.github.io/dagger/shared/users-guide.html

**Comment by JakeWharton** [comment] 2016-02-01 19:43
Dupe of #300 and #299.

**Closed** 2016-02-01 20:00 UTC

**Comment by MarkOSullivan94** [comment] 2016-02-01 21:05
Sorry only checked the open issues!
