### ISSUE TITLE
Components not supporting extending generic interfaces: needs human readable error

### ISSUE THREAD

**Issue by pyricau** [google/dagger#65] opened 2014-11-11 15:21 UTC
Sample code:

```
  public interface Injector<T> {
    void inject(T t);
  }

  @Component interface Lalala extends Injector<MyView> {
  }
```

This does not compile because Injector is parameterized.

Two things to consider here:

1) The error below is thrown at compilation time. It's a "valid" error, but it needs to be more human readable.

2) I understand why this isn't allowed right now: it's more work AND it's useless as soon as you have more than one type to inject from that component. However, in our Android apps, we create one component per custom view (I can explain why if needed) and in most cases have only one entry point. We hide components in a ContextWrapper, and it'd be nice to return a Injector<T> from that context wrapper and use that from the view.

```
Caused by: java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
	at dagger.internal.codegen.InjectBindingRegistry.getOrFindMembersInjectionBinding(InjectBindingRegistry.java:198)
	at dagger.internal.codegen.BindingGraph$Factory$RequestResolver.resolve(BindingGraph.java:318)
	at dagger.internal.codegen.BindingGraph$Factory.create(BindingGraph.java:155)
	at dagger.internal.codegen.ComponentProcessingStep.process(ComponentProcessingStep.java:70)
	at dagger.internal.codegen.ComponentProcessor.process(ComponentProcessor.java:146)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
	at com.sun.tools.javac.main.Main.compile(Main.java:439)
	... 68 more
```

**Comment by svenjacobs** [comment] 2015-01-10 13:48
I just stumbled upon this, too.
I tried something like:

```java
@Component
interface ActivityComponent {

    <T extends Activity> T inject(T activity);
}
```

so that I could use one component for all Activities and execute the dependency injection in an abstract Activity base class.

The compile error should be clear. Preferably this should work, of course ;)

**Comment by gk5885** [comment] 2015-04-03 21:29
Reproduced and a fix is on the way.

**Comment by cgruber** [comment] 2015-04-08 02:32
so:

```java
public interface Injector<T> {
    void inject(T t);
  }

  @Component interface Lalala extends Injector<MyView> {
  }
```

is fixed.  However, 

```java
@Component
interface ActivityComponent {
    <T extends Activity> T inject(T activity);
}
```

is not.  Or rather, it throws a different exception, and does not issue an appropriate error that fails the build.

I'm going to close this issue, since the original issue is resolved, but I'll file a bug for the compiler crash.

**Closed by cgruber** 2015-04-08 02:32 UTC
