### ISSUE TITLE
Improve Kotlin support for qualified provision vals

### ISSUE THREAD

**Issue by tfcporciuncula** [google/dagger#1816] opened 2020-04-15 18:24 UTC
Right now this won't work:

```kotlin
interface MyComponent {

  @MyQualifier val myDependency: MyDependency
}
```

But this will:

```kotlin
interface MyComponent {

  @get:MyQualifier val myDependency: MyDependency
}
```

This is similar to how things were for qualifier annotations on fields in Kotlin. [That was improved on Dagger 2.25.2](https://github.com/google/dagger/commit/646e0336cdbe454baa5fe73c0af11f211a92deeb), so I thought this could be improved too.

**Comment by danysantiago** [comment] 2020-04-15 18:27
Yup, it's on 'the radar'. I'll close this as dupe of https://github.com/google/dagger/issues/1719

**Closed by danysantiago** 2020-04-15 18:27 UTC
