### ISSUE TITLE
Two inner class subcomponent siblings can't have the same simple class name

### ISSUE THREAD

**Issue by pyricau** [google/dagger#236] opened 2015-09-18 00:34 UTC
Say I have a `RootComponent` with two sub components that are inner classes, `Foo.Component` and `Bar.Component`, then `DaggerRootComponent` will have two `ComponentImpl` classes generated with the same name, which means `DaggerRootComponent` will have compile errors.

The generated subcomponents should use names that include the outer class name.

**Comment by ronshapiro** [comment] 2015-11-17 14:39
Dupe of #194

**Comment by ronshapiro** [comment] 2015-11-30 18:13
A fix for this was submitted internally (and will be linked to this issue when synced with Github). When conflicting simple names are encountered, we're going to continue prepending parts of the FQCN to the Subcomponent impl name until we get unique names. So in the case of `com.example.Bar.Foo` and `com.example.baz.Foo` you'd get `Bar_FooImpl`and `baz_FooImpl`.

**Closed** 2015-11-30 18:14 UTC
