### ISSUE TITLE
Building an Android UI test module with more than 1 UI test fails on ':uitest:hiltAggregateDepsDebug'

### ISSUE THREAD

**Issue by vpuonti** [google/dagger#3478] opened 2022-07-22 10:03 UTC
Hi,

We started adding Jetpack Compose to our project and while doing that, also updated Hilt from `2.38.1` to `2.42`. 
Now our `:uitest` module is not building due to an error:
```
Execution failed for task ':uitest:hiltAggregateDepsDebug'.
> A failure occurred while executing dagger.hilt.android.plugin.task.AggregateDepsTask$WorkerAction
   > Collection has more than one element.
```
Hilt `2.39` is the latest version that works fine. I checked the release notes for what could be the cause, and saw that Hilt `2.40` turned on `enableAggregatingTask` by default. 
I think that change might be the reason I'm facing this error, but I'm not so knowledgeable on "compilation units" etc to apply the info written here [(Sharing Test Components)](https://dagger.dev/hilt/flags.html#sharing-test-components) to the issue I'm facing. 

Do I need to change the way I structure my tests? 
Do I need to pass some flags? 
Is disabling `enableAggregatingTask` a possibility and will that have some adverse effects down the line?

I've created a repro project which is hosted here: https://github.com/vpuonti/hilt-ui-test-repro

Thanks in advance!

**Comment by vpuonti** [comment] 2022-07-22 12:08
Adding 
```
hilt {
    enableAggregatingTask = false
}
```
to `uitest/build.gradle` fixes the issue, so it seems the issue is resolved!

I would still like to know if that is the recommended approach when you have UI tests in their own module.

**Comment by bcorso** [comment] 2022-07-22 16:45
Hi @vpuonti, this sounds like it could be a duplicate of #3464, which should be fixed in  [Dagger 2.43](https://github.com/google/dagger/releases/tag/dagger-2.43). 

Can you try upgrading to 2.43 and see if it fixes your issue **without** having to set `enableAggregatingTask = false`?

**Comment by vpuonti** [comment] 2022-07-25 07:39
Hi @bcorso I upgraded to Hilt `2.43` but the issue still persists.

**Comment by danysantiago** [comment] 2022-07-25 14:40
It seems that the issue is Hilt's task configuration not considering the sources in `src/main` of the `com.android.test` module as tests and we didn't expect to find `@HiltAndroidTest` annotated classes in there. Likely a regression from the previous strategy for aggregating the compile classpath.

As a workaround you can instead move the test module to a `com.android.library` one, moving the tests sources to `androidTest` along with the dependency declarations from `implementation` to `androidTestImplementation`.

**Closed** 2022-08-10 19:48 UTC
Labels: type: bug, area: build, P2, area: hilt
