### ISSUE TITLE
Note: Generating a MembersInjector or Factory for *. Prefer to run the dagger processor over that class instead.

### ISSUE THREAD

**Issue by vanniktech** [google/dagger#328] opened 2016-03-01 08:52 UTC
In Android on [the qualitymatters project](https://github.com/artem-zinnatullin/qualitymatters) we are getting this message from Dagger:

> Note: Generating a MembersInjector or Factory for com.artemzin.qualitymatters.QualityMattersApp. Prefer to run the dagger processor over that class instead.

Also what's interesting is that the moment we're trying to add [error-prone](http://errorprone.info/), compiling will fail with `IllegalStateException couldn't register MembersInjectionBinding ... was already registered for Key{type=com.artemzin.qualitymatters.QualityMattersApp}`. Full Stacktrace is [here](https://github.com/artem-zinnatullin/qualitymatters/pull/89). 

Could you explain this note to @artem-zinnatullin & me?

**Comment by tbroyer** [comment] 2016-03-01 09:45
Could it be related to the fact you also have a `@Provides QualityMattersApp` method in your `ApplicationModule`? Maybe that confuses Dagger…

BTW, there's been a commit related to that message since the 2.0.2 release (https://github.com/google/dagger/commit/9659996e2c39bbd5a42fa03badaf7539db83b3f5) so maybe try a snapshot?

**Comment by artem-zinnatullin** [comment] 2016-03-01 10:59
Yup, just tried to provide `Application` instead of `QualityMattersApp` and Dagger now happy. This is probably even better in terms of Modules design in general and since some users use qualitymatters as template for their projects. 

I'll try snapshot later, thanks for your help, @tbroyer and @vanniktech!

**Comment by artem-zinnatullin** [comment] 2016-03-07 16:20
@tbroyer unfortunately I wrongly said that providing more abstract `Application` class instead of concrete one fixes the issue, I probably did compilation twice and second time it skipped apt for non-changed classes.

Snapshot didn't help too, with and without providing more general application class.

So, issues is still open.

**Comment by tbroyer** [comment] 2016-03-07 16:25
So, how about using accessors on the `ApplicationComponent` for your 2 dependencies instead of injecting the members of `QualityMattersApp`? Would that work as a workaround?

**Comment by artem-zinnatullin** [comment] 2016-03-07 16:26
I'll check, but even if it'll work it won't be a great solution :)

**Comment by tbroyer** [comment] 2016-03-07 16:45
That'd possibly help narrow down the issue though.

**Comment by artem-zinnatullin** [comment] 2016-03-07 23:32
Ok, I confirm, moving dependencies to component and removing all `@Inject`s from application class removes warning

**Comment by artem-zinnatullin** [comment] 2016-03-29 15:55
2.2 didn't fix the problem. Dagger team: do you think it's a problem & if so -> would you be open for a PR?

**Comment by svenjacobs** [comment] 2016-04-28 06:14
I posted a similar [question](http://stackoverflow.com/questions/36396307/getting-rid-of-dagger-2-warning-generating-a-membersinjector) on StackOverflow but unfortunately didn't get any response.

I get these warnings when injecting dependencies into a class which extends from an abstract base class which also contains dependencies.

```java
abstract class AbstractClass {
    @Inject SomeDependency someDependency;
}

class SomeClass extends AbstractClass {
    @Inject AnotherDependency anotherDepenency;

    public void onCreate() {
        component = // Get component instance somehow
        component.inject(this);
    }
}
```

However if I override/implement `onCreate()` in `AbstractClass` and call the dependency injection there, too, the dependency `someDependency` will be injected twice which might lead to unexpected behaviour. Once in `onCreate()` of `AbstractClass` and once in `onCreate()` of `SomeClass`.

What is the best solution to get rid of this warning while preventing duplicate injection of dependencies?

**Comment by gk5885** [comment] 2016-04-28 21:02
I am _pretty_ sure that this issue was addressed.  Have you tried with 2.4?

**Comment by vanniktech** [comment] 2016-04-28 21:36
I did and I'm still getting it.

**Comment by svenjacobs** [comment] 2016-04-29 06:20
I'm on 2.4 and also still get this.

**Comment by tbroyer** [comment] 2016-04-29 12:04
@gk5885 FWIW, in the case of quality-matters at least, the `QualityMattersApp` is deferred (ends up in `deferredElementNames`) during the first round, so the note is emitted when processing the component; then on the second round, it's deemed valid and is passed to the processing steps.

Side note: it's hard to debug shaded classes (namely `BasicAnnotationProcessor`); for some reason IntelliJ fails to decompile it (`Unrecognized invocation of <init>` inside `reportMissingElements (Ljava/util/Map;Ljava/util/Collection;)V`, probably due to bytecode rewriting by the maven-shade-plugin) so I can only use method breakpoints (which are slow as hell) and this only allowed me to confirm that the class was deferred to the next round (I had hints when the class passed through the `InjectProcessingStep` after the note was generated through the `ComponentProcessingStep`); I cannot easily debug why the class was deferred though (would have to build a non-shaded version locally and use that in the Gradle build).
I supposed it might be due, in this case, to `DaggerApplicationComponent.Builder` being exposed as the return type of a method (that class is generated during the first round).

The solution might be a big refactoring to ignore/defer "incomplete (unprocessable) APIs" selectively during processing (having a processing step throw a specific exception when it encounters an error), rather than use up-front filtering that's blind to what the processor will really need (this method is not annotated and not in a component, so will is ignored by Dagger anyway).

**Comment by tbroyer** [comment] 2016-05-01 15:05
Here's a repro case:

```java

  @Test
  public void unprocessedMembersInjectorNotesFalsePositive() {
    assertAbout(javaSources())
        .that(
            ImmutableList.of(
                JavaFileObjects.forSourceLines(
                    "test.TestComponent",
                    "package test;",
                    "",
                    "import dagger.Component;",
                    "",
                    "@Component(modules = TestModule.class)",
                    "interface TestComponent {",
                    "  void inject(TestApplication object);",
                    "}"),
                JavaFileObjects.forSourceLines(
                    "test.TestModule",
                    "package test;",
                    "",
                    "import dagger.Module;",
                    "import dagger.Provides;",
                    "",
                    "@Module",
                    "class TestModule {",
                    "  @Provides static Object object() {",
                    "    return \"object\";",
                    "  }",
                    "}"),
                JavaFileObjects.forSourceLines(
                    "test.TestApplication",
                    "package test;",
                    "",
                    "import javax.inject.Inject;",
                    "",
                    "public class TestApplication {",
                    "  @Inject Object object;",
                    "",
                    "  protected DaggerTestComponent.Builder prepareComponent() {",
                    "    return DaggerTestComponent.builder();",
                    "  }",
                    "}")))
        .withCompilerOptions("-Xlint:-processing")
        .processedWith(new ComponentProcessor())
        .compilesWithoutWarnings()
        .withNoteCount(0);
  }
```

For those in this case, the workaround would be to encapsulate everything and have a method returning the fully-built component (possibly move that method into a separate class if you need to "share" the base implementation instead of duplicating it in subclasses)

**Comment by vanniktech** [comment] 2016-05-27 18:42
Might this get fixed with Dagger 2.5?

**Comment by aoriani** [comment] 2016-09-01 18:38
I still get this issue with 2.6.1

**Comment by vanniktech** [comment] 2016-09-01 18:45
Yup I get it as well

**Comment by ronshapiro** [comment] 2016-09-01 18:54
Would anyone like to send a PR with the proposal @tbroyer made in https://github.com/google/dagger/issues/328#issuecomment-215694029?

**Comment by tbroyer** [comment] 2016-09-02 11:33
@ronshapiro Correct me if I'm wrong but `BasicAnnotationProcessor` from auto-common hides whether we're in the last round or not, so that behavior cannot be added to Dagger without changes to auto-common (e.g. passing a boolean or the `RoundEnvironment` to `postProcess`)

**Comment by ronshapiro** [comment] 2016-09-02 20:50
Could you call `roundEnv.processingOver()` in `postRound(RoundEnv)`?

**Comment by tbroyer** [comment] 2016-09-02 22:13
Oh, hadn't seen the hook had been added. I could use the snapshot then, pending an auto-common 0.7 with the change.

**Comment by tbroyer** [comment] 2016-09-03 10:03
I made the changes in https://github.com/tbroyer/dagger/commit/225039e318fe58244b967ae05e0625a42831f512 (things definitely need to be renamed all over the place; naming is hard, particularly when English is not your native language) but the test still fails. I debugged and it happens that the `Key`s for `test.TestApplication` aren't _equivalent_: the `.remove(binding.key())` doesn't find the previously inserted `Key` (they apparently don't have the same `hashCode`), so the note is still emitted at the end. Are `MoreTypes.TypeEquivalence` supposed to be equivalent across processing rounds to begin with? (they seem to be reused that way in `InjectBindingRegistry.BindingsCollection#materializedBindingKeys`)

**Comment by vanniktech** [comment] 2016-12-17 23:47
@tbroyer how's the progress on this? does the test still fail?

**Comment by tbroyer** [comment] 2016-12-18 08:32
Rebased on latest master at tbroyer@600a865 but still the same error. Auto-common's `TypeEquivalence` apparently computes different hash codes for the `test.TestApplication` in the different rounds.

**Comment by ronshapiro** [comment] 2017-03-21 18:35
This note was turned off by default in 72aa9653252c348e07f79030c49ce921a72ea9e1

**Closed by ronshapiro** 2017-03-21 18:35 UTC
