### ISSUE TITLE
Dagger Application injection NPE

### ISSUE THREAD

**Issue by luispereira** [google/dagger#748] opened 2017-05-23 13:18 UTC
I'm trying to inject some objects on application, in order to access them whenever I want. 
So, on my application I'm doing something like this:

```
private static AppComponent mApplicationComponent;

@Override
    public void onCreate() {
        …
       mApplicationComponent = DaggerAppComponent.builder()
                .appModule(new AppModule(this, new ModuleSpref(this))
                .build();
   }

 public static AppComponent getInstance() {
        return mApplicationComponent;
    }
```

However, according to google crash log of my production app, the application has a NullPointException when trying to access anything from getInstance(). On my application this happens on a service which is only called via a receiver. Additionally, this also happens on another receiver.

```
 MyApplication.getInstance().context(); //Null Point Exception :(
```

Here is my ApplicationComponent:
```
@Component(modules = AppModule.class)
@Singleton
public interface AppComponent {
    void inject(Context context);

    //Exposed to sub-graphs.
    Context context();
    ModuleSpref getSpref();
}
```

I tried many times to replicate, but so far without success, despite the google crash saying otherwise.
Am I doing something wrong here?
As far as I know, for services/receivers to be initialised in android, the application must first be initialised, so getInstance() should not return null right?

**Comment by ronshapiro** [comment] 2017-05-23 19:57
Take a look at [https://google.github.io/dagger/api/latest/dagger/android/DaggerApplication.html](DaggerApplication), which handles this scenario where sometimes a contentprovider.oncreate() is called before the application.oncreate()

**Comment by luispereira** [comment] 2017-05-24 07:30
I can't see the link (404) for me.

**Comment by luispereira** [comment] 2017-05-24 07:33
Also, getInstance() is only called on onReceiver() of broadcast or on startCommand() of service

**Comment by tbroyer** [comment] 2017-05-24 10:00
Ron probably got his markdown mixed up and meant [DaggerApplication](https://google.github.io/dagger/api/latest/dagger/android/DaggerApplication.html)

**Comment by luispereira** [comment] 2017-05-24 10:24
Thanks, so if I undestrood correctly, injecting my objects on a DaggerApplication class will prevent this injection before application.oncreate() right?

**Comment by luispereira** [comment] 2017-05-26 11:56
I'm actually trying to do something about this, 

`public MyApplication extends DaggerApplication implements AndroidInjector<MyApplication>`

When I notice that AndroidInjector only has, broadcast, service, activity, fragment or contentprovider.

So, how should I proceed when overriding the method applicationInjector on application?

```
  @Override
    protected AndroidInjector<? extends DaggerApplication> applicationInjector() {
        return this;
    }
```

Since I'm only injecting this to access it from everywhere, activities, services and broadcasts.

**Comment by matpag** [comment] 2017-06-11 16:38
I'm stucked at the same point, i'm pretty new to Dagger 2 and there is no documentation on how to use the new `DaggerApplication` class

**Comment by luispereira** [comment] 2017-06-26 09:34
As a side note, this NPE on injected instance happens a lot on services from startCommand() and on samsung devices such as S8, S7 and S6

**Comment by ronshapiro** [comment] 2017-09-12 19:50
Github isn't the best forum for this - please use StackOverflow with the `dagger-2` tag instead, as that is a better forum for questions.

**Comment by juliahexen** [comment] 2017-10-11 12:53
@luispereira Did you find any solution for your problem? Same here :/

**Comment by luispereira** [comment] 2017-10-11 13:06
Actually I found a work around for this which implies something like this on your application class:
```
public class MyApplication extends Application {
    private static MyApplication sInstance;
    private AppComponent applicationComponent;

    public MyApplication() {
        sInstance = this;
    } 

    public static AppComponent getInstance() {
        return sInstance.getAppComponent();
    }

    private AppComponent getAppComponent() {
        if (applicationComponent == null) {
            //initialise the dagger stuff here
        }
        return applicationComponent;
    }
}
```

Basically, if by any instance, the dagger app component builder returns null, it will force to initialise again. I know this is far from a perfect solution, but it works.

**Comment by juliahexen** [comment] 2017-10-11 13:58
Thank you very much, I will try it :)

**Comment by fassor** [comment] 2017-10-16 14:29
I am facing this issue as well and I have no idea how to work around it.

```
Caused by: java.lang.RuntimeException: 
  at dagger.android.AndroidInjection.inject (AndroidInjection.java:48)
  at dagger.android.support.DaggerAppCompatActivity.onCreate (DaggerAppCompatActivity.java:43)
  at com.package.MainActivity.onCreate (MainActivity.java:83)
  at android.app.Activity.performCreate (Activity.java:6912)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1126)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2900)
```

This happens only on Android 7.0, mainly on Samsung devices, some Huawai and Motorola devices and a few Xperia devices. I am unable to reproduce it since I do not have any of the affected devices at hand.

It seems this is caused by the application not (yet) being set for the activity, meaning activity's onCreate is called before the activity is actually attached to the application.

Here the affected Dagger code:

https://github.com/google/dagger/blob/e8d7cd4c29c1316c5bb1cf0737d4f29111fcb1c8/java/dagger/android/support/DaggerAppCompatActivity.java#L42-L45

https://github.com/google/dagger/blob/e8d7cd4c29c1316c5bb1cf0737d4f29111fcb1c8/java/dagger/android/AndroidInjection.java#L43-L52

``activity.getApplication()`` returns null, and so the RuntimeException is thrown.

Anyone any suggestions?

**Comment by Zhuinden** [comment] 2017-10-17 13:00
Oh this is the same problem as what Mortar fixes with

    Application app = activity.getApplication();
    if(app == null) {
         app = (Application)activity.getApplicationContext();
    }

**Comment by Zhuinden** [comment] 2017-10-17 13:19
@ronshapiro oh btw this is a bug in Dagger2's Android injection stuff so fix it instead of closing the issue k thx

**Comment by ronshapiro** [comment] 2017-10-17 15:35
@Zhuinden is this what you're referring too: https://github.com/square/mortar/commit/bf74e3e0ad00713c3123b957a61f82bd73b578b5?

Is there any reason to not just call `(Application) activity.getApplicationContext()` here then and not worry about the null-check?

/cc @rjrjr @loganj

**Comment by JakeWharton** [comment] 2017-10-17 16:25
No

**Comment by fassor** [comment] 2017-10-17 17:43
Hi everyone,

I rolled out an update a few hours ago with the change @Zhuinden proposed based on Dagger's DaggerAppCompatActivity and the AndroidInjection class:

```
public abstract class MyDaggerAppCompatActivity extends AppCompatActivity implements HasFragmentInjector, HasSupportFragmentInjector {

    @Inject DispatchingAndroidInjector<Fragment> supportFragmentInjector;
    @Inject DispatchingAndroidInjector<android.app.Fragment> frameworkFragmentInjector;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        inject();
        super.onCreate(savedInstanceState);
    }

    @Override
    public AndroidInjector<Fragment> supportFragmentInjector() {
        return supportFragmentInjector;
    }

    @Override
    public AndroidInjector<android.app.Fragment> fragmentInjector() {
        return frameworkFragmentInjector;
    }

    private void inject() {
        Application application = getApplication();
        if(application == null) {
            application = (Application) getApplicationContext();
        }

        if (!(application instanceof HasActivityInjector)) {
            throw new RuntimeException(String.format("%s does not implement %s", application.getClass().getCanonicalName(), HasActivityInjector.class.getCanonicalName()));
        }

        AndroidInjector<Activity> activityInjector = ((HasActivityInjector) application).activityInjector();
        checkNotNull(activityInjector, "%s.activityInjector() returned null", application.getClass().getCanonicalName());

        activityInjector.inject(this);
    }

}
```

Still getting the RuntimeException, now thrown by my code above. So looks like that either there is an application but the wrong one or even the application context is null. Cannot imagine how any of both scenarios would work actually...

**Comment by fassor** [comment] 2017-10-23 08:49
I tested using `getApplicationContext()` instead of `getApplication()` in all Dagger 2 components I am using (DaggerAppCompatActivity, DaggerIntentService, DaggerFragment) and I can confirm that it does not make any difference. This version is now rolled out to over 300k users and the exception rate is no different to the original version based on unchanged Dagger 2 code.

See also https://stackoverflow.com/questions/46784685/runtimeexception-with-dagger-2-on-android-7-0-and-samsung-devices where I posted some code where I tried to get more understanding of this error without any luck.

**Comment by tbroyer** [comment] 2017-10-23 08:56
See also https://github.com/google/dagger/issues/891

**Comment by fassor** [comment] 2017-10-25 07:05
I solved the issue for myself by not using anymore the DaggerApplication but an Application independent solution described here: https://stackoverflow.com/a/46925736/8788319

Not sure if this is an option for Dagger 2 but I did not find another way to resolve the crashes under Android 7.0 otherwise.

**Comment by abhiroopnray** [comment] 2018-12-14 09:43
Hope you had added application class name in the Android Manifest file. Without it, the app will work but the dagger component will be null.

**Comment by ronshapiro** [comment] 2019-04-03 20:09
I'm still pretty dumbfounded at what is happening here. I wish I had a better suggestion at what we should do.

**Comment by pablobaxter** [comment] 2020-04-09 17:51
One interesting thing to point out is that Android doesn't always run any of the `ContentProvider` classes or the `Application` class listed in the manifest. https://developer.android.com/guide/topics/data/autobackup#ImplementingBackupAgent

Specifically...
![image](https://user-images.githubusercontent.com/12305694/78924938-74df0780-7a4f-11ea-8581-6011e534a3fc.png)

I've tested to see if Services and BroadcastReceivers still ran, and they do. This was causing multiple issues for me with Fabric, Firebase, and Dagger. I figured I'd share my findings here as I referenced this issue to try to fix my dagger problem.

I'm in the process of disabling this auto backup (setting `allowBackup="false"` in the AndroidManifest) for the app I work on to validate my fix. I'll post my findings if it fixes my Dagger issue.

**Comment by camsteffen** [comment] 2020-06-08 23:36
@pablobaxter Any update?

**Comment by pablobaxter** [comment] 2020-06-09 00:10
> @pablobaxter Any update?

@camsteffen Thank you for reminding me! Also sorry... I never did update my result on this thread as promised.

So disabling the backup worked for me. I am no longer seeing my Dagger crash, which in my case was a `ClassCastException` due to `getApplication()` not being an instance of `DaggerApp`, even though I extend it. This also solved one of the other issues I had, which would only ever happen if my extended `Application` class never ran.

I filed a ticket about this with Firebase (https://github.com/firebase/firebase-android-sdk/issues/1456), as this was the main library starting Services and BroadcastReceivers while the app was in this restricted mode. However, this is most likely an Android OS issue. It looks like whenever the app crashes in this restricted mode (in my case due to Firebase starting up), the next launch app (user initiated or otherwise) restarts the app in this restricted mode, which caused a crash, and so on.

Hope this helps!

**Comment by Chang-Eric** [comment] 2020-07-14 23:29
Closing this as I don't think there is much that can be done on the Dagger side. This feels like an Android bug that you can ever be called without the `Application` specified in the manifest.

**Closed by Chang-Eric** 2020-07-14 23:29 UTC

**Comment by camsteffen** [comment] 2020-07-15 17:09
Given the Android docs [quoted](https://github.com/google/dagger/issues/748#issuecomment-611663561) and the SO solution [mentioned](https://github.com/google/dagger/issues/748#issuecomment-339235062), would it make sense for Dagger to provide a solution to work without overriding `Application`?

**Comment by pablobaxter** [comment] 2020-07-15 17:12
As an FYI, I did file a bug with the Android team regarding the backup agent. https://issuetracker.google.com/u/1/issues/160946170

**Comment by Chang-Eric** [comment] 2020-07-15 17:33
@camsteffen if I understand the SO solution, it is just moving the component to a static variable? This would work for the production app, but keeping your DI graph in static state tends to cause problems for things like tests.

**Comment by Zhuinden** [comment] 2020-07-15 22:16
> @camsteffen if I understand the SO solution, it is just moving the component to a static variable? This would work for the production app, but keeping your DI graph in static state tends to cause problems for things like tests.

That's never bothered anyone using Koin, which works exactly the same way.
