### ISSUE TITLE
No Dagger2 generated files for JUnit tests

### ISSUE THREAD

**Issue by westward** [google/dagger#125] opened 2015-02-24 13:18 UTC
A new AndroidStudio 1.1 version introduced the unit testing support. This URL http://tools.android.com/tech-docs/unit-testing-support provides step-by-step instruction how to setup IDE to run JUnit tests for Android project.

android-apt plugin by Hugo Visser works nice in assisting of creation Dagger2 generated files for usual Android code but unfortunately there is no generated files for any JUnit test class. I tried to configure dependency like androidTestApt 'com.google.dagger:dagger-compiler:2.0-SNAPSHOT' (and tried to specify 'testCompile' and 'provided' too) according to android-apt plugin documentation but without success.

I think the problem is in different sources directory for Unit tests - it's src/test/java instead of src/androidTest/java that used by android instrumentation tests.

Can you please provide any help how to resolve this trouble? I can't understand where is the problem: in the wrong project configuration, a bug in new Android Studio's JUnit tests feature, something wrong in Dagger2 or in android-apt plugin. When needed, I can provide the simple AndroidStudio project to reproduce the trouble.

Thanks in advance.

**Comment by stephanenicolas** [comment] 2015-02-27 23:30
For me it works when adding dagger 2 with both apt and testCompile scopes. 

BTW, it would be great if we could have an example of testing with Dagger 2. It's not obvious at all to figure out how module can be overiden.

**Comment by westward** [comment] 2015-02-27 23:32
Can you please provide an example project? I tried to add dagger compiler as a testCompile dependency but without success.

**Comment by twelve17** [comment] 2015-03-03 13:43
I'm also running into this issue.  An example project or a few pointers would be helpful.  Thanks!

**Comment by sockeqwe** [comment] 2015-03-20 08:16
That `build.gradle` script works for me [https://bitbucket.org/hvisser/android-apt](with android apt plugin):

```groovy
dependencies {
    apt 'com.google.dagger:dagger-compiler:2.0-SNAPSHOT'
    compile 'com.google.dagger:dagger:2.0-SNAPSHOT

    // Additional for unit tests
    testProvided 'com.google.dagger:dagger-compiler:2.0-SNAPSHOT'
}
```

**Comment by westward** [comment] 2015-03-20 22:14
Can you please provide an example project? I would like to see the whole project configuration related to JUnit tests.

**Comment by cgruber** [comment] 2015-03-26 00:20
Our recommendation for Android Studio is to use https://bitbucket.org/hvisser/android-apt as described above.  I'm going to close this.  If you are still encountering it when using the apt plugin, and after updating all dependencies, please re-open this, but point to either a github repo with an example project, or a gist containing a failing test, or something so we can reproduce this.

**Closed by cgruber** 2015-03-26 00:20 UTC

**Comment by westward** [comment] 2015-03-26 10:24
Here is the AndroidStudio example project: https://github.com/westward/Dagger2Test
It contains the single JUnit file named DummyControllerTest.java with code that should create a Component. I tried "testProvided", "testCompile" directives in build.gradle, both variants witout success. 
Thanks!

**Comment by stephanenicolas** [comment] 2015-03-26 13:20
@cgruber why use android apt plugin ? Gradle and Android Studio are supposed to have annotation processor support out of the box, no ?

**Comment by tbroyer** [comment] 2015-03-26 14:06
@stephanenicolas `javac` does annotation processing out of the box (unless told otherwise) by looking for processors in the classpath. So in that sense, yes, Gradle supports annotation processing out of the box. But Gradle is missing one thing: dependencies that you need when compiling but not at runtime (such as annotation processors; you don't want to package them into your application). Additionally, ideally, you'd want to be explicit about your processorpath, rather than just put annotation processors in the classpath: the processorpath is usually much smaller than the classpath so processor discovery is faster, but more importantly you know you're not bringing in an annotation processor that you didn't mean to use (for example, antlr' includes its own annotation processor: https://github.com/antlr/antlr4/issues/487)

So you want an `apt` (or whatever its name) `configuration` that ends up filling `javac`'s `-processorpath`, independently of the classpath. `android-apt` does just that, for Android builds.

**Comment by JakeWharton** [comment] 2015-03-26 15:47
And it also makes the generated sources visible to the IDE automatically.

**Comment by westward** [comment] 2015-03-27 08:35
OK guys, what's wrong with my example project? What I've missing? I can't use Dagger2 in tests, I didn't configured project well, something else? Any advice or hint please!
