### ISSUE TITLE
How to read and understand the error messages 

### ISSUE THREAD

**Issue by sarimmehdi** [google/dagger#3697] opened 2023-01-08 22:13 UTC
I am in a strange situation where hilt injection works fine in the production app but not when I a running the Instrumented test. I want to understand how to debug the issue but the error messages don't really make it clear where the problem lies. Here is an example:

```
/home/sarimmehdi/project/feature_splash/splash_presentation/build/generated/hilt/component_sources/debugAndroidTest/dagger/hilt/android/internal/testing/root/Default_HiltComponents.java:140: error: [Dagger/MissingBinding] com.project.login_domain.repository.UserRepository cannot be provided without an @Provides-annotated method.
  public abstract static class SingletonC implements SplashScreenFragmentTest_GeneratedInjector,
                         ^
      com.project.login_domain.repository.UserRepository is injected at
          com.project.splash_domain.di.SplashDomainModule.provideSplashScreenUseCases(userRepository, …)
      com.project.splash_domain.usecase.screen.SplashScreenUseCases is injected at
          com.project.splash_presentation.fragment.SplashScreenViewModel(splashScreenUseCases)
      com.project.splash_presentation.fragment.SplashScreenViewModel is injected at
          com.project.splash_presentation.fragment.SplashScreenViewModel_HiltModules.BindsModule.binds(arg0)
      @dagger.hilt.android.internal.lifecycle.HiltViewModelMap java.util.Map<java.lang.String,javax.inject.Provider<androidx.lifecycle.ViewModel>> is requested at
          dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.ViewModelFactoriesEntryPoint.getHiltViewModelMap() [dagger.hilt.android.internal.testing.root.Default_HiltComponents.SingletonC → dagger.hilt.android.internal.testing.root.Default_HiltComponents.ActivityRetainedC → dagger.hilt.android.internal.testing.root.Default_HiltComponents.ViewModelC]
  It is also requested at:
      com.project.login_domain.di.LoginDomainModule.provideLoginScreenUseCases(userRepository, …)
```
What I understand from the above is that my UserRepository (which is an interface) is not being provided and that I should probably add a @Provides annotation. However, this is incorrect as I am indeed doing that.

```
@Module
@InstallIn(ViewModelComponent::class)
object LoginDataModule {

    @Provides
    @ViewModelScoped
    fun provideOkHttpClient(): OkHttpClient {
        val logger = HttpLoggingInterceptor()
        logger.setLevel(HttpLoggingInterceptor.Level.BODY)
        return OkHttpClient
            .Builder()
            .addInterceptor(logger)
            .build()
    }

    @Provides
    @ViewModelScoped
    fun provideMicrodronesApi(okHttpClient: OkHttpClient): Api {
        return Retrofit.Builder()
            .baseUrl(Api.BASE_URL)
            .addConverterFactory(MoshiConverterFactory.create())
            .client(okHttpClient)
            .build()
            .create(Api::class.java)
    }

    @Provides
    @ViewModelScoped
    @Named(UserRepositoryImpl.USER_SHARED_PREFERENCES)
    fun provideSharedPreferences(@ApplicationContext context: Context): SharedPreferences {
        return context.getSharedPreferences(UserRepositoryImpl.USER_SHARED_PREFERENCES, Context.MODE_PRIVATE)
    }

    @Provides
    @ViewModelScoped
    fun provideUserRepository(
        api: Api,
        @Named(UserRepositoryImpl.USER_SHARED_PREFERENCES) sharedPreferences: SharedPreferences
    ): UserRepository {
        return UserRepositoryImpl(api, sharedPreferences)
    }
}

@Module
@TestInstallIn(
    components = [ViewModelComponent::class],
    replaces = [LoginDataModule::class]
)
object TestLoginDataModule {

    @Provides
    @ViewModelScoped
    fun provideUserRepository(): UserRepository {
        return UserRepositoryTest()
    }
}
```
I then clicked on the very first line in the error message and got taken to Default_HiltComponents.java where I was brought to this part immediately by the IDE:

```
  @Singleton
  public abstract static class SingletonC implements SplashScreenFragmentTest_GeneratedInjector,
      FragmentGetContextFix.FragmentGetContextFixEntryPoint,
      HiltWrapper_ActivityRetainedComponentManager_ActivityRetainedComponentBuilderEntryPoint,
      ServiceComponentManager.ServiceComponentBuilderEntryPoint,
      SingletonComponent,
      TestSingletonComponent {
  }
```
This means that my SplashScreenFragmentTest is being annotated as a Singleton but all my dependencies are annotated and scoped to a ViewModel. Here is my SplashScreenFragmentTest:

```
@HiltAndroidTest
class SplashScreenFragmentTest {

    @get:Rule
    var hiltRule = HiltAndroidRule(this)

    @Before
    fun setup() {

        hiltRule.inject()
    }

    @OptIn(ExperimentalCoroutinesApi::class)
    @Test
    fun splashScreenExitsToLoginScreenAfter3Seconds() {
        launchFragmentInHiltContainer<SplashScreenFragment> {

        }
    }
}
```
But, I have another dependency that is scoped to a Fragment and it is being injected just fine:

```
@Module
@InstallIn(FragmentComponent::class)
object CoreUiModule {

    @Provides
    @FragmentScoped
    fun provideSplashTimer(): SplashTimer {
        return ActualSplashTimer()
    }

    @Provides
    @FragmentScoped
    fun provideMicrodronesFragmentFactory(
        providerMap: Map<Class<out Fragment>, @JvmSuppressWildcards Provider<Fragment>>
    ): MicrodronesFragmentFactory {
        return MicrodronesFragmentFactory(providerMap)
    }
}

@Module
@TestInstallIn(
    components = [FragmentComponent::class],
    replaces = [CoreUiModule::class]
)
object TestCoreUiModule {

    @Provides
    @FragmentScoped
    fun provideSplashTimer(): SplashTimer {
        return TestSplashTimer()
    }
}
```
For further context, here is my SplashScreenViewModel:

```
@HiltViewModel
class SplashScreenViewModel @Inject constructor(
    private val splashScreenUseCases: SplashScreenUseCases
): ViewModel() {
}
```
Can anyone explain this discrepancy to me?

**Comment by bcorso** [comment] 2023-01-09 21:02
> ```
> [Dagger/MissingBinding] com.project.login_domain.repository.UserRepository cannot be provided 
> without an @Provides annotated method.
> ```

Hi @sarimmehdi, if `@InstallIn`/`@TestInstallIn` modules from a transitive dependency are missing in a test it likely means that the generated metadata for the modules were not properly piped through to the given test compilation. This is generally the responsibility of the Hilt Gradle plugin. 

First, can you verify that all of your Gradle modules applies the [Hilt Gradle plugin](https://dagger.dev/hilt/gradle-setup#hilt-gradle-plugin)? 

If that's all fine, then it may be a bug in the Hilt Gradle plugin itself. Would it be possible for you to provide a minimal reproducible example so that we can reproduce the behavior on our side?

**Comment by sarimmehdi** [comment] 2023-01-10 08:28
@bcorso I have added you to the repository. The culprit test is called SplashScreenFragmentTest.kt

Please have a look at it whenever you find the time

**Comment by bcorso** [comment] 2023-01-10 18:13
@sarimmehdi thanks I was able to reproduce the issue. I'm still looking into this, but as a workaround you can add the modules as direct dependencies to `:splash_presentation`, e.g.

```
    implementation project(path: ':feature_login:login_data')
    implementation project(path: ':feature_onboarding:onboarding_data')
```

**Comment by bcorso** [comment] 2023-01-10 21:49
So I finished looking into this and it looks like this is working as intended from the Hilt side. The issue is that `:feature_splash:splash_presentation` doesn't have a direct or transitive dependency to the `login_data` or `onboarding_data` Gradle modules, so there's no way for Hilt to know about them. The Gradle dependency graph is shown below (ignoring the core Gradle modules):

<img width="1781" alt="Dot graph of Gradle module dependencies" src="https://user-images.githubusercontent.com/2928034/211667728-eea09393-c01a-4b0c-9926-dd1e18f072fb.png">

There's a couple ways you could solve this.

**Option 1.** Merge your "domain" and "data" Gradle modules into a single Gradle module so that anything that depends on the `UserRepository` automatically gets the prod and test implementation bundled with the interface


**Option 2.** If you only want to expose the modules to the test, use the suggestion in https://github.com/google/dagger/issues/3697#issuecomment-1377660570 to add a direct dependency on the modules.

I'm going to close this issue, but feel free to ask if you have any other questions.

**Closed by bcorso** 2023-01-10 21:49 UTC

**Comment by sarimmehdi** [comment] 2023-01-11 19:39
@bcorso thanks for your answer but that still doesn't explain why my current setup works fine in the prod version. Is there something about transitive dependencies that prevent them from working in a test scenario with hilt?

**Comment by bcorso** [comment] 2023-01-11 20:53
@sarimmehdi It works in your prod version because you have already added the `: login_data` and `:onboarding_data` dependencies to `:app`.

**Comment by sarimmehdi** [comment] 2023-01-11 21:03
Ah yes, you're right. That definitely makes a lot of sense! Thanks for clearing that up!
