### ISSUE TITLE
after add hilt { enableAggregatingTask = true } dependencies tasks faild

### ISSUE THREAD

**Issue by cquin89** [google/dagger#2787] opened 2021-07-27 15:49 UTC
when I add the line hilt { enableAggregatingTask = true} error (Execution failed for task ':app:dependencies) happend

>Execution failed for task ':app:dependencies'.
Cannot change dependencies of dependency configuration ':app:hmsDebugAndroidTestRuntimeClasspath' after it has been included in dependency resolution. Use 'defaultDependencies' instead of 'beforeResolve' to specify default dependencies for a configuration.

The task fails when I add a flavor that starts with a letter greater than g

Example:
>flavorDimensions "version"
productFlavors{
hms{
dimension "version"
}
gms{
dimension "version"
}
}

**Comment by uhooi** [comment] 2021-08-11 00:23
I had the same build error.  
https://github.com/uhooi/UhooiPicBook-Android/runs/3291487872?check_suite_focus=true

```shell
> Task :app:getDependencies FAILED

1 actionable task: 1 executed
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:getDependencies'.
> Cannot change dependencies of dependency configuration ':app:productionDebugAndroidTestRuntimeClasspath' after it has been included in dependency resolution. Use 'defaultDependencies' instead of 'beforeResolve' to specify default dependencies for a configuration.
```

After removing the `production` flavor, the build was successful.  
https://github.com/uhooi/UhooiPicBook-Android/runs/3295567631?check_suite_focus=true

```diff
android {
    flavorDimensions 'environment'
    productFlavors {
-       production {
-           dimension 'environment'
-       }
        develop {
            dimension 'environment'
            applicationIdSuffix '.develop'
            versionNameSuffix '-develop'
        }
    }
}
```

But the `production` flavor is required, so `enableAggregatingTask` flag cannot be added now.

**Comment by danysantiago** [comment] 2021-08-11 00:43
Thanks for the repro project, I'll take a look at this soon.

**Comment by danysantiago** [comment] 2021-08-11 00:47
By the way, I think this is a dupe of https://github.com/google/dagger/issues/2744, but need to look deeper.

**Comment by danysantiago** [comment] 2021-08-18 17:02
Definitely a dupe of https://github.com/google/dagger/issues/2744, closing as dupe.

**Closed by danysantiago** 2021-08-18 17:02 UTC
Labels: P2, needs investigation, area: hilt
