### ISSUE TITLE
Public website talks about unreleased feature

### ISSUE THREAD

**Issue by benjaminplee** [google/dagger#694] opened 2017-04-13 01:28 UTC
The dagger website, https://google.github.io/dagger/android.html, mentions a nice convenience method for new the dagger.android features to simply setup for most users but this isn't in the latest 2.10 release.  @ronshapiro what is the status of the work with the ContributesAndroidInjector annotation?  It looks to be on master only.

> Pro-tip: If your subcomponent and its builder have no other methods or supertypes than the ones mentioned in step #2, you can use @ContributesAndroidInjector to generate them for you. Instead of steps 2 and 3, add an abstract module method that returns your activity, annotate it with @ContributesAndroidInjector, and specify the modules you want to install into the subcomponent. If the subcomponent needs scopes, apply the scope annotations to the method as well.

I would really like this feature as we have a good set of base architecture using an older dagger2 version setup for our last app which was good at reducing boilerplate for new activity setup, but had some other deficiencies.

**Is there a Dagger roadmap for v2.11 (or future) where this is planned or anything I can do to help get this ready for prime time?**

_Issue #691 makes this unfortunate since quick testing with the current snapshot is missing._  Also, FYI, there are some 404s on the Javadocs referenced for that page for version "latest" too.

**Comment by JakeWharton** [comment] 2017-04-13 01:32
This is effectively a dupe of https://github.com/google/dagger/issues/581 and is because of how the sync works (see https://github.com/google/dagger/issues/581#issuecomment-280064012)

**Comment by ronshapiro** [comment] 2017-04-13 01:39
Should be released by the end of the week

**Closed by ronshapiro** 2017-04-13 01:39 UTC

**Comment by benjaminplee** [comment] 2017-04-13 02:14
@JakeWharton Good catch.  My search missed that.

**Comment by JakeWharton** [comment] 2017-04-13 02:19
I only knew it existed because I follow all the issues. Took a few searches
to find!
