### ISSUE TITLE
Run all tests under ecj

### ISSUE THREAD

**Issue by autonomousapps** [google/dagger#483] opened 2016-10-27 05:41 UTC
Here's the exact error:

```
ERROR: /workspace/ReactiveStopwatch/app/build/generated/source/apt/androidTest/debug/com/autonomousapps/reactivestopwatch/di/DaggerTestStopwatchComponent.java:74: The method create(Provider<Stopwatch>, Provider<Scheduler>) in the type StopwatchService_MembersInjector is not applicable for the arguments (Provider<Scheduler>, Provider<Stopwatch>)
```

This is bizarre. Why would the arguments be out of order? I should note that they're _not_ out of order for `DaggerStopwatchComponent` (in other words, it's only affecting the test component in the `androidTest` source set).

**To reproduce**

This issue should be easy to reproduce. Clone my repo and checkout the commit [here](https://bitbucket.org/tonyrobalik/reactivestopwatch/commits/f3a66ac47d36823b91f845fb1162dacdb223c1ab). Run the command `./gradlew clean sanityCheck` (which compiles everything).

**Comment by ronshapiro** [comment] 2016-10-27 15:01
My best guess is this is a a `jack` issue with elements ordering, since `jack` is based off of `ecj`. I'll try to reproduce.

**Comment by autonomousapps** [comment] 2016-10-27 15:03
It wouldn't be the first (or second, or third) time I've ran into a Jack issue on this project. Google should be paying me for beta testing it, at this point.

Thanks.

**Comment by ronshapiro** [comment] 2016-10-27 15:08
I'm not sure it's an issue with `jack` or the fact that Dagger assumes `javac` since all of our tests are run in a `javac` environment.

**Comment by gabrielittner** [comment] 2016-10-27 15:10
Could it be related to this https://github.com/google/auto/issues/372 ?

**Comment by ronshapiro** [comment] 2016-10-27 15:16
@gabrielittner I believe so

**Comment by autonomousapps** [comment] 2016-10-28 22:02
So, is there anything to be done? That issue is marked as closed, but I still experience problems, as this issue demonstrates.

**Comment by ronshapiro** [comment] 2016-10-29 23:47
Its not the same issue, but it has a similar culprit I believe. Do you want to take a look at trying to figure out where in the Dagger code this might be getting confused?

**Comment by autonomousapps** [comment] 2016-10-30 23:48
Sure, that would be interesting. I don't have any experience with code generation libraries - could you provide me a pointer as far as a class or package that would be a good place to start?

**Comment by autonomousapps** [comment] 2016-11-21 04:45
Finally found some time to look through the dagger source. Forked and ran `mvn test`. Everything passes, of course. That said, I just ran a global search through project files for the string `create(Provider<`. Found 12 occurrence total. 2 in examples, 10 in tests. Not one of them contemplates a `create()` method with more than one `Provider<>`. This seems significant.

Just posting some notes as I investigate the issue.

**Comment by autonomousapps** [comment] 2017-03-21 18:59
I'm wondering how relevant this ticket is now that Google has announced that they're moving away from Jack and towards native Java 8 support with javac on the Android platform?

**Comment by ronshapiro** [comment] 2017-03-21 19:02
Eclipse is still a very popular compiler and we should make sure we support it.

**Comment by Chang-Eric** [comment] 2021-02-02 23:54
Since it sounds like most of the issues were issues dealing with Jack and there haven't been recent occurrences, I'm going to close this issue for now. While we do support Eclipse, I'm not sure it is worth it at this time to set up a separate mode of tests to use it. We are still of course willing to fix issues that come up with the Eclipse compiler.

**Closed by Chang-Eric** 2021-02-02 23:54 UTC
