### ISSUE TITLE
Are the examples updated to Dagger 2 ?

### ISSUE THREAD

**Issue by AntonioCappiello** [google/dagger#270] opened 2015-12-05 11:50 UTC
The readme file of the examples says:
> _Note: The app is in transition to Dagger 2 and may not reflect recommended patterns.  Before
 we release Dagger 2.0 it will, but until this note is removed, please do not rely on this
> example as a strong recommendation._

However Dagger 2 has been released since a while, so I was wondering whether the examples are updated and the readme file is not or none of the two is updated. Does anybody knows?

**Comment by cgruber** [comment] 2015-12-05 20:10
The examples are valid dagger 2, but as trivial samples they are not
necessarily recommended practice.  That said, we are refreshing the
documentation and it is reasonable to refresh these samples.

**Comment by ronshapiro** [comment] 2016-08-09 21:27
I believe there's another issue which is a duplicate of this.

**Closed by ronshapiro** 2016-08-09 21:27 UTC
Labels: area: examples, status: accepted, type: enhancement
