### ISSUE TITLE
Generated supertypeInjector is null

### ISSUE THREAD

**Issue by tonyshkurenko** [google/dagger#243] opened 2015-10-17 15:49 UTC
I posted this: http://stackoverflow.com/questions/33185968/dagger-2-supertypeinjector-is-null

But my researches brought me to this:

Going up and up, to find where supertypeInjector has to be initialized I found this method in `DaggerAppComponent` (watch `abstractRestClientActivityMembersInjector`, exactly this object will be supertypeInjector)
```
private void initialize() {  
      this.provideCallbackManagerProvider = ScopedProvider.create(LogInModule_ProvideCallbackManagerFactory.create(logInModule));
      this.authActivityMembersInjector = AuthActivity_MembersInjector.create(abstractRestClientActivityMembersInjector, DaggerAppComponent.this.provideTokenUtilsProvider, provideCallbackManagerProvider);
      this.abstractRestClientActivityMembersInjector = AbstractRestClientActivity_MembersInjector.create((MembersInjector) MembersInjectors.noOp(), DaggerAppComponent.this.provideApiServiceProvider);
    }
```

Seems like `abstractRestClientActivityMembersInjector` is used in 2nd line of this method, but is inited in third. This is the one place, where it inits, obviously it's `null`, when we try to use it in second line.

**Comment by tbroyer** [comment] 2015-10-17 15:53
Dupe of #214

**Closed** 2015-12-10 19:29 UTC
Labels: status: duplicate
