### ISSUE TITLE
[Hilt] Multiple viewmodel instances with different keys crash

### ISSUE THREAD

**Issue by chpetersen** [google/dagger#2328] opened 2021-01-28 10:22 UTC
Hello

I have recently swapped to Hilt. Before we used dagger and had the following code which would allow us to have multiple instance of the same viewmodel, but with different keys:
```kotlin
fun <T : ViewModel> getUniqueViewModel(modelClass: Class<T>, key: String): T {
    val viewModel = ViewModelProvider.get(key, modelClass)
    return viewModel
}
```

Example of use:
```kotlin
val firstViewModel = getUniqueViewModel(TestViewModel.class, "key1")
val secondViewModel = getUniqueViewModel(TestViewModel.class, "key2")
```

But when I'm using Hilt I get the following error when I try to get my second instance:
```
java.lang.IllegalArgumentException: SavedStateProvider with the given key is already registered
        at androidx.savedstate.SavedStateRegistry.registerSavedStateProvider(SavedStateRegistry.java:111)
        at androidx.lifecycle.SavedStateHandleController.attachToLifecycle(SavedStateHandleController.java:50)
        at androidx.lifecycle.SavedStateHandleController.create(SavedStateHandleController.java:70)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:67)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:84)
        at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:108)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
        at com.test.BaseActivity.getUniqueViewModel(BaseActivity.kt:162)
```

Doesn't Hilt allow multiple viewModels with different keys?

**Comment by frett** [comment] 2021-01-28 16:36
I've run into the same issue when switching from the AndroidX hilt-lifecycle-viewmodel to the dagger hilt view model.

I believe the core of the issue is that `HiltViewModelFactory` implements `ViewModelProvider.Factory` and doesn't extend `ViewModelProvider.KeyedFactory` which provides support for defining custom keys for ViewModels.

**Comment by danysantiago** [comment] 2021-01-28 17:08
Yup - Part of the problem is that [`ViewModelProvider.KeyedFactory`](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:lifecycle/lifecycle-viewmodel/src/main/java/androidx/lifecycle/ViewModelProvider.java;l=65) is not a public API in `androidx.lifecycle` so we can't make `HiltViewModelFactory` a keyed factory so that the [`ViewModelProvider` propagates the key](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:lifecycle/lifecycle-viewmodel/src/main/java/androidx/lifecycle/ViewModelProvider.java;l=184).

We are working on a long term solution to have ['extras' be propagated via `ViewModelProvider`](https://android-review.googlesource.com/c/platform/frameworks/support/+/1535760) such that during ViewModel creation you get access to the `SavedStateRegistryOwner`, `Application` and ViewModel keys if available instead of having to create custom factories with tight inheritance.

Sadly, I don't have a workaround recommendation for this issue, I can only say to make distinct ViewModel classes with a shared parent since the ViewModel class is the key used.

We could try to make `HiltViewModelFactory` extend [`AbstractSavedStateViewModelFactory`](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:lifecycle/lifecycle-viewmodel-savedstate/src/main/java/androidx/lifecycle/AbstractSavedStateViewModelFactory.java) like it was in the `androidx.hilt` package but that has its own set of problems, specifically it eagerly creates a `SavedStateHandle` that might be thrown out if your ViewModel does not use it and it might cause conflicting key issues too when the ViewModel is not Hilt injected and is just a vanilla ViewModel.

**Comment by frett** [comment] 2021-01-28 18:10
in my current use-case distinct ViewModels won't work, I'm currently using the ViewModel framework to load additional complex data about individual items in a recycler view. Each item gets its own distinct instance of the ViewModel and the key is based off the unique id of the recycler view item.

I'll probably just rework my use-case to store all the individual item ViewModels in a single parent ViewModel when I have a chance, until then I'll hold off on upgrading

**Comment by Zhuinden** [comment] 2021-01-28 21:09
> Doesn't Hilt allow multiple viewModels with different keys?

This isn't actually a Hilt issue. If you weren't using AbstractSavedStateViewModelFactory, only one of your ViewModels would be stored in the store, because the default key in the ViewModelStore is the canonical name of the ViewModel.

IIRC the code says "//TODO: log a warning".

https://android.googlesource.com/platform/frameworks/support/+/androidx-main/lifecycle/lifecycle-viewmodel/src/main/java/androidx/lifecycle/ViewModelProvider.java#181

Therefore

If you directly retrieve `HiltViewModelFactory` through injection or an entry point accessor from either Activity or Fragment level (or the new Hilt-navigation method they added for NavBackStackEntry), then you can use `ViewModelProvider(this, hiltViewModelProviderFactory).get("viewModel1", MyViewModel::class.java)` and `ViewModelProvider(this, hiltViewModelProviderFactory).get("viewModel2", MyViewModel::class.java)`

https://github.com/google/dagger/blob/b5990a0641a7860b760aa9055b90a99d06186af6/java/dagger/hilt/android/lifecycle/HiltViewModelFactory.java#L46

**Comment by frett** [comment] 2021-01-28 21:38
> So try `ViewModelProvider(this, hiltViewModelFactory).get("viewModel1", MyViewModel::class.java)` and `ViewModelProvider(this, hiltViewModelFactory).get("viewModel2", MyViewModel::class.java)`

This is the problem this issue is surfacing, using that method call with 2 different keys but the same ViewModel class doesn't work with the current hilt ViewModel support because it is implementing `ViewModelProvider.Factory` and is not a descendant of `KeyedFactory`.

**Comment by Zhuinden** [comment] 2021-01-28 21:46
Oh.... It stopped being an AbstractSavedStateViewModelFactory. 

Yeah, I'd consider that a Hilt issue. 🤔

**Comment by chpetersen** [comment] 2021-01-29 07:48
> So try ViewModelProvider(this, hiltViewModelFactory).get("viewModel1", MyViewModel::class.java) and ViewModelProvider(this, hiltViewModelFactory).get("viewModel2", MyViewModel::class.java)

I have tried several different ViewModelFactories, including the `hiltViewModelFactory`.
But as @danysantiago mention, non of them is a `KeyedFactory`, so the `key` parameter is never passed to the factory.

**Comment by Chang-Eric** [comment] 2021-02-02 23:45
Just a quick summary, we are working on fixing this, but unfortunately just switching back to AbstractSavedStateViewModelFactory will not work due to injection timing issues and the SavedStateHandle. As @danysantiago mentioned above, we're looking at some long term solutions like that in https://android-review.googlesource.com/c/platform/frameworks/support/+/1535760. Unfortunately, until then, HiltViewModels will not be able to support multiple keys.

**Comment by lijiang-hotstar** [comment] 2021-07-16 07:59
Any update about this issue?

**Comment by theapache64** [comment] 2021-08-13 18:48
Any updates on this?

**Comment by ammargitham** [comment] 2021-10-30 08:10
Seems the changes linked in https://github.com/google/dagger/issues/2328#issuecomment-772093299 has been fixed in https://issuetracker.google.com/issues/188541057. But it seems that it hasn't been released yet.

**Comment by kennir** [comment] 2021-12-13 13:39
Multi-instance is a very important feature for some type of project, Hope it can be fixed soon

Thanks

**Comment by JuanchiFraga** [comment] 2021-12-27 13:24
Any new about this issue?

**Comment by SecretA** [comment] 2022-03-08 00:21
Any updates? We really need this.

**Comment by dzzchao** [comment] 2022-03-10 12:32
We fixed this in the latest app version, but it's not the right way to do it, if anyone is suffering from online crashes, try to use our approach.

```
override fun onStart() {
    val deleteKeys: List<String?> = arrayListOf<String?>(
       XXViewModel::class.java.canonicalName,
    )
    for (key in deleteKeys) {
        key?.let {
            savedStateRegistry.unregisterSavedStateProvider(key)
        }
    }
    super.onStart()
}

```

**Comment by Chang-Eric** [comment] 2022-03-10 22:59
The CreationExtras change that we need for this is unfortunately still in alpha https://developer.android.com/jetpack/androidx/releases/lifecycle#2.5.0-alpha01. Once that is stable, I think we can update Hilt's ViewModelFactory to pass through CreationExtras and then I think it would just work since the key is now derived from that instead of via that `KeyedFactory` interface mentioned in above comments.

**Comment by originx** [comment] 2022-05-06 13:53
androidx.lifecycle  moved to beta: Version 2.5.0-beta01  🥳, meaning the API is now stable enough to proceed with this?

**Comment by sbatezat** [comment] 2022-05-13 07:48
androidx.lifecycle moved to beta: Version 2.5.0-rc01 now, stable enough to proceed with this?

**Comment by tommyzat** [comment] 2022-06-30 18:41
Lifecycle hit 2.5.0 stable!

**Comment by Zhuinden** [comment] 2022-07-03 06:32
Yes, it should now be possible.

**Comment by antwangorillas** [comment] 2022-07-06 15:07
any update on this ?
Thanks

**Comment by Tgo1014** [comment] 2022-07-11 21:58
Also waiting for this much needed feature

**Comment by qiuzaiming** [comment] 2022-07-15 03:22
I have updated to the latest version 2.5.0, but this problem still exists.

**Comment by Chang-Eric** [comment] 2022-07-15 17:18
Just upgrading to 2.5.0 isn't enough, it requires a change on the Hilt side. I have a PR to do that, but it has been delayed due to various dependency issues that need sorting out. We're aiming to get it submitted and then do a release next week, assuming no other issues come up.

**Comment by Chang-Eric** [comment] 2022-07-18 21:28
Forgot to tag this issue in https://github.com/google/dagger/commit/74ea7653a2a51ccb7246066c548184ce1e899045, but that commit should fix this issue.

**Comment by sebaslogen** [comment] 2022-07-21 20:55
And the fix is released 🎉 https://github.com/google/dagger/releases/tag/dagger-2.43
According to the release description, it fixes this issue. I'll test it tomorrow on my library.

**Comment by tommyzat** [comment] 2022-07-23 01:13
What is the standard then for initiating viewmodels with keys?

**Comment by sebaslogen** [comment] 2022-07-23 13:08
> What is the standard then for initiating hiltViewModels() with keys?

Until Hilt provides an API to use the key explicitly, you easily create one yourself using the `viewModel(key = "myKey", factory = hiltFactory)` ([new API with creation extras](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:lifecycle/lifecycle-viewmodel-compose/src/main/java/androidx/lifecycle/viewmodel/compose/ViewModel.kt;l=80)) and create an instance of the Hilt factory [like this.](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:hilt/hilt-navigation-compose/src/main/java/androidx/hilt/navigation/compose/HiltViewModel.kt;l=53)

FYI: I tested this in my own library and it works like a charm https://github.com/sebaslogen/resaca/blob/main/resacahilt/src/main/java/com/sebaslogen/resaca/hilt/ScopedMemoizers.kt#L57

**Closed** 2022-07-26 18:13 UTC
Labels: type: bug, P2, area: hilt

**Comment by tommyzat** [comment] 2022-08-24 05:12
> > What is the standard then for initiating hiltViewModels() with keys?
> 
> Until Hilt provides an API to use the key explicitly, you easily create one yourself using the `viewModel(key = "myKey", factory = hiltFactory)` ([new API with creation extras](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:lifecycle/lifecycle-viewmodel-compose/src/main/java/androidx/lifecycle/viewmodel/compose/ViewModel.kt;l=80)) and create an instance of the Hilt factory [like this.](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:hilt/hilt-navigation-compose/src/main/java/androidx/hilt/navigation/compose/HiltViewModel.kt;l=53)
> 
> FYI: I tested this in my own library and it works like a charm https://github.com/sebaslogen/resaca/blob/main/resacahilt/src/main/java/com/sebaslogen/resaca/hilt/ScopedMemoizers.kt#L57

Thank you for this - I tried it and it seems that only variables are scoped, while running coroutines on viewmodelscope are not. How can I fix this?

**Comment by sebaslogen** [comment] 2022-08-25 13:42
> > > What is the standard then for initiating hiltViewModels() with keys?
> > 
> 
> Thank you for this - I tried your library and it seems that only variables are scoped, while running coroutines on viewmodelscope are not. How can I fix this?

@tommyzat I'm not sure I fully understand your question correctly, but if it's about my library (https://github.com/sebaslogen/resaca) it's better to move the discussion out of this Hilt/Dagger issue. You can either open an issue on the Resaca GitHub space or contact me on Twitter @sebaslogen

**Comment by ondrej-111** [comment] 2023-04-25 12:17
> What is the standard then for initiating hiltViewModels() with keys?

now you can basically create fun:
```kotlin
import androidx.compose.runtime.Composable
import androidx.compose.ui.platform.LocalContext
import androidx.hilt.navigation.HiltViewModelFactory
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewmodel.compose.LocalViewModelStoreOwner
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.navigation.NavBackStackEntry

@Composable
inline fun <reified VM : ViewModel> hiltViewModel(key: String): VM {
    val viewModelStoreOwner =
        if (checkNotNull(LocalViewModelStoreOwner.current) is NavBackStackEntry) {
            checkNotNull(LocalViewModelStoreOwner.current) { "ViewModelStoreOwner is null" }
        } else null

    return viewModel(
        key = key,
        factory = if (viewModelStoreOwner is NavBackStackEntry) {
            HiltViewModelFactory(
                LocalContext.current,
                viewModelStoreOwner
            )
        } else null
    )
}
```

and then usage like:
```kotlin
yourComposableWithViewModelArg(
            viewModel = hiltViewModel(key = "MyUniqueViewModelKey"),
```

**Comment by k4dima** [comment] 2023-06-10 22:34
> > What is the standard then for initiating hiltViewModels() with keys?
> 
> now you can basically create fun:
> 
> ```kotlin
> import androidx.compose.runtime.Composable
> import androidx.compose.ui.platform.LocalContext
> import androidx.hilt.navigation.HiltViewModelFactory
> import androidx.lifecycle.ViewModel
> import androidx.lifecycle.viewmodel.compose.LocalViewModelStoreOwner
> import androidx.lifecycle.viewmodel.compose.viewModel
> import androidx.navigation.NavBackStackEntry
> 
> @Composable
> inline fun <reified VM : ViewModel> hiltViewModel(key: String): VM {
>     val viewModelStoreOwner =
>         if (checkNotNull(LocalViewModelStoreOwner.current) is NavBackStackEntry) {
>             checkNotNull(LocalViewModelStoreOwner.current) { "ViewModelStoreOwner is null" }
>         } else null
> 
>     return viewModel(
>         key = key,
>         factory = if (viewModelStoreOwner is NavBackStackEntry) {
>             HiltViewModelFactory(
>                 LocalContext.current,
>                 viewModelStoreOwner
>             )
>         } else null
>     )
> }
> ```
> 
> and then usage like:
> 
> ```kotlin
> YourComposableWithViewModelArg(
>             viewModel = hiltViewModel(key = "MyUniqueViewModelKey"),
>             // ... rest of the arguments
>             )
> ```

supported since 1.1.0-alpha01 of androidx.hilt:hilt-navigation-compose with key param
