### ISSUE TITLE
Android Hilt Jetpack Compose documentation is incorrect

### ISSUE THREAD

**Issue by goldy1992** [google/dagger#2622] opened 2021-05-14 21:01 UTC
On the [Compose and other libraries documentation](https://developer.android.com/jetpack/compose/libraries#hilt-navigation)
to use hilt with navigation and jetpack compose version states:

```
dependencies {
  ...
  implementation 'androidx.hilt:hilt-navigation-compose:1.0.0-alpha02'
}
```

however this library is not yet available.

it should still be 1.0.0-alpha01 and refer to 1.0.0-alpha01 documentation until 1.0.0-alpha02 is released.

**Comment by danysantiago** [comment] 2021-05-14 21:09
Dupe of https://github.com/google/dagger/issues/2606

**Closed by danysantiago** 2021-05-14 21:09 UTC
