### ISSUE TITLE
Hilt doesn't work if package name includes "import"

### ISSUE THREAD

**Issue by wlyu2001** [google/dagger#3775] opened 2023-03-01 07:35 UTC
For example if the package is xxx.import.xxx, then hilt components are not generated.

**Comment by danysantiago** [comment] 2023-03-01 15:50
Dupe of https://github.com/google/dagger/issues/2743

Essentially when Hilt is run with KAPT, packages with Java keyword are ignored and invalid. There is nothing Hilt can do at the moment and your best option is to not use Java keyword in package names.

**Closed by danysantiago** 2023-03-01 15:50 UTC
