### ISSUE TITLE
Allow @IntoSet on constructor or type

### ISSUE THREAD

**Issue by AngusMorton** [google/dagger#633] opened 2017-03-16 00:19 UTC
Allowing the `@IntoSet` annotation on a constructor or type would be useful because it means we could remove Modules that exist only to wire up the set multibindings.

For example:

```java
@Singleton public class FooAdapter implements Adapter {
  @Inject @IntoSet(Adapter.class) FooAdapter() { }
}
```

Would be equivalent to a Module:

```java
@Module public abstract class AdapterModule {
  @Binds @Singleton @IntoSet abstract Adapter provideFooAdapter(FooAdapter adapter);
}
```

**Comment by ronshapiro** [comment] 2017-03-16 00:40
Dupe of #510

**Closed by ronshapiro** 2017-03-16 00:40 UTC

**Comment by ansman** [comment] 2023-04-11 20:03
FYI I released a library that does this for you using Hilt (Android only unfortunately unless Hilt starts supporting non Android projects): https://auto-dagger.ansman.se/
