### ISSUE TITLE
Feature Request: @Binds Module abstraction

### ISSUE THREAD

**Issue by recoverrelax** [google/dagger#2029] opened 2020-08-07 12:49 UTC
**Request**

Please allow generating an automatic module equivalent of what module + binds provides

**Technical background**

I find myself having a couple of single method modules, only for the purpose of binding an interface

```kotlin
@Module
interface ModuleX {
@Binds
   fun bindRopeManager(impl: RopeManagerImpl): RopeManager
}

class RopeManagerImpl @Inject constructor()
```

**Proposed Feature**

```kotlin
@Binds(abstraction = RopeManager::class.java)
class RopeManagerIpm @Inject constructor(): RopeManager
```
Would something like this make sense and would it be easy to implement? (probably with a better naming than 'abstraction')

**Comment by JakeWharton** [comment] 2020-08-07 13:15
Dupe of #2026 and see also #510

**Closed** 2020-08-19 22:30 UTC
