### ISSUE TITLE
2.25.2 non-static method provideSpanCount() cannot be referenced from a static context

### ISSUE THREAD

**Issue by Ethan1983** [google/dagger#1694] opened 2019-12-14 21:13 UTC
Updated dagger from 2.24 to 2.25.2 and tried removing @JvmStatic in kotlin object based modules. It works fine in all cases except this one. It fails with "error: non-static method provideSpanCount() cannot be referenced from a static context".

Note: @BindsInstance would work but the actual implementation of provideSpanCount takes context and returns a value at runtime. This example is just to reproduce.

```
@Module
object AppModule {

    @Provides
    fun provideSpanCount() : Int = 10
}

class SampleApp : DaggerApplication() {

    @Inject
    @JvmField
    var count : Int = 0
}
```

**Comment by bcorso** [comment] 2019-12-16 23:40
I think this is a duplicate of issue #1648. This should be fixed now in 2.25.3.

**Closed by bcorso** 2019-12-16 23:40 UTC
