### ISSUE TITLE
Release build crash using 2.31-alpha

### ISSUE THREAD

**Issue by peterLaurence** [google/dagger#2291] opened 2021-01-18 08:55 UTC
Hi,

My release version runs just fine with `2.30.1-alpha`. However, with the new version, the release version fails (at app startup) with this stacktrace:
```
java.lang.IllegalAccessError: Interface e.b.b.c.c.a$a implemented by class com.peterlaurence.trekme.TrekMeApp_HiltComponents$ActivityC is inaccessible (declaration of 'com.peterlaurence.trekme.TrekMeApp_HiltComponents$ActivityC' appears in base.apk)
        at com.peterlaurence.trekme.DaggerTrekMeApp_HiltComponents_SingletonC$ActivityRetainedCImpl.activityComponentBuilder(Unknown Source:0)
        at e.b.b.c.d.a.a(Unknown Source:79)
        at e.b.b.c.d.a.generatedComponent(Unknown Source:11)
        at com.peterlaurence.trekme.Hilt_MainActivity.generatedComponent(Unknown Source:4)
        at com.peterlaurence.trekme.Hilt_MainActivity.inject(Unknown Source:7)
        at com.peterlaurence.trekme.Hilt_MainActivity.onCreate(Unknown Source:0)
        at com.peterlaurence.trekme.MainActivity.onCreate(Unknown Source:0)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Is there some proguard rule I should add?

**Comment by bcorso** [comment] 2021-01-19 17:14
Hmm, I'm not really sure what in Hilt could have caused this.

> Is there some proguard rule I should add?

Does it only happen in proguarded builds? 

Any idea what the underlying cause of this is (e.g. is it that `e.b.b.c.c.a$a` is completely missing from the dex, or something else)?

**Comment by peterLaurence** [comment] 2021-01-19 20:28
I wasn't clear. The release build finishes without error. It is when I start the app (the release version) that I get the crash.
The debug version, which isn't affected by proguard, runs fine.

**Comment by yshrsmz** [comment] 2021-01-19 22:57
@peterLaurence  `enableExperimentalClasspathAggregation` is true in your gradle file? I think I saw the same error when I enabled this flag.
I'm wondering if the root cause is the same as #2288

**Comment by hijamoya** [comment] 2021-01-20 06:22
Same issue here.

**Comment by peterLaurence** [comment] 2021-01-20 07:56
@yshrsmz No, I don't have `enableExperimentalClasspathAggregation` set. It's not the build that fails. The app crashes at startup, while reverting to `2.30.1-alpha` fixed the issue. I changed the OP to reflect that.
BTW, I also tested with `2.31.1-alpha`. Still the same stacktrace.

**Comment by satoshun** [comment] 2021-01-20 08:00
I got a same issue when release build.

Added proguard rules and output logs.

```
Process: my.app.dev, PID: 4079
java.lang.IllegalAccessError: Interface dagger.hilt.android.internal.lifecycle.DefaultViewModelFactories$ActivityEntryPoint implemented by class my.app.App_HiltComponents$ActivityC is inaccessible (declaration of 'my.app.App_HiltComponents$ActivityC' appears in /data/app/~~FM-gpW7f2V-7shmQqvIcog==/my.app.dev-I_VxkFwsLMsITVbsHfv9JQ==/base.apk)
    at my.app.DaggerApp_HiltComponents_SingletonC$ActivityRetainedCImpl.a(DaggerApp_HiltComponents_SingletonC.java:3652)
    at dagger.hilt.android.internal.managers.ActivityComponentManager.a(ActivityComponentManager.java:88)
    at dagger.hilt.android.internal.managers.ActivityComponentManager.I(ActivityComponentManager.java:66)
    ...
```

**Comment by bcorso** [comment] 2021-01-20 22:06
@satoshun thanks for the deobfuscated error message, that helps a lot!  @danysantiago was able to reproduce this locally and confirm the issue. `dagger.hilt.android.internal.lifecycle.DefaultViewModelFactories$ActivityEntryPoint`, was recently changed from public to pkg-private which is likely what triggered this issue. 

However, I think the real issue is in r8. Hilt allows non-public entry points by generating a public wrapper for the entry point, e.g. 

```java
// Hilt generates a public wrapper for PkgPrivateEntryPoint.
public interface HiltWrapper_PkgPrivateEntryPoint extends PkgPrivateEntryPoint {}

// The generated Hilt component extends the public wrapper
@Component(...)
interface HiltComponents_SingletonC extends HiltWrapper_PkgPrivateEntryPoint {}
```

It sounds like this is a bug in r8 where it is incorrectly removing the wrapper during shrinking/optimization. We should file a bug for r8.

In the meantime, you can try adding a keep rule for all `HiltWrapper_*` classes to unblock yourself.  We should probably also consider pushing another release that includes this keep rule automatically until the bug is fixed.

**Comment by peterLaurence** [comment] 2021-01-21 08:40
@satoshun For my own education, how did you generated a deobfuscated stacktrace? :)

**Comment by kenshin171** [comment] 2021-01-21 09:35
For anyone who wants the workaround, here is what i added to my proguard/r8 file.

```
-keep class  dagger.hilt.android.internal.modules.HiltWrapper_ActivityModule
-keep class dagger.hilt.android.internal.managers.HiltWrapper_ActivityRetainedComponentManager_LifecycleModule
-keep class dagger.hilt.android.internal.managers.HiltWrapper_ActivityRetainedComponentManager_ActivityRetainedLifecycleEntryPoint
-keep class dagger.hilt.android.internal.managers.HiltWrapper_ActivityRetainedComponentManager_ActivityRetainedComponentBuilderEntryPoint

-keep class dagger.hilt.android.internal.lifecycle.HiltWrapper_DefaultViewModelFactories_ActivityEntryPoint
-keep class dagger.hilt.android.internal.lifecycle.HiltWrapper_DefaultViewModelFactories_ActivityModule
-keep class dagger.hilt.android.internal.lifecycle.HiltWrapper_DefaultViewModelFactories_FragmentEntryPoint

-keep class dagger.hilt.android.internal.lifecycle.HiltWrapper_HiltViewModelFactory_ViewModelModule
-keep class dagger.hilt.android.internal.lifecycle.HiltWrapper_HiltViewModelFactory_ViewModelFactoriesEntryPoint
```

**Comment by satoshun** [comment] 2021-01-21 09:55
@peterLaurence  I use a `keepnames` proguard rule !

```
 -keepnames class dagger.**
```

**Comment by Chang-Eric** [comment] 2021-01-21 23:32
The immediate breakage caused by 2.31 has been reverted and pushed in 2.31.2. I will continue to leave this open though since the general issue still remains.

**Comment by FunkyMuse** [comment] 2021-01-25 11:56
> @peterLaurence I use a `keepnames` proguard rule !
> 
> ```
>  -keepnames class dagger.**
> ```

It works even with dagger.hilt.** since it obfuscates only the problematic hilt deps

**Comment by ColinAygalincSe** [comment] 2021-01-25 17:35
Hi, get the same issue. Here is the unscramble stack trace  : 

     at com.schneiderelectric.configelec.application.DaggerScotApplication_HiltComponents_SingletonC$ActivityRetainedCImpl.activityComponentBuilder(DaggerScotApplication_HiltComponents_SingletonC.java:0)
        at dagger.hilt.android.internal.managers.ActivityComponentManager.createComponent(ActivityComponentManager.java:79)
        at dagger.hilt.android.internal.managers.ActivityComponentManager.generatedComponent(ActivityComponentManager.java:11)
        at com.se.module.wiserhome.ui.activity.Hilt_WiserHomeActivity.generatedComponent(Hilt_WiserHomeActivity.java:4)
        at com.se.module.wiserhome.ui.activity.Hilt_WiserHomeActivity.inject(Hilt_WiserHomeActivity.java:7)
        at com.se.module.wiserhome.ui.activity.Hilt_WiserHomeActivity.onCreate(Hilt_WiserHomeActivity.java:0)
        at com.se.module.wiserhome.ui.activity.WiserHomeActivity.onCreate(WiserHomeActivity.java:0)
        at android.app.Activity.performCreate(Activity.java:7893)
        at android.app.Activity.performCreate(Activity.java:7880)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3286)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3460)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7590)
        at java.lang.reflect.Method.invoke(Method.java)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

@peterLaurence  : check this blogpost to unscramble stack trace : https://segunfamisa.com/posts/analyze-stack-trace-in-android-studio

**Comment by bcorso** [comment] 2021-01-25 17:56
Hi @ColinAygalincSe, 

1. The stack trace you posted is missing the line with the error -- is it the same as https://github.com/google/dagger/issues/2291#issuecomment-763413582 or are you reporting a new error?

2. Are you still seeing this error after the update to 2.31.2 (see https://github.com/google/dagger/issues/2291#issuecomment-765008233)?

**Comment by ColinAygalincSe** [comment] 2021-01-25 17:59
@bcorso : it just the unscramble stack trace. 
Update to  2.31.2 fix the issue.

**Comment by Chang-Eric** [comment] 2021-02-02 23:52
The underlying issue is https://issuetracker.google.com/178045782 which has been fixed in R8. Since that is done, and the immediate issue introduced by Hilt was fixed in 2.31.2, I'm closing this issue.

**Closed by Chang-Eric** 2021-02-02 23:52 UTC

**Comment by eugene-kirzhanov** [comment] 2021-04-08 17:31
Still reproducible in 2.34-beta

**Comment by danysantiago** [comment] 2021-04-08 17:38
@eugene-kirzhanov do you have a repro steps? Are you seeing the same issue as OP? Have you tried adding the obfuscation rules mentioned in https://github.com/google/dagger/issues/2291#issuecomment-764507001 ? We have not been able to repro this locally after updating the visibility in https://github.com/google/dagger/commit/a2798a8b26d9c983f4cd21f631cff8555557bf5d.

**Comment by eugene-kirzhanov** [comment] 2021-04-08 17:41
> @eugene-kirzhanov do you have a repro steps? Are you seeing the same issue as OP? Have you tried adding the obfuscation rules mentioned in [#2291 (comment)](https://github.com/google/dagger/issues/2291#issuecomment-764507001) ? We have not been able to repro this locally after updating the visibility in [a2798a8](https://github.com/google/dagger/commit/a2798a8b26d9c983f4cd21f631cff8555557bf5d).

Sorry, my mistake - commented in another thread #2502

**Comment by badoualy** [comment] 2021-09-20 13:40
For anyone hitting this with hilt 1.0.0:

`-keep class dagger.hilt.android.internal.** {*;}`

did the trick for me

(`dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$ActivityCreatorEntryPoint` might be enough though)
