### ISSUE TITLE
After updating 2.34.1-beta I got build error DaggerApp_HiltComponents_SingletonC.builder()

### ISSUE THREAD

**Issue by mcnarek** [google/dagger#2556] opened 2021-04-17 10:54 UTC
After updating Hilt version to **2.34-beta** I got build error` DaggerApp_HiltComponents_SingletonC.builder()`

I think its something about `class App : Application() { ... }` class

**Build Error:**
![image](https://user-images.githubusercontent.com/5946745/115110380-35b19380-9f8c-11eb-87c6-0cda5445cbce.png)

**Generated class:**
![image](https://user-images.githubusercontent.com/5946745/115110401-495cfa00-9f8c-11eb-8f5f-d41881cdca2e.png)

**And App's dependencies looks like:**
![image](https://user-images.githubusercontent.com/5946745/115110418-64c80500-9f8c-11eb-9ab4-0166af2f2f9f.png)
![image](https://user-images.githubusercontent.com/5946745/115110430-73aeb780-9f8c-11eb-9a40-be575ed15cba.png)
![image](https://user-images.githubusercontent.com/5946745/115110459-993bc100-9f8c-11eb-8c49-83c1cf79a301.png)

**My Application class like:**
![image](https://user-images.githubusercontent.com/5946745/115110449-8aeda500-9f8c-11eb-9b15-518cb39113da.png)

Note: Previous (2.33) version was OK.

Thanks.

**Comment by bcorso** [comment] 2021-04-17 16:49
This looks like a dupe of #2541. 

You'll need to remove your dependency on `hilt-lifecycle-viewmodel`. For details, see https://github.com/google/dagger/issues/2541#issuecomment-817927472

**Closed by bcorso** 2021-04-17 16:49 UTC

**Comment by mcnarek** [comment] 2021-04-17 19:34
Thanks @bcorso
