### ISSUE TITLE
"Dagger & Android" documentation needs overhauled.

### ISSUE THREAD

**Issue by JakeWharton** [google/dagger#407] opened 2016-07-14 03:32 UTC
> One of the primary advantages of Dagger 2 over most other dependency injection frameworks is that its strictly generated implementation (no reflection) means that it can be used in Android applications.

Guice and Dagger 1 "can be used" in Android as well. This paragraph should instead focus on the advantages of Dagger 2 for Android.

> But many of the patterns commonly applied to code intended for Android are contrary to those applied to other Java code. Even much of the advice in Effective Java is considered inappropriate for Android.

This paragraph should be deleted. Currently it's just inaccurate and FUD. Most patterns and Effective Java items apply fine. Unless you're going to backup this statement with actual examples  that justify the "most" and "much" words, its inclusion isn't necessary.

> In order to achieve the goals of both idiomatic and portable code, Dagger relies on ProGuard to post-process the compiled bytecode.

Idiomatic and portable code comes from the Java language and the choices made in the annotation processor on how to generate the code. ProGuard provides nothing here for either of those two things.

Dagger also doesn't _rely on_ ProGuard for anything. ProGuard is a completely optional build step in Android  and Dagger works fine without it.

> Moreover, Dagger has an explicit goal to ensure that the Java source that it generates is consistently compatible with ProGuard optimizations.

I think you meant "obfuscation" instead of "optimization". ProGuard's optimizations are an optional and volatile change to bytecode.

> Dagger assumes that users on Android will use ProGuard.

Why? ProGuard isn't even an Android-specific tool. Nothing about Dagger assumes and certainly does not require the use of ProGuard.

**Comment by gk5885** [comment] 2016-07-14 06:11
Dupe of #319

**Closed by gk5885** 2016-07-14 06:11 UTC
Labels: status: duplicate

**Comment by JakeWharton** [comment] 2016-07-14 15:34
That answer on that issue doesn't address inaccuracies on the page. I would
rather see the entire page deleted than remain in its current state.
