### ISSUE TITLE
Classes that don't implement anything get placed in incorrect directory

### ISSUE THREAD

**Issue by Amyntas** [google/dagger#101] opened 2015-01-11 19:20 UTC
I'm not sure if there currently is no way to @Inject a regular class instead of an interface, but if you try to give a class that doesn't implement anything an @Inject-constructor, it gets placed in a directory called "ClassName$$Factory" instead of the directory corresponding to its package declaration (for example, I have a class Thing that sits in com/package/Thing.java, and it looks like

public class Thing {
@Inject public Thing() {}
}

and it produces a class Thing$$Factory that sits in Thing$$Factory/Thing$$Factory.java instead of com/package/Thing$$Factory.java and looks like

package com.package; // Note the correct package declaration

import dagger.Factory;
import javax.annotation.Generated;

@Generated("dagger.internal.codegen.ComponentProcessor")
public enum Thing$$Factory implements Factory<Thing> {
INSTANCE;

  @Override
  public Thing get() {  
    return new Thing();
  }
}

**Comment by jwachter** [comment] 2015-01-12 23:01
I also noticed that lately when trying out again the current SNAPSHOT, and it seems to be a bug in [JavaWriter - Line 89](https://github.com/google/dagger/blob/master/compiler/src/main/java/dagger/internal/codegen/writer/JavaWriter.java#L89) where it should be `ClassName.create(packageName, simpleName)` instead of `ClassName.create(simpleName, simpleName)`

But it's already been fixed in https://github.com/google/dagger/pull/96

**Comment by cgruber** [comment] 2015-03-26 18:35
Can you please confirm that this is happening in the current snapshots, as we've had several code-drops since Jan 12, which have  affected the code paths that would be responsible for this behavior. 

I believe that fix in #96 is the relevant one, but I'd love verification from the bug author, if possible.

**Comment by tbroyer** [comment] 2015-03-26 18:48
Not the author but I can confirm I haven't seen the bogus behavior in the tests I wrote today for Bullet.

**Comment by gk5885** [comment] 2015-03-31 23:20
\o/

**Closed by gk5885** 2015-03-31 23:20 UTC
Labels: area: code-generation, status: fixed, type: bug
