### ISSUE TITLE
Dagger does not support providing @AssistedInject types

### ISSUE THREAD

**Issue by alizarei95** [google/dagger#2396] opened 2021-02-20 12:26 UTC
I am using Hilt (v2.32-alpha) dependency injection with viewmodel. I have a class with 2 parameters, the first is context and the second is an optional string so if not provide any value this takes null. To achieve this in Hilt I read below doc: https://dagger.dev/dev-guide/assisted-injection.html

This is my code :

```
class SharedPreferencesHelper @AssistedInject constructor(
    context: Context,
    @Assisted sharedPreferencesName: String? = null
) { ... }
```

And Hilt Module :

```
@Module
@InstallIn(ViewModelComponent::class)
object WebServicesModule {

    @Provides
    fun provideSharedPreferencesHelper(@ApplicationContext context: Context): SharedPreferencesHelper =
        SharedPreferencesHelper(context)
}
```
AssistedFactory interface:

```
@AssistedFactory
interface MyAssistedFactory {
    fun create(sharedPreferencesName: String): SharedPreferencesHelper
}
```
And my viewmodel :

```
@HiltViewModel
class SplashViewModel @Inject constructor(
    application: Application,
    savedStateHandle: SavedStateHandle,
    private val repository: SplashRepository
) : AndroidViewModel(application) {

    @Inject
    lateinit var assistedFactory: MyAssistedFactory

fun callSplashApi() {

        val preferencesHelper = assistedFactory.create("ss")
...
  }
}
```
But build fails with this error:

`Dagger does not support providing @AssistedInject types.`

**Comment by tbroyer** [comment] 2021-02-20 12:55
Duplicate of #2370?

**Comment by alizarei95** [comment] 2021-02-20 13:16
@tbroyer is there any way to handle this use case at this time?

**Comment by bcorso** [comment] 2021-02-21 01:28
@alizarei95, note that #2370 will allow you to provide a ***qualified*** `@AssistedInject` type, but we're still not allowing an unqualified `@AssistedInject` type to be provided to avoid confusion.

Thus, you'll have to provide your default type with a qualifier like, `@Default`. 

You probably also want to provide the default via the factory rather than calling the constructor directly.  For example:

```kotlin
@Module
@InstallIn(ViewModelComponent::class)
object WebServicesModule {
    @Provides
    @Default
    fun provideDefault(factory: MyAssistedFactory) = factory.create()
}

@AssistedFactory
interface MyAssistedFactory {
  fun create(sharedPreferencesName: String ?= null): SharedPreferencesHelper
}
```

**Also, note that the fix for #2370 is not yet included in a release. It should be out with the next Dagger release, 2.33.

**Comment by alizarei95** [comment] 2021-02-21 12:16
@bcorso Thanks
I wrote your codes but again I got error:
Dagger does not support providing @AssistedInject types.

Is my case is an unusual scenario? This is a little bit strange for me there is not a simple solution

**Comment by bcorso** [comment] 2021-02-22 02:59
@alizarei95 see the last part of my previous comment:

>  note that the fix for #2370 is not yet included in a release. It should be out with the next Dagger release, 2.33.

**Comment by alizarei95** [comment] 2021-02-22 06:01
@bcorso what about last part of my previous question?

> Is my case is an unusual scenario? This is a little bit strange for me there is not a simple solution

**Comment by beigirad** [comment] 2021-02-22 07:23
@bcorso Do you have any time estimation for releasing 2.33?
I have the same issue.

**Comment by beigirad** [comment] 2021-02-22 08:17
@alizarei95 
> is there any way to handle this use case at this time?

You can use [Square's AssistedInject ](https://github.com/square/AssistedInject) for assisting inject at this time. And when 2.33 is out you change just annotations (May need to remove some lines)

**Comment by bcorso** [comment] 2021-02-23 07:04
@beigirad we're should have a release out within the next week or two

**Comment by bcorso** [comment] 2021-02-23 16:16
Closing this as a dupe of #2370

**Closed by bcorso** 2021-02-23 16:16 UTC
