### ISSUE TITLE
additionalClassesDir property in TransformClassesWithAsmTask causes gradle cache misses

### ISSUE THREAD

**Issue by saihemanth121** [google/dagger#3563] opened 2022-09-11 16:13 UTC
I am facing gradle build cache misses in my android project with Hilt in TransformClassesWithAsmTask for each module when built on different machines (CI and local). Task input comparison between CI and local build scans says `Input 'visitorsList.$0.parameters.additionalClassesDir' is in both builds but the values are different.`

I'm suspecting this might be due to `AndroidEntryPointClassVisitor.AndroidEntryPointParams` having `additionalClassesDir: Property<File>` without any path normalisation. Would it be possible to add RELATIVE path sensitivity to this property? 

I also found an old issue to add tests around this scenario - https://issuetracker.google.com/issues/167186378

**Comment by kuanyingchou** [comment] 2022-09-30 16:47
Hi, @saihemanth121 , thanks for reporting. I'm still trying to reproduce this issue but from the source the property `additionalClassesDir` is already marked as `@Internal` and to my understanding Gradle [shouldn't include it in its cache key calculation](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/Internal.html). Could you share what versions of Gradle and Android Gradle Plugin you're using?

**Comment by saihemanth121** [comment] 2022-09-30 17:02
@kuanyingchou My bad, I didnt notice it has been marked `@Internal` in newer versions. I am using hilt 2.38.1 which has it marked as `@Input` only. Thank you, I'll update to a newer version soon.

**Comment by kuanyingchou** [comment] 2022-09-30 17:16
This should be a duplicate of https://github.com/google/dagger/issues/2763.

**Closed by kuanyingchou** 2022-09-30 17:16 UTC
Labels: type: bug, area: build, P2, area: hilt
