### ISSUE TITLE
 Error:Error converting bytecode to dex: Cause: Dex cannot parse version 52 byte code.

### ISSUE THREAD

**Issue by raghunandankavi2010** [google/dagger#614] opened 2017-03-05 07:15 UTC
Dagger libs used for android. 

```
           compile 'com.google.dagger:dagger:2.10-rc1'
           annotationProcessor 'com.google.dagger:dagger-compiler:2.10-rc1'
```

     This is caused by library dependencies that have been compiled using Java 8 or above.
      If you are using the 'java' gradle plugin in a library submodule add 
      targetCompatibility = '1.7'
      sourceCompatibility = '1.7'
      to that submodule's build.gradle file.
      ...while parsing dagger/Binds.class
      Error:1 error; aborting
      Error:Execution failed for task ':app:transformClassesWithDexForDebug'.

> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: Unable to pre-dex 'C:\Users\Raghu\.gradle\caches\modules-2\files-2.1\com.google.dagger\dagger\2.10-rc1\775d8608178ddadfec0be8b5f960b3827d9e9fec\dagger-2.10-rc1.jar' to 'F:\AndroidProjects\rxify-master\rxify-master\app\build\intermediates\pre-dexed\debug\dagger-2.10-rc1_e66a3f81726b8b110d85a47748a2005e1db8ae82.jar'

Looking at the error i tried

      tasks.withType(JavaCompile) {
        sourceCompatibility = "1.7"
        targetCompatibility = "1.7"
    }

But that also din't solve the problem.

**Comment by naturalwarren** [comment] 2017-03-05 07:46
This is fixed in 2.10-rc2.

**Comment by tbroyer** [comment] 2017-03-05 10:10
Dupe of #593 and#594

**Closed** 2017-03-05 13:07 UTC

**Comment by Jorgesmash** [comment] 2017-09-25 19:01
raghunandankavi2010 you solved it?

**Comment by kj387948407** [comment] 2017-10-19 01:53
It still appears in the latest version
