### ISSUE TITLE
Injecting component objects

### ISSUE THREAD

**Issue by juanyanezgc** [google/dagger#231] opened 2015-09-03 15:50 UTC
I've tried to inject a component and I got the following error at compile time:

Error:Execution failed for task > java.lang.UnsupportedOperationException: Not yet supporting COMPONENT binding types.

Any particular reason for this not being supported? As a workaround, I've tried wrapping the component into another object and that way I'm able to inject that wrapper and indirectly inject the component.

 Is there any issues about injecting components objects I should be aware of?

**Comment by netdpb** [comment] 2015-12-10 17:55
Can you include more of the stack trace? That looks like it's an error that is thrown when Dagger tries to report duplicate bindings.

Could it be that you have a `@Provides` method that also returns the component type?

**Comment by netdpb** [comment] 2016-01-20 19:37
We have reproduced this internally, and will fix.

**Comment by ronshapiro** [comment] 2016-08-09 21:32
Reopen if you're still getting this issue in Dagger 2.6, but this should be fixed.

**Closed by ronshapiro** 2016-08-09 21:32 UTC
Labels: area: validation, status: accepted, type: bug
