### ISSUE TITLE
Feature request: Binds on return type

### ISSUE THREAD

**Issue by kirich1409** [google/dagger#2158] opened 2020-10-23 19:55 UTC
Right now only one way of declare Bind in Dagger:
```java
interface Feature {
}

class FeatureImpl implements Feature {
}

@Module
interface BindsModule {

   @Binds
   Feature bindFeatureImpl_Feature(feature: FeatureImpl)
}
```
it will be better to have the possibility to declare Binds on the type, something like this:
```java
@BindsTo(FeatureImpl.class)
interface Feature {
}

class FeatureImpl implements Feature {
}
```
it will help eliminate a lot of boilerplate Binds modules

**Comment by JakeWharton** [comment] 2020-10-23 19:58
This is a dupe of #1164 it seems.

**Comment by bcorso** [comment] 2020-10-26 17:06
Thanks @JakeWharton for linking the dupe. Closing this since #1164 should cover it.

**Closed by bcorso** 2020-10-26 17:06 UTC

**Comment by ansman** [comment] 2023-04-11 20:03
FYI I released a library that does this for you using Hilt (Android only unfortunately unless Hilt starts supporting non Android projects): https://auto-dagger.ansman.se/
