### ISSUE TITLE
libraries conflict with dependencies bundled in dagger-compiler.jar 

### ISSUE THREAD

**Issue by gfx** [google/dagger#349] opened 2016-04-01 13:20 UTC
dagger-compiler bundles lots of libraries, not as maven dependencies. This causes problems when another annotation processing library uses a newer version of libraries that are used in dagger-compiler.

For example, there is an annotation processor that uses JavaPoet 1.6 feature (e.g. `CodeBlock.of()`), does not work with Dagger 2.2 because [JavaPoet 1.5.1, bundled in dagger-compiler](https://github.com/google/dagger/blob/master/compiler/pom.xml#L100-L102), is loaded.

I think dagger-compiler should not bundle any libraries because users can't control their versions.

## Environment

* JDK 1.8.0_77
* Dagger 2.2

**Comment by tbroyer** [comment] 2016-04-01 13:37
Partly a dupe of #228, but JavaPoet is new in Dagger 2.2, and the issue here is that maven-shade-plugin is lacking a relocation rule for `com.squareup`.

**Comment by gk5885** [comment] 2016-04-07 14:21
OK, then I think we can just close this as a dupe of #228 and update that to include javapoet as well.

**Closed by gk5885** 2016-04-07 14:21 UTC
