### ISSUE TITLE
Gradle crashes with: Hilt + AGP 7.0.0-beta04

### ISSUE THREAD

**Issue by sabin19** [google/dagger#2703] opened 2021-06-17 12:36 UTC
Versions:
Hilt : 2.37
AGP : 7.0.0-beta04
Gradle : 7.0.2-all

FAILURE: Build failed with an exception.

* What went wrong:
com/android/build/api/extension/AndroidComponentsExtension$DefaultImpls

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.NoClassDefFoundError: com/android/build/api/extension/AndroidComponentsExtension$DefaultImpls
	at dagger.hilt.android.plugin.HiltGradlePlugin.configureBytecodeTransformASM(HiltGradlePlugin.kt:258)
	at dagger.hilt.android.plugin.HiltGradlePlugin.configureHilt(HiltGradlePlugin.kt:89)
	at dagger.hilt.android.plugin.HiltGradlePlugin.access$configureHilt(HiltGradlePlugin.kt:59)
	at dagger.hilt.android.plugin.HiltGradlePlugin$apply$1.execute(HiltGradlePlugin.kt:66)

**Comment by danysantiago** [comment] 2021-06-17 15:18
Dupe of https://github.com/google/dagger/issues/2700

**Closed by danysantiago** 2021-06-17 15:18 UTC
