### ISSUE TITLE
Add Dagger Base Classes for DialogFragment

### ISSUE THREAD

**Issue by akaN44** [google/dagger#847] opened 2017-08-18 19:02 UTC
I would like to know if it's possible to add Dagger base classes for DialogFragment (and support version) like
 ```
@Beta
public abstract class DaggerDialogFragment extends DialogFragment implements HasFragmentInjector {

  @Inject DispatchingAndroidInjector<Fragment> childFragmentInjector;

  @Override
  public void onAttach(Context context) {
    AndroidInjection.inject(this);
    super.onAttach(context);
  }

  @Override
  public AndroidInjector<Fragment> dialogFragmentInjector() {
    return childFragmentInjector;
  }
}
```

**Comment by ronshapiro** [comment] 2017-08-18 19:04
Sounds reasonable. Dialog fragments are pretty common. Want to add this?

**Comment by akaN44** [comment] 2017-08-18 20:11
Actually I have it in one of my project but it make more sense to be in the dagger android library. I tried to make a Pull request but I don't have right on this repo.

**Comment by ronshapiro** [comment] 2017-08-18 20:15
You should be able to fork the repo, commit to your fork, and then make a pull request here from that.

**Comment by akaN44** [comment] 2017-08-18 20:16
Yes I can do that thanks for quick reply

**Comment by akaN44** [comment] 2017-08-18 20:16
I'll close the ticket when the PR is up

**Comment by ronshapiro** [comment] 2017-09-12 19:42
Did you ever send this?

**Comment by ronshapiro** [comment] 2017-09-12 19:54
Dupe of #728.

**Closed by ronshapiro** 2017-09-12 19:54 UTC
