### ISSUE TITLE
Multibinding into a map produces wildly different implementations

### ISSUE THREAD

**Issue by manabreak** [google/dagger#1750] opened 2020-02-27 10:55 UTC
I ran into a weird issue with Dagger in an Android application I'm working on. I have two components, `ApplicationComponent` and `UserComponent`, plus a `TestComponent` which extends on `ApplicationComponent`.

Now, both `ApplicationComponent` and `UserComponent` have modules that provide dependencies via multibinding into a map. The functions annotated with `@Provides` are also `@Named`.

In production code, everything works smooth and dandy, but during tests, there's a `NoClassDefFoundError: Failed resolution of: Lcom/google/common/collect/ImmutableMap`. I investigated the generated `DaggerXXXComponent` classes and noticed that there are three different implementations of the same method:

`ApplicationComponent` returns the map like this
```
return Collections.<Class<? extends ViewModel>, Provider<ViewModel>>singletonMap(...
```

`UserComponent` returns the map like this:
```
return MapBuilder.<Class<? extends ViewModel>, Provider<ViewModel>>newMapBuilder(2).put(...
```

And finally, the `TestComponent` returns the map like this:
```
return ImmutableMap.<Class<? extends ViewModel>, Provider<ViewModel>>of(...
```

What affects the return type of the method? Is there a way to control the return type?

**Comment by bcorso** [comment] 2020-03-04 18:09
Which version of Dagger are you using? Does this issue repro with [Dagger 2.26](https://github.com/google/dagger/releases/tag/dagger-2.26)?

The relevant code is in [MapBindingExpression.java](https://github.com/google/dagger/blob/beed87cc75439d873a2f53dbd70306266023d766/java/dagger/internal/codegen/writing/MapBindingExpression.java#L96). It's essentially:

```java
switch (numDeps) {
   case 0: return "Collections.emptyMap()"
   case 1: return "Collections.singletonMap(arg1)"
   default:
      return isImmutableMapInClassPath
         ? "ImmutableMap.builder().build()"
         : "MapBuilder.newMapBuilder().build()"
}
```

So it looks like the issue is that Dagger found `ImmutableMap` in the class path at compile time but not at runtime. From [NoClassDefFoundError javadoc](https://docs.oracle.com/javase/7/docs/api/java/lang/NoClassDefFoundError.html):

> "The searched-for class definition existed when the currently executing class was compiled, but the definition can no longer be found."

I'd need repro case to troubleshoot further. 

You can also try to work around the issue by manually adding guava to your build.gradle dependencies.

**Comment by bcorso** [comment] 2020-03-26 15:10
Closing this for now. Feel free to reopen if you have further questions.

**Closed by bcorso** 2020-03-26 15:10 UTC
