### ISSUE TITLE
Injection in custom views using AndroidInjector<View>

### ISSUE THREAD

**Issue by abhaysood** [google/dagger#765] opened 2017-06-05 11:01 UTC
Hey, I was building a custom view on which the user can perform some actions. In the traditional way I would have to create callbacks for all the actions and register them with the activity where I will react to those actions.
Making  the View class a possible injection target by creating `AndroidInjector<View>` would make life much easier and allow us to create custom views which can directly interact with the rest of the app without bloating the activity with callbacks.

Is this a feasible option?

**Comment by abhaysood** [comment] 2017-06-05 11:43
For more context consider the following view:
 
```
class CustomNavigationView : NavigationView, NavigationView.OnNavigationItemSelectedListener {
    lateinit var drawerLayout: DrawerLayout

    override fun onAttachedToWindow() {
        super.onAttachedToWindow()
        if (parent !is DrawerLayout) {
            throw IllegalStateException("NavigationView's parent must be a DrawerLayout")
        } else {
            drawerLayout = parent as DrawerLayout
        }
    }

    override fun onNavigationItemSelected(item: MenuItem): Boolean {
        when (item.itemId) {
            R.id.nav_notes -> {
                // actionCreator.create(Action.NOTES_ITEM_CLICKED)
                drawerLayout.closeDrawer(Gravity.START)
                return true
            }
            R.id.nav_archive -> {
                drawerLayout.closeDrawer(Gravity.START)
                return true
            }
            else -> {
                throw IllegalStateException("No such id: $itemId")
            }
        }
    }
}
```

I would like to inject a class which will allow me to do something to the rest of the app when a particular menu item is clicked. The injection can be performed in `onAttachedToWindow`.

**Comment by ronshapiro** [comment] 2017-06-05 11:59
This is a dupe of another issue. I'm on my phone so I can't easily find which one, but it shouldn't be hard to find.

**Closed by ronshapiro** 2017-06-05 11:59 UTC

**Comment by JonathanMerritt** [comment] 2017-06-05 20:21
#720
