### ISSUE TITLE
Map<Class<out ViewModel>, @JvmSuppressWildcards dagger.Lazy<ViewModel>> cannot be provided without an @Provides-annotated method.

### ISSUE THREAD

**Issue by hadilq** [google/dagger#2474] opened 2021-03-12 16:47 UTC
## Issue
There is a scenario in which I need to inject something like `Map<Class<out ViewModel>, @JvmSuppressWildcards dagger.Lazy<ViewModel>>` into a class, but it gives me `cannot be provided without an @Provides-annotated method.`

## Details
By using dagger `2.31.2` or `2.33` and Kotlin `1.4.31`, this sceniario is so similar to what usually we do for `ViewModelProviderFactory`s, but instead of `javax.inject.Provider` I need `dagger.Lazy` there. The similarity is the reason I used `ViewModel`, `ViewModelProviderFactory`, etc. names in the title and example below but the real use case is something else! However, this is the setup.

```kotlin
class ViewModelProviderFactory @Inject constructor(
    private val creators: Map<Class<out ViewModel>, @JvmSuppressWildcards dagger.Lazy<ViewModel>>
) : ViewModelProvider.Factory {
   ...
}


@Module
abstract class ViewModelModule {
    @[Binds IntoMap ViewModelKey(SomeViewModel::class)]
    internal abstract fun bindSomeViewModel(viewModel: SomeViewModel): ViewModel
    ..
}

@MustBeDocumented
@Target(AnnotationTarget.FUNCTION, AnnotationTarget.PROPERTY_GETTER, AnnotationTarget.PROPERTY_SETTER)
@Retention(AnnotationRetention.RUNTIME)
@MapKey
annotation class ViewModelKey(val value: KClass<out ViewModel>)
```

But I get ` cannot be provided without an @Provides-annotated method.`. On the other hand, if we replace `dagger.Lazy` with `javax.inject.Provider`, without any other changes, it will successfully compile! Also if we remove `javax.inject.Provider` and `dagger.Lazy` all together, it will successfully compile again!

## Expectation
It should be build successfully with `dagger.Lazy` too, because the `ViewModel`s can be provided without problem for `javax.inject.Provider`.

**Comment by bcorso** [comment] 2021-03-12 17:34
Closing this as duplicate of #1630

**Closed by bcorso** 2021-03-12 17:34 UTC
