### ISSUE TITLE
JaCoCo junit coverage does not work when adding Hilt to Android project

### ISSUE THREAD

**Issue by ZOlbrys** [google/dagger#2740] opened 2021-07-07 03:17 UTC
I recently noticed that simply adding the Hilt dependencies to my project resulted in JaCoCo no longer picking up code coverage data from JUnit tests of my Kotlin code.

To test this out a bit I created a new app with a single Kotlin class and added JaCoCo - so far so great.  After adding Hilt to the app (note: not even using Hilt yet, just adding the dependencies) and re-running JaCoCo the coverage was no longer being reported.

version info:
Hilt 2.37
JaCoCo 0.87
Kotlin 1.5.20

Sample app and instructions are available here: https://github.com/ZOlbrys/HiltJacocoSampleApp

**Comment by bcorso** [comment] 2021-07-07 15:33
This sounds like a dupe of #1982. Closing this one for now.

**Closed by bcorso** 2021-07-07 15:33 UTC

**Comment by ZOlbrys** [comment] 2021-07-07 15:37
I saw that earlier but wasn't even using `@AndroidEntryPoint ` syntax yet - the issue described here is reproduced just by adding the dependencies... so I figured it was different.  Hmm.

**Comment by slott** [comment] 2021-09-28 14:08
I just saw the same - damn that was a tricky one.

So _just_ adding this

apply plugin: 'dagger.hilt.android.plugin'

caused the problem...

**Comment by bcorso** [comment] 2021-09-28 15:10
I _think_ these are essentially the same underlying issue, which is that adding the Hilt Gradle plugin adds a transform to the AGP transformation pipeline, and JaCoCo isn't handling that properly. If that issue is fixed, it should fix both #1982 and this issue.

The workaround for #1982 should also apply here, which is to remove the plugin and use the suggestion (https://github.com/google/dagger/issues/1982#issuecomment-710308132) for any `@AndroidEntryPoint` usages. It's not great, but I think it's the best we have for now.

**Comment by Morteza-Rastgoo** [comment] 2022-11-28 19:50
A year after and the problem still exists. Any updates on this?

**Comment by shubhamgarg1** [comment] 2023-01-07 06:30
I was able to resolve this issue in my project by using the hack mentioned here: https://issuetracker.google.com/issues/161300933#comment5

**Comment by aljohnston112** [comment] 2023-07-20 20:38
Same issue. Created a test project to confirm.

**Comment by rkrishnan2012** [comment] 2023-07-31 17:22
You can work around this by adding `build/intermediates/classes/debug/transformDebugClassesWithAsm` to your Jacoco classes set.
