### ISSUE TITLE
java.lang.NoSuchMethodError: No interface method putIfAbsent(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Ljava/util/Map; or its super classes (declaration of 'java.util.Map' appears in /system/framework/core-libart.jar)

### ISSUE THREAD

**Issue by kingravi17** [google/dagger#3740] opened 2023-02-13 02:49 UTC
[Metadata]
SystemVersion: 01-21-04.1-MG-00-UPDATE012 release-keysOS Version: 6.0.1
Brand: ZebraManufacturer: Zebra TechnologiesBuildType: Manufacturer/Model/Type/Id: Zebra Technologies/TC56/GSM/
--

02-12 01:45:04.386 10153 10153 E CrashMetricHelper: 	at com.google.common.collect.j0.a(JdkBackedImmutableMap.java:5)
02-12 01:45:04.386 10153 10153 E CrashMetricHelper: 	at com.google.common.collect.s0.a(RegularImmutableMap.java:22)
02-12 01:45:04.386 10153 10153 E CrashMetricHelper: 	at com.google.common.collect.a0$a.a(ImmutableMap.java:19)
02-12 01:45:04.386 10153 10153 E CrashMetricHelper: 	at android.dagger.DaggerAppComponent$LoginActivitySubcomponentImpl.getMapOfClassOfAndProviderOfAndroidInjectorFactoryOf(DaggerAppComponent.java:1)
02-12 01:45:04.386 10153 10153 E CrashMetricHelper: 	at .android.dagger.DaggerAppComponent$LoginActivitySubcomponentImpl.getDispatchingAndroidInjectorOfObject(DaggerAppComponent.java:1)
02-12 01:45:04.386 10153 10153 E CrashMetricHelper: 	at android.dagger.DaggerAppComponent$LoginActivitySubcomponentImpl.injectLoginActivity(DaggerAppComponent.java:4)
02-12 01:45:04.386 10153 10153 E CrashMetricHelper: 	at android.dagger.DaggerAppComponent$LoginActivitySubcomponentImpl.inject(DaggerAppComponent.java:2)
02-12 01:45:04.386 10153 10153 E CrashMetricHelper: 	at android.dagger.DaggerAppComponent$LoginActivitySubcomponentImpl.inject(DaggerAppComponent.java:1)
02-12 01:45:04.386 10153 10153 E CrashMetricHelper: 	at dagger.android.DispatchingAndroidInjector.inject(DispatchingAndroidInjector.java:6)
02-12 01:45:04.386 10153 10153 E CrashMetricHelper: 	at dagger.android.a.a(AndroidInjection.java:55)
02-12 01:45:04.386 10153 10153 E CrashMetricHelper: 	at dagger.android.a.a(AndroidInjection.java:5)

**Comment by bcorso** [comment] 2023-02-13 03:32
This looks like a duplicate of #3600.

**Closed by bcorso** 2023-02-13 03:32 UTC
