### ISSUE TITLE
Poor error message for transitive Gradle module dependencies

### ISSUE THREAD

**Issue by dandc87** [google/dagger#2043] opened 2020-08-12 23:00 UTC
Given a gradle project like:

```kotlin
// in gradle :module2 module
class Module2 @Inject constructor() {}

// in gradle :module1 module
// implementation project(":module2")
class Module1 @Inject constructor(dep: Module1) {}

// in gradle :root module
// implementation project(":module1")
// Does NOT depend on :module2
@Component interface MyComponent {
  fun module1(): Module1
}
```

Dagger will output an error:

```
$ ./gradlew assemble
...
> Task :root:kaptDebugKotlin FAILED
error: cannot access Module2
  class file for Module2 not found
  Consult the following stack trace for details.
  com.sun.tools.javac.code.Symbol$CompletionFailure: class file for Module2 not found
```

Knowing how Dagger generates components, I know that the `:root` module needs access to all transitive classes. But it would be nice if there was a better, more actionable error message.

It would also be wonderful if Dagger could just work here, but I'm sure that's a pipe dream.

**Comment by bcorso** [comment] 2020-08-13 15:51
I this this has the same root cause as https://github.com/google/dagger/issues/970#issuecomment-472069736.

I don't think there's much we can do. From Ron:

> We can't catch Symbol$CompletionFailure as that's a javac internal type [...] and we don't have any way to even know that the annotation might not complete correctly.

**Comment by danysantiago** [comment] 2020-08-26 16:02
I'll close this for now, since it is the same as https://github.com/google/dagger/issues/970, I also wanted to add that we are investigating for possible solutions with the Android Gradle Team with regards to this since it also affects Hilt (https://github.com/google/dagger/issues/1991#issuecomment-661245887).

**Closed by danysantiago** 2020-08-26 16:02 UTC
