### ISSUE TITLE
Out Of Memory with dagger 2.25.2

### ISSUE THREAD

**Issue by lucas34** [google/dagger#1645] opened 2019-10-24 01:41 UTC
Hi, I recently tried to update to dagger 2.25.2 from 2.24. I'm having OOM during kapt. 
I tried changing the configuration with way more memory and I notice that the annotation processing is around 2 to 3x slower compare to 2.24.
The project is pretty huge, almost fully in kotlin and have hundreds of modules

EDIT:
Having the issue with gradle plugin 3.5.1 but does not happen with 3.6.0-beta1

```
e: java.lang.IllegalStateException: failed to analyze: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.jetbrains.kotlin.analyzer.AnalysisResult.throwIfError(AnalysisResult.kt:56)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:182)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:164)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:54)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1558)
	at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.sun.tools.javac.code.Scope.makeEntry(Scope.java:231)
	at com.sun.tools.javac.code.Scope.enter(Scope.java:220)
	at com.sun.tools.javac.code.Scope.enter(Scope.java:202)
	at com.sun.tools.javac.code.Scope.enter(Scope.java:198)
	at com.sun.tools.javac.comp.MemberEnter.visitVarDef(MemberEnter.java:683)
	at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:852)
	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:437)
	at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:449)
	at com.sun.tools.javac.comp.MemberEnter.finishClass(MemberEnter.java:459)
	at com.sun.tools.javac.comp.MemberEnter.finish(MemberEnter.java:1404)
	at com.sun.tools.javac.comp.MemberEnter.complete(MemberEnter.java:1199)
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1037)
	at com.sun.tools.javac.comp.Enter.complete(Enter.java:493)
	at com.sun.tools.javac.comp.Enter.main(Enter.java:471)
	at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:982)
	at com.sun.tools.javac.main.JavaCompiler.enterTreesIfNeeded(JavaCompiler.java:965)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1242)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:79)
	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:35)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.runAnnotationProcessing(Kapt3Extension.kt:230)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:188)
	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:99)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:96)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:106)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:81)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:555)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:82)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:107)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:546)
```

**Comment by bcorso** [comment] 2019-10-24 02:52
Hmm, my initial guess is that this is due to reading the [KotlinClassMetadata](https://github.com/google/dagger/tree/master/java/dagger/internal/codegen/kotlin) for each module (required for the [new Kotlin-specific features](https://github.com/google/dagger/releases/tag/dagger-2.25.2)). I'll take a look at this and see if anything obvious shows up in profiling.

**Comment by lucas34** [comment] 2019-10-24 03:02
I manage to compile by using gradle plugin 3.6.0-beta1. Will continue testing with this one.

**Comment by Chang-Eric** [comment] 2019-10-24 21:23
When switching to 3.6.0-beta1, does that fix just the OOM or does it also change the build speed as well?

**Comment by lucas34** [comment] 2019-10-25 01:06
With 3.6.0-beta1 the build speed is back to how to was with the old dagger version.

**Comment by chrisharris77** [comment] 2019-11-01 17:32
I still get Out of Memory Errors with dagger 2.25.2 and gradle plugin 3.6.0-beta02

**Comment by gildor** [comment] 2019-11-04 02:28
I think that 3.6.0 helps (sometimes) just because in 3.6 were fixed a few regressions of 3.5 that cause higher memory usage, so most probably Dagger 2.25.2 has higher usage of memory, but it less visible on 3.6 which has lower usage of memory, but the problem still exists (as @chrisharris77  mentioned)

**Comment by Chang-Eric** [comment] 2019-11-04 18:41
Thanks, we're looking into this. It is likely that the extra Kotlin metadata processing we need to do for the object class and qualifier on fields support is taking the extra memory.

**Comment by gavra0** [comment] 2019-12-11 18:22
R.java files (generated in 3.5) may cause very high memory usage. In 3.6 we generate R.jar so this should save quite a bit of memory in the javac compiler (which is used by KAPT).

**Comment by Ethan1983** [comment] 2019-12-14 15:41
Subscribing, just started using 2.25.2

**Comment by lucas34** [comment] 2019-12-17 10:05
Still have out of memory after updating to 2.25.3

**Comment by doniwinata0309** [comment] 2019-12-19 12:46
I got 3gb leaked from kapt. 
<img width="996" alt="Screen Shot 2019-12-19 at 19 41 03" src="https://user-images.githubusercontent.com/38415463/71174369-94cb9f00-2297-11ea-80be-56dcd133a289.png">
<img width="849" alt="Screen Shot 2019-12-19 at 19 41 16" src="https://user-images.githubusercontent.com/38415463/71174370-94cb9f00-2297-11ea-9167-c830fafd03a7.png">
Some people also got similar issue:
 https://youtrack.jetbrains.com/issue/KT-32962

**Comment by bcorso** [comment] 2019-12-23 18:54
Thanks for the heap dump. Looks like this is from a static cache in `RequestKinds` causing a memory leak, which is probably made worse due to the persistent GradleDaemon. We should have a fix shortly, and we'll push out a new minor release.

**Comment by Ma7moudHatem** [comment] 2019-12-25 09:43
Also please check this:

> Task :app:compileDev3DebugKotlin
e: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:207)
	at org.jetbrains.org.objectweb.asm.ClassReader.readUtf(ClassReader.java:3478)
	at org.jetbrains.org.objectweb.asm.ClassReader.readUtf(ClassReader.java:3446)
	at org.jetbrains.org.objectweb.asm.ClassReader.readUTF8(ClassReader.java:3427)
	at org.jetbrains.org.objectweb.asm.ClassReader.readCode(ClassReader.java:2343)
	at org.jetbrains.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1276)
	at org.jetbrains.org.objectweb.asm.ClassReader.accept(ClassReader.java:680)
	at org.jetbrains.kotlin.com.intellij.psi.impl.compiled.ClsFileImpl.buildFileStub(ClsFileImpl.java:580)
	at org.jetbrains.kotlin.com.intellij.psi.impl.compiled.ClassFileStubBuilder.buildStubTree(ClassFileStubBuilder.java:54)
	at org.jetbrains.kotlin.com.intellij.psi.impl.compiled.ClassFileStubBuilder.buildStubTree(ClassFileStubBuilder.java:25)
	at org.jetbrains.kotlin.com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:62)
	at org.jetbrains.kotlin.com.intellij.psi.stubs.CoreStubTreeLoader.readOrBuild(CoreStubTreeLoader.java:49)
	at org.jetbrains.kotlin.com.intellij.psi.impl.compiled.ClsFileImpl.getStubTree(ClsFileImpl.java:486)
	at org.jetbrains.kotlin.com.intellij.psi.impl.compiled.ClsFileImpl.getStub(ClsFileImpl.java:458)
	at org.jetbrains.kotlin.com.intellij.psi.impl.compiled.ClsFileImpl.getClasses(ClsFileImpl.java:134)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCliJavaFileManagerImpl$Companion.findClassInPsiFile(KotlinCliJavaFileManagerImpl.kt:261)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCliJavaFileManagerImpl$Companion.access$findClassInPsiFile(KotlinCliJavaFileManagerImpl.kt:257)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCliJavaFileManagerImpl.findPsiClassInVirtualFile(KotlinCliJavaFileManagerImpl.kt:227)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCliJavaFileManagerImpl.access$findPsiClassInVirtualFile(KotlinCliJavaFileManagerImpl.kt:48)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCliJavaFileManagerImpl$findClasses$1$$special$$inlined$forEachClassId$lambda$1.invoke(KotlinCliJavaFileManagerImpl.kt:166)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCliJavaFileManagerImpl$findClasses$1$$special$$inlined$forEachClassId$lambda$1.invoke(KotlinCliJavaFileManagerImpl.kt:48)
	at org.jetbrains.kotlin.cli.jvm.index.JvmDependenciesIndexImpl$traverseDirectoriesInPackage$1.invoke(JvmDependenciesIndexImpl.kt:77)
	at org.jetbrains.kotlin.cli.jvm.index.JvmDependenciesIndexImpl$traverseDirectoriesInPackage$1.invoke(JvmDependenciesIndexImpl.kt:32)
	at org.jetbrains.kotlin.cli.jvm.index.JvmDependenciesIndexImpl.search(JvmDependenciesIndexImpl.kt:131)
	at org.jetbrains.kotlin.cli.jvm.index.JvmDependenciesIndexImpl.traverseDirectoriesInPackage(JvmDependenciesIndexImpl.kt:76)
	at org.jetbrains.kotlin.cli.jvm.index.JvmDependenciesDynamicCompoundIndex.traverseDirectoriesInPackage(JvmDependenciesDynamicCompoundIndex.kt:59)
	at org.jetbrains.kotlin.cli.jvm.index.JvmDependenciesIndex$DefaultImpls.traverseDirectoriesInPackage$default(JvmDependenciesIndex.kt:35)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCliJavaFileManagerImpl$findClasses$1.invoke(KotlinCliJavaFileManagerImpl.kt:162)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCliJavaFileManagerImpl$findClasses$1.invoke(KotlinCliJavaFileManagerImpl.kt:48)
	at org.jetbrains.kotlin.util.PerformanceCounter.time(PerformanceCounter.kt:101)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCliJavaFileManagerImpl.findClasses(KotlinCliJavaFileManagerImpl.kt:158)

**Comment by bcorso** [comment] 2019-12-27 18:27
This should hopefully be fixed in [2.25.4](https://github.com/google/dagger/releases/tag/dagger-2.25.4).

**Comment by chao2zhang** [comment] 2019-12-27 19:55
2.25.4 resolves the out of memory issue in our case. We have 70k+ lines in the generated dagger component.

**Comment by lucas34** [comment] 2019-12-27 21:49
Thanks everyone. Will bump and will close this issue if we can confirm that the issue went away.

**Comment by doniwinata0309** [comment] 2019-12-28 02:08
I checked my heap dump from 2.25.4 and the leak went away. Thanks for the fix !

**Closed** 2019-12-28 04:32 UTC
