### ISSUE TITLE
lint.jar does not specify a vendor; see IssueRegistry#vendor

### ISSUE THREAD

**Issue by jaredsburrows** [google/dagger#3221] opened 2022-02-06 15:50 UTC
AGP: 7.1.1
Dagger: 2.40.5

## Repro:
```
git clone https://github.com/jaredsburrows/android-gif-example
cd android-gif-example
gradlew :app:lintAnalyzeDebug
```

## Warning:
```
> Task :app:lintAnalyzeDebug
dagger.lint.DaggerIssueRegistry in /Users/<>/.gradle/caches/transforms-3/d435f2bb6101c503720377b9566a3a49/transformed/dagger-lint-aar-2.40.5/jars/lint.jar does not specify a vendor; see IssueRegistry#vendor
```

**Comment by danysantiago** [comment] 2022-02-06 16:55
Dupe of https://github.com/google/dagger/issues/2582

**Closed by danysantiago** 2022-02-06 16:55 UTC
