### ISSUE TITLE
Cannot see Dagger build error log 

### ISSUE THREAD

**Issue by jollyjoker992** [google/dagger#531] opened 2016-12-16 03:00 UTC
I cannot see Dagger Error Log when build project. My project using both Dagger 2 and Android DataBinding and when I build with error, I can only see DataBinding Error but I know exactly all error comes from my Dagger 2 implementation. Pls help me to trace Dagger 2 error log. Thank you !

**Comment by ronshapiro** [comment] 2016-12-16 15:45
Dupe of #306. Ill add some docs for this.

**Closed by ronshapiro** 2016-12-16 15:45 UTC
