### ISSUE TITLE
[Feature Request] Allow Dagger Hilt to be configured from "plugins" DSL

### ISSUE THREAD

**Issue by jaredsburrows** [google/dagger#3170] opened 2022-01-18 17:30 UTC
## Description
Publish plugin data for Dagger Hilt plugin? The AGP and Kotlin plugins do this already.

## Example (currently in production)

Using`buildscript`:
```
buildscript {
  repositories {
    google()
    mavenCentral()
  }

  dependencies {
    classpath("com.android.tools.build:gradle:7.0.4")
    classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10")
  }
}

apply {
  plugin("com.android.application")
  plugin("org.jetbrains.kotlin.android")
}
```

Using `plugins`:
```
plugins {
  id("com.android.application") version "7.0.4"
  kotlin("android") version "1.6.10"
}
```

# Proposal Example

Using`buildscript`:
```
buildscript {
  repositories {
    google()
    mavenCentral()
  }

  dependencies {
    classpath("com.google.dagger:hilt-android-gradle-plugin:2.40.5")
  }
}

apply {
  plugin("dagger.hilt.android.plugin")
}
```

Using `plugins`:
```
plugins {
  id("com.google.dagger.hilt") version "2.40.5"
}
```

**Comment by danysantiago** [comment] 2022-01-18 17:35
Duplicate of https://github.com/google/dagger/issues/2774, we need to publish a marker artifact for this to work.

**Closed by danysantiago** 2022-01-18 17:35 UTC

**Comment by jaredsburrows** [comment] 2022-01-18 17:43
@danysantiago Can we update #2774's title and description or use this issue to track the progress?

**Comment by jaredsburrows** [comment] 2022-02-02 15:14
@danysantiago submitted this change here https://github.com/google/dagger/commit/e50aa067efc6484e165e6e0715dc7391487a03f1
