### ISSUE TITLE
Make @ContributesAndroidInjector for SomeActivity also bind AndroidInjector<SomeActivity>

### ISSUE THREAD

**Issue by makaroffandrey** [google/dagger#874] opened 2017-09-13 19:44 UTC
I want to use `@ContributesAndroidInjector` with a custom `@Scope`, so that after a configuration change I will get the same instances.
To do this I need to inject a `@Subcomponent`, that is responsible for injecting some activity, into that activity, and then handle persistence of this `@Subcomponent`
I have two options to do this:

1. Inject the component by its name as generated by Dagger
```Java
@Inject
SomeActivityModule_ContributeSomeActivity.SomeActivitySubcomponent subcomponent;
```
But this leaks information about my component structure to the activity, which makes faking `AndroidInjector<Activity>` for testing more difficult
2. Create a module with this binding
```Java
@Binds
abstract AndroidInjector<SomeActivity>
    bindSomeActivityInjector(SomeActivityModule_ContributeSomeActivity.SomeActivitySubcomponent subcomponent);
```
and use this module as a parameter for `@ContributesAndroidInjector` annotation.
But this requires creating a separate module class for every `Activity` that needs to handle persistence of its dependencies.

Also both options depend on how dagger actually names this `@Subcomponent`s, and therefore any changes to this behavior will break the code.

I am not familiar with Dagger internals but I hope it is possible to create binding from `SomeActivityModule_ContributeSomeActivity.SomeActivitySubcomponent` to `AndroidInjector<SomeActivity>` automatically

**Comment by ronshapiro** [comment] 2018-03-23 19:06
This is a duplicate of #961

**Closed by ronshapiro** 2018-03-23 19:06 UTC
