### ISSUE TITLE
Java annotation processor error in eclipse when having a dependency depth greater than 2

### ISSUE THREAD

**Issue by jeroendelooze** [google/dagger#312] opened 2016-02-10 19:26 UTC
When you have a project that has more than dagger module includes with a dependency depth greater than 2, dagger will give error when generating code.

I have added 2 examples to this issue. This are 2 example based on the dagger example simple. 
“Example-simple-depth2.zip“ has 2 maven projects that depend on each other -> No error when generating dagger code. 
“Example-simple-depth3.zip“ has 3 maven projects that depend on each other -> Error when generating dagger code. 
Both have been tested with dagger release version 2.0.2 and snapshot version 2.1-SNAPSHOT. Both give errors when going deeper then 2 dependencies, but not the same error.

The version that I have tested it on 2 machines both had are Eclipse (MARS(4.5.1) & NEON(M6)) and java 1.8 (1.8.0_65 and 1.8.0_72) and maven 3.3.9 on OSX 10.11.3
In Eclipse I have used M2E Maven integration is used, including integration for Annotation Processing. Also, in Eclipse Preferences, Maven > Annotation Processing is set to "JDT APT"

[example-simple-depth3.zip](https://github.com/google/dagger/files/125376/example-simple-depth3.zip)
[example-simple-depth2.zip](https://github.com/google/dagger/files/125377/example-simple-depth2.zip)

**Comment by jeroendelooze** [comment] 2016-03-07 08:05
Here is a stacktrace, maybe this will speed up the process

`java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
	at com.google.common.base.Absent.get(Absent.java:49)
	at dagger.internal.codegen.ModuleDescriptor$Factory.create(ModuleDescriptor.java:69)
	at dagger.internal.codegen.ModuleDescriptor$Factory.collectIncludedModules(ModuleDescriptor.java:116)
	at dagger.internal.codegen.ModuleDescriptor$Factory.create(ModuleDescriptor.java:89)
	at dagger.internal.codegen.ComponentDescriptor$Factory.create(ComponentDescriptor.java:244)
	at dagger.internal.codegen.ComponentDescriptor$Factory.forComponent(ComponentDescriptor.java:206)
	at dagger.internal.codegen.ComponentProcessingStep.componentDescriptors(ComponentProcessingStep.java:100)
	at dagger.internal.codegen.ComponentProcessingStep.componentDescriptors(ComponentProcessingStep.java:42)
	at dagger.internal.codegen.AbstractComponentProcessingStep.process(AbstractComponentProcessingStep.java:52)
	at dagger.internal.codegen.AbstractComponentProcessingStep.process(AbstractComponentProcessingStep.java:30)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:318)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:171)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:121)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:134)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:909)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:434)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:367)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:179)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:304)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:61)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:256)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:186)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
`

**Comment by ronshapiro** [comment] 2016-03-07 16:08
Looks like a duplicate of #273, feel free to reopen if it's not.

**Closed by ronshapiro** 2016-03-07 16:08 UTC

**Comment by jeroendelooze** [comment] 2016-03-08 08:42
Before i submitted this issue i already had found [#273](https://github.com/google/dagger/issues/273) and there the problem was that the @Module annotations was missing in module B. That is a other problem then what i'm discribing. Al annotations are correct in my example.
In short my problem is :

Error:
project A -> depedency @Module B
project B -> depedency @Module C
project C

NoError:
project A -> depedency @Module B
project B

Maybe its the same problem bud not the same issue.
