### ISSUE TITLE
[2.13] - warning: [classfile] MethodParameters attribute introduced in version 52.0 class files is ignored in version 51.0 class files

### ISSUE THREAD

**Issue by jaredsburrows** [google/dagger#945] opened 2017-11-10 06:52 UTC
# Error:
```
$ gradlew assembleDebug

> Task :compileDebugJavaWithJavac FAILED
/Users/<>/.gradle/caches/modules-2/files-2.1/com.google.dagger/dagger/2.13/37dc0fc55b65aa10f6e1edc4691a1231c904cfb1/dagger-2.13.jar(dagger/internal/DoubleCheck.class): warning: [classfile] MethodParameters attribute introduced in version 52.0 class files is ignored in version 51.0 class files
/Users/<>/.gradle/caches/modules-2/files-2.1/com.google.dagger/dagger/2.13/37dc0fc55b65aa10f6e1edc4691a1231c904cfb1/dagger-2.13.jar(dagger/internal/Preconditions.class): warning: [classfile] MethodParameters attribute introduced in version 52.0 class files is ignored in version 51.0 class files
/Users/<>/.gradle/caches/modules-2/files-2.1/com.google.dagger/dagger/2.13/37dc0fc55b65aa10f6e1edc4691a1231c904cfb1/dagger-2.13.jar(dagger/MembersInjector.class): warning: [classfile] MethodParameters attribute introduced in version 52.0 class files is ignored in version 51.0 class files
error: warnings found and -Werror specified
1 error
3 warnings


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
17 actionable tasks: 17 executed
```

**Comment by ronshapiro** [comment] 2017-11-10 15:51
Looks like @cushon added this in https://github.com/bazelbuild/bazel/commit/ff1bdb02e5a32983295c713f0ce9fba60142996e. Liam, is there a way to turn off `-parameters` when `-source 7 -target 7` is passed?

**Comment by ronshapiro** [comment] 2017-11-10 15:56
@jaredsburrows in the meantime you can disable `-Werror` if you need.

**Comment by jaredsburrows** [comment] 2017-11-10 16:06
@ronshapiro Yes, I purposely fail builds on warnings. Here is my example project: https://github.com/jaredsburrows/android-gif-example.

What is weird is that I am setting my source/target to Java 8 here: https://github.com/jaredsburrows/android-gif-example/blob/master/gradle/compile.gradle.kts#L5 based on https://github.com/jaredsburrows/android-gif-example/blob/master/gradle/dependencies.gradle.kts#L19.

Since I am using Java 8, I wonder why I still see this?

**Comment by tbroyer** [comment] 2017-11-10 16:12
@jaredsburrows The problem is that Dagger classes are in version 51.0 (compiled with `-source 7 -target 7`) but contain that attribute. Instead of turning off `-Werror` entirely, you could only silence that specific warning with `-Xlint:-classfile`.

**Comment by jaredsburrows** [comment] 2017-11-10 16:18
@tbroyer Yes, I know but what changed going from `2.12` to `2.13` that caused this issue?

**Comment by ronshapiro** [comment] 2017-11-10 16:30
We built with a newer version of Bazel that passed the `-parameters` flag to `javac` by default.

**Comment by cushon** [comment] 2017-11-10 18:10
javac shouldn't be emitting `MethodParameters` attributes to v51 and earlier class files: [JDK-8190452](https://bugs.openjdk.java.net/browse/JDK-8190452).

**Comment by sjudd** [comment] 2017-11-23 19:29
For posterity: ``new TransitionOptions().dontTransition()``

**Comment by ronshapiro** [comment] 2017-12-19 02:33
I'm going to close this in favor of the `javac` bug that @cushon filed. Not much more we can do with this (besides some hacks that I don't think we want to do).

**Closed by ronshapiro** 2017-12-19 02:33 UTC

**Comment by jhass** [comment] 2018-01-16 13:21
Given the sheer lack of any movement on this upstream, (ML report 2016-11, issue opened 2017-10, no activity in the ticket at all), any chance of reconsidering workarounds?

**Comment by cushon** [comment] 2018-01-16 18:21
I pinged the upstream thread.
Desugar could remove the attributes. Are you running dagger through desugar?

**Comment by ronshapiro** [comment] 2018-01-16 20:26
No, but if it's simple enough to wire up in bazel, it could solve this without needing a change from upstream.

**Comment by cushon** [comment] 2018-02-06 00:56
JDK-8190452 will be fixed in JDK 11...

**Comment by jhass** [comment] 2018-02-06 08:50
So I guess nine more months no updating dagger for me, unless... :P

**Comment by tir38** [comment] 2019-09-24 15:59
I'm late to the party here. But given this is fixed in JDK11, does that mean that this will not get fixed in Dagger classes until both Bazel is updated to work w/ JDK11 and Dagger is rebuilt with latest Bazel?
