### ISSUE TITLE
[Rant] May you change the coffee maker example to some other domain fewer people understand?

### ISSUE THREAD

**Issue by Villason** [google/dagger#609] opened 2017-03-04 11:34 UTC
Are you sure talking about thermosiphons and pumps is a good simplification to understand the framework?

I agree you should remove this post...

**Comment by ronshapiro** [comment] 2017-03-05 21:47
@gk5885 has been working on one that is much better documented and much clearer for exactly this purpose.

Because DI is pretty confusing to start with, we're going through a bunch of rounds to make sure we get something really good.

**Comment by ronshapiro** [comment] 2017-03-21 18:36
This is a dupe of #262

**Closed by ronshapiro** 2017-03-21 18:36 UTC
