### ISSUE TITLE
No Found Application on path: DexPathList.. after enabling "enableAggregatingTask"

### ISSUE THREAD

**Issue by aeroxr1** [google/dagger#2707] opened 2021-06-18 07:20 UTC
Versions:
Android Studio: 4.2.1
AGP: 4.2.1
Dagger: 2.37
Gradle Wrapper: 6.8

After enabling "enableAggregatingTask" the following error appear:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: aeroxr1.pocHybridHmsGms, PID: 4352
    java.lang.RuntimeException: Unable to instantiate application aeroxr1.pocHybridHmsGms.PocApplication: java.lang.ClassNotFoundException: Didn't find class "aeroxr1.pocHybridHmsGms.PocApplication" on path: DexPathList[[zip file "/data/app/aeroxr1.pocHybridHmsGms-PIMPYgH5RFukkxe5WJaD4w==/base.apk"],nativeLibraryDirectories=[/data/app/aeroxr1.pocHybridHmsGms-PIMPYgH5RFukkxe5WJaD4w==/lib/arm64, /data/app/aeroxr1.pocHybridHmsGms-PIMPYgH5RFukkxe5WJaD4w==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1296)
        at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7152)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7134)
        at android.app.ActivityThread.access$1600(ActivityThread.java:274)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "aeroxr1.pocHybridHmsGms.PocApplication" on path: DexPathList[[zip file "/data/app/aeroxr1.pocHybridHmsGms-PIMPYgH5RFukkxe5WJaD4w==/base.apk"],nativeLibraryDirectories=[/data/app/aeroxr1.pocHybridHmsGms-PIMPYgH5RFukkxe5WJaD4w==/lib/arm64, /data/app/aeroxr1.pocHybridHmsGms-PIMPYgH5RFukkxe5WJaD4w==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
        at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1156)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1288)
        at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7152) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7134) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:274) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:8167) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100) 
    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Laeroxr1/pocHybridHmsGms/Hilt_PocApplication;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        		... 15 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "aeroxr1.pocHybridHmsGms.Hilt_PocApplication" on path: DexPathList[[zip file "/data/app/aeroxr1.pocHybridHmsGms-PIMPYgH5RFukkxe5WJaD4w==/base.apk"],nativeLibraryDirectories=[/data/app/aeroxr1.pocHybridHmsGms-PIMPYgH5RFukkxe5WJaD4w==/lib/arm64, /data/app/aeroxr1.pocHybridHmsGms-PIMPYgH5RFukkxe5WJaD4w==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        		... 18 more
```

It's a poc project, if can help I give you its github repository link: [https://github.com/aeroxr1/ExampleAppWithHmsAndGms/tree/feature/hilt](https://github.com/aeroxr1/ExampleAppWithHmsAndGms/tree/feature/hilt)

**Comment by danysantiago** [comment] 2021-06-18 16:26
Closing as dupe of https://github.com/google/dagger/issues/2695, thanks!

**Closed by danysantiago** 2021-06-18 16:26 UTC
