### ISSUE TITLE
Build warning suppress

### ISSUE THREAD

**Issue by talentprince** [google/dagger#259] opened 2015-11-10 02:19 UTC
Hi team, so many build warning for generic inflect, will it be solved in feature release soon, I saw one TODO(gak) for months, but still not solved.

**Comment by ronshapiro** [comment] 2015-11-10 02:29
Can you clarify? Which warnings are you referring to? And in what
conditions do you see them? Can you reproduce in a small example?

**Comment by talentprince** [comment] 2015-11-10 02:47
ComponentGenerator 666 line.

My app update from dagger1, and 90% of warning is like this.

```
warning: [unchecked] unchecked conversion
    this.omnitureCacheProvider = OmnitureCache_Factory.create((MembersInjector) MembersInjectors.noOp(), providesAppDataProvider);
```

**Comment by tbroyer** [comment] 2015-11-10 09:01
This is a dupe of #199

**Closed** 2015-11-10 20:43 UTC
