### ISSUE TITLE
Open ContributesAndroidInjector for other classes 

### ISSUE THREAD

**Issue by PaulWoitaschek** [google/dagger#804] opened 2017-07-08 20:55 UTC
I'm using [Conductor](https://github.com/bluelinelabs/Conductor/issues) and created a `DispatchingAndroidInjector` for `Controllers` (like fragments from a dagger perspective).
That works great. 

However I want to make use of the `ContributesAndroidInjector` annotation because I don't want to go through all the boilerplate of creating subscomponents manually. However dagger fails with an exception that only framework classes are allowed.
What is the reason for that? Can it be done anyways?

**Comment by ronshapiro** [comment] 2017-07-09 02:33
This is unlikely to happen. We won't know which `@MapKey` to apply, base class to bind, etc. It's also likely to be abused for types that really should be constructor injected - I don't know anything about Conductor, but that's something to consider.

You're welcome to fork and do something similar if you'd like.

**Comment by PaulWoitaschek** [comment] 2017-07-09 13:07
Controllers are really similar to fragments and it's a real bummer creating so many subcomponents.

Isn't it possible to create some plugin structure where you can define your map `@MapKey` and base class?

**Comment by ronshapiro** [comment] 2017-07-09 14:38
Why can't you just `@Inject` your controller? or a Provider<Controller>?

**Comment by PaulWoitaschek** [comment] 2017-07-09 18:36
The same reason you can't just inject your fragments. The framework does the instantiation.

**Comment by PaulWoitaschek** [comment] 2017-07-17 15:00
So this is something you don't reconsider?

**Comment by charlag** [comment] 2017-07-19 15:29
It's really pity that the current mechanism is not extensible. I am considering using Conductor and it is quite disappointing. Maybe we should write some gradle plugin which can generate such subcomponents?

**Comment by hzsweers** [comment] 2017-07-23 20:40
Paul's proposal about a custom mapkey and base class seems reasonable

**Comment by sevar83** [comment] 2017-07-25 17:44
It would be great to eliminate the last piece of remaining boilerplate! In case someone knows how to write an annotation processor here's the original one:
https://github.com/google/dagger/blob/master/java/dagger/android/processor/ContributesAndroidInjectorGenerator.java
Porting it doesn't seem very hard for someone who already did an annotation processor.

**Comment by sevar83** [comment] 2017-07-26 19:32
I've just pushed a ported dagger.android.processor that enables automatic subcomponent generation by using a custom annotation `@ContributesControllerInjector` and `@ControllerKey`:
https://github.com/sevar83/conductor-dagger
It works with only one minor problem. You have to manually add the generated module class to the app component. Don't know the cause of the problem yet. Hope someone could find it.

**Comment by sevar83** [comment] 2017-08-06 10:33
For anyone interested: I report that my experiment doesn't work. The Dagger compiler collects only its own generated modules but not those for `Controller`s. By "own" I mean those generated by the `@ContributesAndroidInjector` annotation not by our custom `@ContributesControllerInjector`. The result is runtime exception. I suspect the check is inside `dagger.internal.codegen.ModuleDescriptor.collectImplicitlyIncludedModules()`:

```
// @ContributesAndroidInjector generates a module that is implicitly included in the enclosing
    // module
    private void collectImplicitlyIncludedModules(
        Set<ModuleDescriptor> includedModules, TypeElement moduleElement) {
      TypeElement contributesAndroidInjector =
          elements.getTypeElement("dagger.android.ContributesAndroidInjector");      // <------ HERE
      if (contributesAndroidInjector == null) {
        return;
      }
      for (ExecutableElement method : methodsIn(moduleElement.getEnclosedElements())) {
        if (isAnnotationPresent(method, contributesAndroidInjector.asType())) {
          includedModules.add(
              create(checkTypePresent(implicitlyIncludedModuleName(method), elements)));
        }
      }
    }
```

**Comment by hzsweers** [comment] 2017-08-06 10:36
I ran into that as well. It would be really useful if there was some added flexibility to facilitate other contributing processors

**Comment by artem-zinnatullin** [comment] 2017-08-07 01:18
But then Dagger will have to maintain compatibility of api for generated
code which can be problematic..

**Comment by IVIanuu** [comment] 2017-12-31 00:36
If any of you guys is interested i created a small library which makes it possible to @ContributesAndroidInjector for every type such as views or conductor controllers.
You can check it out here: https://github.com/IVIanuu/Contributer/

**Comment by ronshapiro** [comment] 2018-09-14 14:37
I'm reopening this - given the recent androidx developments and lots of new, smaller libraries, I think it's worth reconsidering opening up support.

**Comment by LeonRa** [comment] 2018-09-24 16:27
Happy to see this issue reopened! Is there any desire to extend `@ProvidesAndroidInjector` to `View`, as it itself is arguably an Android Framework type?

**Comment by yayaa** [comment] 2019-08-16 10:20
I also need that functionality even [submitted an issue](https://github.com/google/dagger/issues/958) a while ago, but back in then it was not considered at all. Really glad to see more people asks for it and now it is indeed in consideration 😍

Any updates or plans?

**Comment by Chang-Eric** [comment] 2020-07-14 23:27
Closing this as with Dagger Hilt's release there's unlikely to be large new features added to Dagger Android.

**Closed by Chang-Eric** 2020-07-14 23:27 UTC
