### ISSUE TITLE
Multibinding Key error: incompatible types: Class<SubType> cannot be converted to Class<? extends GenericSuperType<?,?>>

### ISSUE THREAD

**Issue by gfreivasc** [google/dagger#2000] opened 2020-07-24 18:03 UTC
This bug occurs when I try to pass the `Class<>` of a subtype of a generic abstract class to a multibinding key.

I have the following key:

```kotlin
@MapKey
@Retention(AnnotationRetention.BINARY)
@Target(AnnotationTarget.FUNCTION)
annotation class ControllerKey(val value: KClass<out Controller<*, *>>)
```

This breaks if I invoke it with
```kotlin
@Binds
@IntoMap
@ControllerKey(HomeController::class)
fun bindHomeController(controller: HomeController): Controller<*, *>
```
(The reason the method returns a wildcard `Controller` instead of the specific types is because that would lead to a weird behavior as seen on issue #385)

I expected it to deal properly with home controller, since it *is* an instance of `Controller<>`. Here are all possibly relevant classes declarations
```kotlin
interface State : Parcelable { /*...*/ }
abstract class Controller<S : State, A : Any> : Fragment() { /*...*/ }
class HomeController : Controller<HomeState, Nothing>() { /*...*/ }
data class HomeState(/*...*/) : State { /*...*/ }
```

If I dial up the hierarchy relationship, making `ControllerKey` expect `KClass<out Fragment>` instead of `KClass<out Controller<*, *>>`, everything works as expected, problem being I give up some of the cohesion of the system being modelled. Is that a problem with how I'm dealing with generics here or is it actually a bug?

**Comment by bcorso** [comment] 2020-07-28 20:49
> This breaks if I invoke it with
>
> ```kotlin
> @Binds
> @IntoMap
> @ControllerKey(HomeController::class)
> fun bindHomeController(controller: HomeController): Controller<*, *>
> ```

Can you explain more about how it breaks? E.g. do you get a compile-time Dagger error, or does it compile fine but the map is missing entries at run-time?

**Comment by gfreivasc** [comment] 2020-07-29 18:35
It is a compiler error which the linter fails to catch, because it appears within generated code. The error message reads as the title says.

```
error: incompatible types: Class<HomeController> cannot be converted to Class<? extends Controller<?,?>>
    @com.gabrielfv.arch_dagger.ControllerKey(value = com.gabrielfv.pay.home.HomeController.class)
```

The stub is generated but fails in task `:app:kaptDebugKotlin` specifically in the generated code that reads:

```java
@org.jetbrains.annotations.NotNull()
@com.gabrielfv.arch_dagger.ControllerKey(value = com.gabrielfv.pay.home.HomeController.class)
@dagger.multibindings.IntoMap()
@dagger.Binds()
public abstract com.gabrielfv.arch.Controller<?, ?> bindHomeController(@org.jetbrains.annotations.NotNull()
com.gabrielfv.pay.home.HomeController controller);
```

Didn't have much success translating the key to java.

**Comment by gfreivasc** [comment] 2020-08-13 18:23
Is any more info on the matter still necessary?

**Comment by bcorso** [comment] 2020-08-13 19:02
No, sorry this just slipped through the cracks.

This part does seem like a bug given your class defs: `Class<HomeController> cannot be converted to Class<? extends Controller<?,?>>`

I'll try to reproduce it at see what's up.

**Comment by bcorso** [comment] 2020-08-16 00:08
Sorry, I finally got around to looking at this. 

It looks like this is more of a Kotlin issue than Dagger. I'm not very familiar with Kotlin, but it seems that `Controller<HomeState, Nothing>` does not extend `Controller<*, *>`. More specifically, the issue seems to be the type, `Nothing`. If you use anything other type it works. Again, I know very little about Kotlin, so I can't really say why but StackOverflow is probably better place to ask that question.

Is there a reason you need to use `Nothing`? Could you define like a `Noop` class or something?

-----
Also, on an unrelated note, I think you can make your types slightly stricter. Specifically, you should be able to swap all of your `Controller<*, *>` with `Controller<out State, *>`

**Comment by gfreivasc** [comment] 2020-08-19 19:30
That's interesting. I do think it's not syntactically incorrect to say `Controller<HomeState, Nothing>` extends `Controller<*, *>` within kotlin but perhaps it doesn't translate so well to java/jvm. I'd have to verify that. I also believe `Unit` would make more sense here, but I've dropped that second type parameter completely in recent iterations.

**Comment by gfreivasc** [comment] 2020-08-20 23:12
Upon inspection, apparently there's no problem with inheritance relations between `Nothing` and wildcard.

```kotlin
fun interface Mapper<R, S> {
    fun map(r: R): S

    class ThrowMapper : Mapper<Int, Nothing> {
        override fun map(r: Int): Nothing {
            throw IllegalStateException()
        }
    }

    companion object {
        val registry: Map<String, Mapper<*, *>> = mapOf(
            "throw" to ThrowMapper()
        )

        fun get(key: String): Mapper<*, *> {
            return registry[key]!!
        }
    }
}
```

`ThrowMapper` works fine as both `Mapper<*, *>` in my kotlin tests and `Mapper<?, ?>` in my java tests.

```java
public class JavaScene {
    Mapper<?, ?> fromMethod() {
        return Mapper.Companion.get("throw");
    }

    Mapper<?, ?> fromRegistry() {
        return Mapper.Companion.getRegistry().get("throw");
    }

    Mapper<?, ?> getThrown() {
        return new Mapper.ThrowMapper();
    }
}
```
Compiles and passes with
```java
public class InheritanceJavaTest {
    @Test
    public void nothingIsWildcard() {
        assert new JavaScene().getThrown() instanceof Mapper<?, ?>;
    }

    @Test
    public void fromRegistryIsWildcard() {
        assert new JavaScene().fromRegistry() instanceof Mapper<?, ?>;
    }

    @Test
    public void fromMethodIsWildcard() {
        assert new JavaScene().fromMethod() instanceof Mapper<?, ?>;
    }
}
```

I believe, however, java doesn't deal well with `Nothing` at all, so perhaps its the case of discouraging its usage. Maybe there's a fix but idk, might be way beyond the scope.

**Comment by bcorso** [comment] 2020-08-20 23:46
Thanks!

I'm going to close this out because I don't think there's anything we can do about it from our side. I don't think we would want to discourage the usage of `Nothing` altogether because I think the issue only affected types passed into annotation values. It also may just be a bug in javac/kapt so filing a bug against them might be useful.

**Closed by bcorso** 2020-08-20 23:46 UTC
Labels: area: dagger, needs more information
