### ISSUE TITLE
Caused by: java.lang.RuntimeException:    at dagger.android.AndroidInjection.inject (AndroidInjection.java:49)

### ISSUE THREAD

**Issue by hueyenclave** [google/dagger#1462] opened 2019-04-02 03:59 UTC
Hi guys,

I have same issue with #891 but the ticket closed. I create new ticket here.

I got same problem reported on Google Play Console.

```
Caused by: java.lang.RuntimeException: 
  at dagger.android.AndroidInjection.inject (AndroidInjection.java:49)
  at com.sisow.hcvg.healthydiningguide.app.main.MainActivity.onCreate (MainActivity.java:218)
```

Following the line number on log trace, I think the issue might happens if `application` is null or `Application` class doesn't implemented `DaggerApplication` interface. But in my project, I already added my application class implemented `DaggerApplication`. **I have no idea which case it happens.**

```
  public static void inject(Activity activity) {
    checkNotNull(activity, "activity");
    Application application = activity.getApplication();
    if (!(application instanceof HasActivityInjector)) {
      throw new RuntimeException(  // Line 49
          String.format(
              "%s does not implement %s",
              application.getClass().getCanonicalName(),
              HasActivityInjector.class.getCanonicalName()));
    }

    AndroidInjector<Activity> activityInjector =
        ((HasActivityInjector) application).activityInjector();
    checkNotNull(activityInjector, "%s.activityInjector() returned null", application.getClass());

    activityInjector.inject(activity);
  }
```

I'm using dagger version `2.19` and the crashes report on some specific devices as below:

- LGE LG X screen (k5), Android 6.0
- Huawei nova 3i (HWINE), Android 8.1
- Huawei HUAWEI P smart 2019 (HWPOT-H), Android 9
- Samsung Galaxy J3(2017) (j3y17lte), Android 8.0
- Samsung Galaxy A8(2018) (jackpotlte), Android 8.0
- Samsung Galaxy Note9 (crownlte), Android 9
- Motorola Moto G Plus (5th Gen) (potter), Android 8.1

**Comment by ronshapiro** [comment] 2019-04-03 20:08
This looks like it's a duplicate of #748

**Closed by ronshapiro** 2019-04-03 20:08 UTC
