### ISSUE TITLE
SubComponents Whose Parents Don't Know About Them

### ISSUE THREAD

**Issue by AustinLMayes** [google/dagger#1292] opened 2018-09-25 18:13 UTC
Let me start off by saying that **this is not an Android project**, so I don't have access to any code created for use of this project in the Android environment.

So, I am creating a project that dynamically loads external JAR files (by directly adding them to the system class loader) which interact with the main project and should have access to any of the provisions available in the main `AppComponent`. Each jar holds a main subcomponent which defines anything needed by the classes contained in the jar. 

The issue I am facing is that the main project does not know about these external JARs (they are built against the main project, and depending on them would create a circular dependency) so there is no way to define these subcomponents in the `subComponents` field of the main component. 

The option I am currently using is creating a new instance of the injection scope for each jar. The issue with this is that any objects annotated with `@Singleton` would actually be created multiple times since, even though they are in the same class loader, dagger considers them as entirely different injection scopes. I am trying to find a way to "hook" into the main component and define subcomponents when the jars are loaded in order to get these base provisions. 

Any ideas?

**Comment by netdpb** [comment] 2018-09-25 18:47
Dagger subcomponents must be known when compiling their parent components, so I don't think they're going to work for your use case.

You may be able to use Dagger component dependencies (see the `dependencies` parameter to `@Component`) to get some of what you want. You could take what are now your subcomponents and make them into `@Component`s that depend on your `@Singleton` component. They would have access only to the bindings represented by the singleton component's entry point methods, and not any other bindings that are not exposed in that way.

**Comment by netdpb** [comment] 2018-09-25 18:50
This is really a question, not a bug, so I'm going to close this issue. Feel free to start a conversation on dagger-discuss@googlegroups.com as well.

**Closed by netdpb** 2018-09-25 18:50 UTC
