### ISSUE TITLE
with AGP 4.2.x, 7.0.0 / java.lang.IllegalAccessError: Method 'boolean[] com.sebiya.myapplication.ktx.LiveDataExtKt.$jacocoInit()' is inaccessible to class 'com.sebiya.myapplication.ktx.LiveDataExtTest$test$1'  during instrumentation test

### ISSUE THREAD

**Issue by kshdreams** [google/dagger#2804] opened 2021-08-10 02:32 UTC
Versions
- Hilt: 2.38.1
- AGP: 4.2.x, 7.0.0
- Gradle: 7.0.2-all

I've got below exception during android instrumentation test with hilt

```
--------- beginning of main
08-10 11:05:58.239 10364 25204 25237 E TestRunner: failed: test(com.sebiya.myapplication.ktx.LiveDataExtTest)
08-10 11:05:58.239 10364 25204 25237 E TestRunner: ----- begin exception -----
08-10 11:05:58.240 10364 25204 25237 E TestRunner: java.lang.IllegalAccessError: Method 'boolean[] com.sebiya.myapplication.ktx.LiveDataExtKt.$jacocoInit()' is inaccessible to class 'com.sebiya.myapplication.ktx.LiveDataExtTest$test$1' (declaration of 'com.sebiya.myapplication.ktx.LiveDataExtTest$test$1' appears in /data/app/com.sebiya.myapplication.test-M9bh20Enr1T3hIa4Y5a1tA==/base.apk!classes4.dex)
08-10 11:05:58.240 10364 25204 25237 E TestRunner: 	at com.sebiya.myapplication.ktx.LiveDataExtTest$test$1.invokeSuspend(LiveDataExtTest.kt:11)
08-10 11:05:58.240 10364 25204 25237 E TestRunner: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-10 11:05:58.240 10364 25204 25237 E TestRunner: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
08-10 11:05:58.240 10364 25204 25237 E TestRunner: 	at android.os.Handler.handleCallback(Handler.java:883)
08-10 11:05:58.240 10364 25204 25237 E TestRunner: 	at android.os.Handler.dispatchMessage(Handler.java:100)
08-10 11:05:58.240 10364 25204 25237 E TestRunner: 	at android.os.Looper.loop(Looper.java:237)
08-10 11:05:58.240 10364 25204 25237 E TestRunner: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
08-10 11:05:58.240 10364 25204 25237 E TestRunner: 	at java.lang.reflect.Method.invoke(Native Method)
08-10 11:05:58.240 10364 25204 25237 E TestRunner: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
08-10 11:05:58.240 10364 25204 25237 E TestRunner: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
08-10 11:05:58.240 10364 25204 25237 E TestRunner: ----- end exception -----
08-10 11:05:58.241 10364 25204 25237 I TestRunner: finished: test(com.sebiya.myapplication.ktx.LiveDataExtTest)

java.lang.IllegalAccessError: Method 'boolean[] com.sebiya.myapplication.ktx.LiveDataExtKt.$jacocoInit()' is inaccessible to class 'com.sebiya.myapplication.ktx.LiveDataExtTest$test$1' (declaration of 'com.sebiya.myapplication.ktx.LiveDataExtTest$test$1' appears in /data/app/com.sebiya.myapplication.test-M9bh20Enr1T3hIa4Y5a1tA==/base.apk!classes4.dex)
	at com.sebiya.myapplication.ktx.LiveDataExtTest$test$1.invokeSuspend(LiveDataExtTest.kt:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```

it seems to happen when using an inline function in test target package.

app module code (test target package)
```
LiveDataExt.kt

inline fun <T> LiveData<T>.filter(crossinline  predicate: (T) -> Boolean): LiveData<T> {
    return MediatorLiveData<T>().apply {
        addSource(this@filter) {
            if (predicate(it)) {
                value = it
            }
        }
    }
}
```

app module test (test package)
```
LiveDataExtTest.kt

class LiveDataExtTest {
    @Test
    fun test() = runBlocking(Dispatchers.Main) {
        MutableLiveData("test").filter { it != null }.observeForever {
            Log.d("test", it)
        }
    }
}
```

An exception is not thrown when testing with the following combinations.

- agp 4.1.0 + hilt 2.38.1 
- agp 7.0.0 + hilt 2.29-alpha 

you can reproduce issue with below repository
https://github.com/kshdreams/agp_hilt_jacoco_runtime_issue

**Comment by danysantiago** [comment] 2021-08-16 15:23
I'm not 100% sure what is going on but looks like the Jacoco's transform somehow conflicts when a transform is registered via the Android Gradle Plugin (Hilt has a small transform).

I tried your sample app and the error makes sense... Jacoco's injects a `private static` init method in the class and all method bodies call it but since you have an inline function the init call is inlined in other places where the method is not accessible.

Downloading your app an simply running `./gradlew connectedAndroidTest` fails with:
```
* What went wrong:
Execution failed for task ':app:createDebugAndroidTestCoverageReport'.
> A failure occurred while executing com.android.build.gradle.internal.coverage.JacocoReportTask$JacocoReportWorkerAction
   > Unable to generate Jacoco report
```
which is already a bad start. Now when running the tests from Android Studio it passes without the Hilt plugin applied, once the Hilt plugin is applied the test fails with the `IllegalAccessError`.

I don't think this is an error in Hilt though, I have a feeling that any other plugin who registers a transform and Jacoco is turned ON will cause an issue.

Its best if you file a bug to the Android Gradle Team here: https://issuetracker.google.com/issues/new?component=192708&template=840533 since they own the Jacoco integration of AGP and the ASM Transform pipeline that Hilt uses.

**Comment by kshdreams** [comment] 2021-08-18 04:54
https://issuetracker.google.com/issues/109771903

This problem was previously registered and resolved on the AGP side, 
but it seems to have recently reproduced and the above ticket has been reopened.

However, it is a little strange that the problem is not reproduced in the hilt 2.29-alpha version ^^;;

**Comment by danysantiago** [comment] 2021-08-18 11:42
The reason why the issue is not in 2.29-alpha or when AGP 4.1.0 is used, is because it was not until [Hilt 2.31](https://github.com/google/dagger/releases/tag/dagger-2.31) that Hilt migrated to using the newer ASM transform that is available in AGP 4.2.0.

**Comment by kshdreams** [comment] 2021-08-19 04:37
I understand the newer ASM transform was the problem.
Thanks for sharing and replying :D

**Comment by danysantiago** [comment] 2021-09-03 17:45
Will close this one out since the fix is in AGP and there is no code change for us.

**Closed by danysantiago** 2021-09-03 17:45 UTC
Labels: needs investigation
