### ISSUE TITLE
2.38 - lateinit property workerFactory has not been initialized

### ISSUE THREAD

**Issue by slavonnet** [google/dagger#2766] opened 2021-07-21 05:12 UTC
```

@HiltAndroidApp
class MyApplication : Application(), Configuration.Provider {

    @Inject
    internal lateinit var workerFactory: HiltWorkerFactory

    override fun getWorkManagerConfiguration() =
        Configuration.Builder()
            .setExecutor(Dispatchers.Default.asExecutor())
            .setWorkerFactory(workerFactory)
            .setTaskExecutor(Dispatchers.Default.asExecutor())
            .setMaxSchedulerLimit(MAX_SCHEDULER_LIMIT)
            .build()

    
```

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.cisystems.ssmp.arm_vmb2, PID: 13731
    java.lang.RuntimeException: Unable to create service com.cisystems.ssmp.arm_vmb2.services.HeartbeatService: kotlin.UninitializedPropertyAccessException: lateinit property workerFactory has not been initialized
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3544)
        at android.app.ActivityThread.access$1300(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property workerFactory has not been initialized
        at com.cisystems.ssmp.arm_vmb2.MyApplication.getWorkerFactory$app_minApi23Debug(MyApplication.kt:37)
        at com.cisystems.ssmp.arm_vmb2.MyApplication.getWorkManagerConfiguration(MyApplication.kt:42)
        at androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl.java:155)
        at androidx.work.WorkManager.getInstance(WorkManager.java:184)
        at com.cisystems.ssmp.arm_vmb2.workers.DirectoryUpdateWorker$Companion.stop$app_minApi23Debug(DirectoryUpdateWorker.kt:337)
        at com.cisystems.ssmp.arm_vmb2.services.HeartbeatService$Companion.stopExecutes(HeartbeatService.kt:57)
        at com.cisystems.ssmp.arm_vmb2.services.HeartbeatService$Companion.access$stopExecutes(HeartbeatService.kt:36)
        at com.cisystems.ssmp.arm_vmb2.services.HeartbeatService.onCreate(HeartbeatService.kt:66)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3532)
        at android.app.ActivityThread.access$1300(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by b95505017** [comment] 2021-07-21 05:42
Same issue here, it doesn't swapped to `Hilt_MyApplication`, so all members won't be injected.

**Comment by BugsBunnyBR** [comment] 2021-07-23 07:37
the method `getWorkManagerConfiguration()` can be called when the ContentProviders are initialised (start-up library), it happens close to the call of `Application.attachBaseContext()` method and before `Application.onCreate()`, if Hilt is injecting the class in the `onCreate()` that would happen.

I have the same issue even without hilt, moving the inject() method to `attachBaseContext()` helped reduce the number of times it happens..., the workaround for now would be not using Dagger/Hilt for that factory if possible.

**Comment by bcorso** [comment] 2021-07-23 16:06
@BugsBunnyBR if this is an issue with ContentProviders calling before `onCreate()` you should be able to fix that issue by using an entry point instead of relying on field injection. For example:

```
@HiltAndroidApp
class MyApplication : Application(), Configuration.Provider {

    @EntryPoint
    @InstallIn(SingletonComponent::class)
    interface HiltWorkerFactoryEntryPoint {
        fun workerFactory(): HiltWorkerFactory
    }

    override fun getWorkManagerConfiguration() =
        Configuration.Builder()
            .setExecutor(Dispatchers.Default.asExecutor())
            .setWorkerFactory(EntryPoints.get(this, HiltWorkerFactoryEntryPoint::class.java).workerFactory())
            .setTaskExecutor(Dispatchers.Default.asExecutor())
            .setMaxSchedulerLimit(MAX_SCHEDULER_LIMIT)
            .build()
}
```

The entry point will take initiative to create the component if it's not already created.

**Comment by slavonnet** [comment] 2021-07-25 12:29
> @BugsBunnyBR if this is an issue with ContentProviders calling before `onCreate()` you should be able to fix that issue by using an entry point instead of relying on field injection. For example:
> 
> ```
> @HiltAndroidApp
> class MyApplication : Application(), Configuration.Provider {
> 
>     @EntryPoint
>     @InstallIn(SingletonComponent::class)
>     interface HiltWorkerFactoryEntryPoint {
>         fun workerFactory(): HiltWorkerFactory
>     }
> 
>     override fun getWorkManagerConfiguration() =
>         Configuration.Builder()
>             .setExecutor(Dispatchers.Default.asExecutor())
>             .setWorkerFactory(EntryPoints.get(this, HiltWorkerFactoryEntryPoint::class.java).workerFactory())
>             .setTaskExecutor(Dispatchers.Default.asExecutor())
>             .setMaxSchedulerLimit(MAX_SCHEDULER_LIMIT)
>             .build()
> }
> ```
> 
> The entry point will take initiative to create the component if it's not already created.

I try you quick fix (i use KSP for hilt compiler):

```
E/Coroutine: Thread[main,5,main]
    java.lang.RuntimeException: Unable to create service com.cisystems.ssmp.arm_vmb2.services.HeartbeatService: java.lang.IllegalStateException: Given component holder class com.cisystems.ssmp.arm_vmb2.MyApplication does not implement interface dagger.hilt.internal.GeneratedComponent or interface dagger.hilt.internal.GeneratedComponentManager
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3544)
        at android.app.ActivityThread.access$1300(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: Given component holder class com.cisystems.ssmp.arm_vmb2.MyApplication does not implement interface dagger.hilt.internal.GeneratedComponent or interface dagger.hilt.internal.GeneratedComponentManager
        at dagger.hilt.EntryPoints.get(EntryPoints.java:62)
        at com.cisystems.ssmp.arm_vmb2.MyApplication.getWorkManagerConfiguration(MyApplication.kt:54)
        at androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl.java:155)
        at androidx.work.WorkManager.getInstance(WorkManager.java:184)
        at com.cisystems.ssmp.arm_vmb2.workers.DirectoryUpdateWorker$Companion.stop$app_minApi23Debug(DirectoryUpdateWorker.kt:338)
        at com.cisystems.ssmp.arm_vmb2.services.HeartbeatService$Companion.stopExecutes(HeartbeatService.kt:57)
        at com.cisystems.ssmp.arm_vmb2.services.HeartbeatService$Companion.access$stopExecutes(HeartbeatService.kt:36)
        at com.cisystems.ssmp.arm_vmb2.services.HeartbeatService.onCreate(HeartbeatService.kt:66)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3532)
        at android.app.ActivityThread.access$1300(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by bcorso** [comment] 2021-07-26 16:07
@slavonnet Hilt does not support KSP yet. You will need to use Kapt.

**Comment by Chang-Eric** [comment] 2021-07-26 21:41
The original report sounds like #2784 is the cause. Closing this assuming that is the case.

**Closed by Chang-Eric** 2021-07-26 21:41 UTC

**Comment by mveroukis** [comment] 2025-07-21 22:46
It's 2025 and I still need @bcorso 's solution of using EntryPoint. If I try to use @Inject in my Application class to get the HiltWorkerFactory the app crashes because nothing gets injected by the time it's referencing the workManagerConfiguration property. That would be fine, however, the official docs for Hilt and Worker still mention that as the proper way to make that work. Very annoying, wasted many hours of my time.
