### ISSUE TITLE
Hilt - injecting ViewModel via navGraphViewModels issue

### ISSUE THREAD

**Issue by silentnuke** [google/dagger#2152] opened 2020-10-19 20:23 UTC
Hello,
I had an issue with restoring state of injected viewmodel via navGraphViewModels. 
I saw the recommended way for injectig viewmodels with the Jetpack navigation library (https://github.com/google/dagger/issues/1935), [2](https://developer.android.com/training/dependency-injection/hilt-jetpack#viewmodel-navigation), however after process death `ViewModel` is not restored correctly on the second screen of navGraph.

I created [demo project](https://github.com/silentnuke/HiltNavGraphViewModelsIssue) which demostrates the issue. We have a nested navigation graph `R.id.nested` which consists of 2 fragments. Those 2 fragments shares `MainViewModel` and `MainViewModel2` which are completely similar and contains `LiveData<String>`.
The only difference is that first ViewModel initialized with fragment's `defaultViewModelProviderFactory` as recommended with Hilt, while second is initialized without passing custom factory, so uses backStackEntry's `defaultViewModelProviderFactory` (will not work when Hilt is used, but to demosntrate the problem).
```kotlin
    private val viewModel by navGraphViewModels<MainViewModel>(R.id.nested) {
        defaultViewModelProviderFactory
    }
    
    private val viewModel2 by navGraphViewModels<MainViewModel2>(R.id.nested)
 ```

First fragment in nested graph sets message to both viewmodels and then opens Second fragment.  
With `Don't keep activities` enabled, putting app to background and back, triggers app process death and restore.  
After process restore, `MainViewModel` doesn't have the value from First fragment and shows the default one, while `MainViewModel2` is restored correctly and displays proper message.  

1. Enter message on FirstFragment and open SecondFragment.  
*On SecondFragment both viewmodels have correct values.*
2. Background app with `Don't keep activities` to trigger process death and come back.  
*On SecondFragment first viewmodel doesn't have restored value, second viewmodel has as expected.*
3. Press back to return on FirstFragment and open SecondFragment again  
*On SecondFragment both viewmodels have correct values.*
4. Background app with `Don't keep activities` to trigger process death and come back.  
*On SecondFragment both viewmodels contains correct value, even if you modify value on FirstFragment.*
5. Press back to return on FirstFragment, Background app with `Don't keep activities` and open SecondFragment.
*On SecondFragment both viewmodels have correct values.*
6. Background app with `Don't keep activities` to trigger process death and come back.  
*On SecondFragment first viewmodel doesn't have restored value, second viewmodel has as expected.*

![demo](https://user-images.githubusercontent.com/13165815/96507414-6ae95d00-1259-11eb-8e97-5bf0c4f78dbc.gif)

**Comment by Chang-Eric** [comment] 2020-10-27 21:10
Thanks for the repro case and detailed write up. Just to clarify, you're running into this issue even when not using Hilt, right? The reason this is related to Hilt is that https://github.com/google/dagger/issues/1935 recommends passing in the defaultViewModelProviderFactory to navGraphViewModels and this causes the issue?

**Comment by silentnuke** [comment] 2020-10-27 21:27
@Chang-Eric yes, this issue reproduces without Hilt when passing fragment's `defaultViewModelProviderFactory` to `navGraphViewModels`.
The reason this is related to Hilt is that with Hilt there is no way to use `navGraphViewModels` without passing fragment's `defaultViewModelProviderFactory` and this is recommened way in the [docs](https://developer.android.com/training/dependency-injection/hilt-jetpack#viewmodel-navigation). Without Hilt **backStackEntry's** `defaultViewModelProviderFactory` is used by default which doesn't have that issue.

**Comment by danysantiago** [comment] 2020-11-05 23:38
The root cause of the issue is that the `defaultViewModelProviderFactory` from an activity or fragment uses the activity itself as the `SavedStateRegistryOwner` and that is different from the `ViewModelStoreOwner` used by the `NavBackStack`. It seems these two should be the same, which is exactly what is going on with the `HiltViewModelFactory` too, it uses the activity or fragment as `SavedStateRegistryOwner` which is different from the `ViewModelStoreOwner` that is used by the `ViewModelProvider` by the`NavBackStack`.

We are investigating a solution but sadly I don't have a workaround for now. We might either expose a builder / factory for `HiltViewModelFactory` (which is odd) or we might work with AndroidX itself to make it so that these two owners are in sync.

**Comment by Zhuinden** [comment] 2020-12-01 07:06
For now, in my sample, what I tried doing is:

- add [an accessor entrypoint for classes that need to be accessed to build a viewmodel](https://github.com/Zhuinden/jetpack-navigation-ftue-sample/commit/c6fa4db5d706549c876a0a09900d74bd4654fbd7#diff-59bdeb72ede0297e067d3e57611fda93accd361d2e0a2479366a6ae7ef5a7393R30)

- use an [old solution to pass the AbstractSavedStateViewModelFactory to the NavBackStackEntry as the ViewModelStoreOwner so that it can be used as both ViewModelStoreOwner and SavedStateRegistryOwner](https://github.com/Zhuinden/jetpack-navigation-ftue-sample/commit/c6fa4db5d706549c876a0a09900d74bd4654fbd7#diff-219a8736c6810e39f46ddde54f7020d88034e3536f53e355c5c77b85b52f99f6R34)

- create ViewModel [using the accessors to get the dependencies](https://github.com/Zhuinden/jetpack-navigation-ftue-sample/commit/c6fa4db5d706549c876a0a09900d74bd4654fbd7#diff-219a8736c6810e39f46ddde54f7020d88034e3536f53e355c5c77b85b52f99f6R36)

And the ugliest part:

- [try to find an component in the hierarchy from which the accessor can be obtained](https://github.com/Zhuinden/jetpack-navigation-ftue-sample/commit/c6fa4db5d706549c876a0a09900d74bd4654fbd7#diff-a70c3e7ee68c6dcd5ab6234e186d168d62abfb996bd0d6cca2c78347058f8974R27). Due to how `activityRetainedComponentManager` seems inaccessible apart from reflection, the code is [in fact using reflection](https://github.com/Zhuinden/jetpack-navigation-ftue-sample/commit/c6fa4db5d706549c876a0a09900d74bd4654fbd7#diff-a70c3e7ee68c6dcd5ab6234e186d168d62abfb996bd0d6cca2c78347058f8974R44).

Not nice, but state restoration seems to work on my second screen now as well. It's unfortunate that I had not noticed earlier, considering that apparently the views restoring their own state has bamboozled me. :frowning:

**Comment by Zhuinden** [comment] 2021-01-28 21:04
Fixed by `hiltNavGraphViewModels` in `hilt-navigation-fragment`

**Closed** 2021-01-28 21:26 UTC
Labels: P2, area: hilt, type: bug
