### ISSUE TITLE
Dagger Hilt with library modules

### ISSUE THREAD

**Issue by kelmer44** [google/dagger#2064] opened 2020-08-25 11:04 UTC
I have a project A which depends on B, which depends on C. Like so:

A --> B --> C

Now C has some fragments that require injection; upon using Dagger Hilt and trying to run, I get the following exception:

java.lang.ClassCastException: `com.example.myapp.DaggerRtlNlApplication_HiltComponents_ApplicationC$ActivityRetainedCImpl$ActivityCImpl$FragmentCImpl cannot be cast to com.example.myapp.gigya.ui.LoginFragment_GeneratedInjector
`
If I include module C in A, then it works.

As I understand Hilt requires that the compiling gradle module contains all the subsequent modules, but this kind of beats the purpose of multi module. Is there a way to overcome this?

**Comment by danysantiago** [comment] 2020-08-26 15:32
Are the dependency declaration `implementation` or `api`? If they are `implementation` then that could explain the issue, since the injection code is generated in the root Gradle module (the app usually) it needs to have visibility to the injected classes in transitive modules and by using `implementation` you restrict the compile time classpath.

**Comment by kelmer44** [comment] 2020-08-27 07:17
Well regardless, it's kind of the same situation. I'd like to be able to change C without A being recompiled, if I use api then that ability is also gone right?

**Comment by danysantiago** [comment] 2020-08-27 16:29
Not necessarily. As far as I know compile avoidance is still present even if the dependency declarations are `api`. For example if you change a method body, or the signature of a private method, it should not cause dependant libraries to recompile even if those are declared with `api`. However, if you change a public method, say in C, then it might have to recompile both A and B where as if it was `implementation` it would only need to recompile B.

This is a long standing issue in Dagger and present in Hilt too (see https://github.com/google/dagger/issues/970 and https://github.com/google/dagger/issues/1991 for some context). We are working with the Android Gradle Team to come up with a solution but it's a hard problem solve correctly.

**Comment by kelmer44** [comment] 2020-09-02 10:36
Gotcha. Guess using api is my best bet for now.

**Comment by Chang-Eric** [comment] 2020-09-22 22:10
Closing this since it is a duplicate of #1991

**Closed by Chang-Eric** 2020-09-22 22:10 UTC
